import type { CustomerBrief } from './types';

export const WORDS: readonly string[] = [
  'Microondas',
  'Calcetín',
  'Dinosaurio',
  'Radio',
  'Paraguas',
  'Café',
  'Cohete',
  'Globo',
  'Queso',
  'Linterna',
  'Robot',
  'Almohada',
  'Burbuja',
  'Taladro',
  'Piña',
  'Imán',
  'Salsa',
  'Casco',
  'Whisky',
  'Wifi',
  'Mermelada',
  'Drone',
  'Cactus',
  'Ventilador',
  'Mochila',
  'Láser',
  'Sandalia',
  'Batería',
  'Sirena',
  'Chocolate',
  'Tornillo',
  'Nube',
  'Espejo',
  'Kayak',
  'Perfume',
  'Trampolín',
  'Cuchara',
  'Hashtag',
  'Meme',
  'Podcast',
  'Tubería',
  'Sombrero',
  'Hielo',
  'Veneno',
  'Tesoro',
  'Laberinto',
  'Selfie',
  'Guante',
  'Cargador',
  'Tambor',
  'Volcán',
  'Arcoíris',
  'Píldora',
  'Antena',
  'Espuma',
  'Filtro',
  'Radar',
  'Silla',
  'Puente',
  'Diamante',
  'Plástico',
  'Algoritmo',
  'Streaming',
  'Inodoro',
  'Gorila',
  'Faro',
  'Semilla',
  'Chicle',
  'Cuerda',
  'Máscara',
  'Olla',
  'Tijeras',
  'Trampa',
  'Vacuna',
  'Zumo',
  'Reloj',
  'Puerta',
  'Bolsillo',
  'Cebo',
  'Disfraz',
  'Humedad',
  'Electricidad',
  'Gasolina',
  'Castillo',
  'Cueva',
  'Jungla',
  'Desierto',
  'Niebla',
  'Tormenta',
  'Eco',
  'Ruido',
  'Sabor',
  'Olor',
  'Baile',
  'Silencio',
  'Caos',
  'Milagro',
  'Desastre',
  'Secreto',
  'Chisme',
  'Orgullo',
  'Envidia',
  'Pereza',
  'Hambre',
  'Sed',
  'Risa',
  'Llanto',
  'Magia',
  'Poder',
  'Tiempo',
  'Futuro',
  'Pasado',
  'Fiesta',
  'Trabajo',
  'Vacaciones',
  'Amor',
  'Miedo',
  'Sueño',
  'Mentira',
  'Verdad',
  'Suerte',
  'Grito',
  'Beso',
  'Drama',
];

export const ADULT_WORDS: readonly string[] = [
  'After',
  'Resaca',
  'Tinder',
  'Ex',
  'Celos',
  'Tentación',
  'Hotel',
  'Medianoche',
  'Champán',
  'Escándalo',
  'Ligoteo',
  'Borracho',
  'Confesión',
  'Chantaje',
  'Deseo',
];

export const CUSTOMERS: readonly CustomerBrief[] = [
  {
    id: 'astro-cats',
    title: 'Astronauta',
    need: 'Un astronauta que tiene miedo a los gatos y va a una estación con mascotas.',
    emoji: '🧑‍🚀',
  },
  {
    id: 'vampire-beach',
    title: 'Vampiro',
    need: 'Un vampiro que quiere ir a la playa sin convertirse en polvo.',
    emoji: '🧛',
  },
  {
    id: 'humble-politician',
    title: 'Político',
    need: 'Un político que quiere parecer humilde sin dejar de ser famoso.',
    emoji: '🗳️',
  },
  {
    id: 'kid-ferrari',
    title: 'Niño',
    need: 'Un niño que quiere convencer a sus padres de que necesita un Ferrari.',
    emoji: '🧒',
  },
  {
    id: 'pirate-water',
    title: 'Pirata',
    need: 'Un pirata con miedo al agua que sigue queriendo mandar un barco.',
    emoji: '🏴‍☠️',
  },
  {
    id: 'last-earth',
    title: 'Última persona',
    need: 'La última persona en la Tierra busca compañía… o al menos un gadget.',
    emoji: '🌍',
  },
  {
    id: 'spy-date',
    title: 'Espía',
    need: 'Una espía que necesita ligar en una cena sin revelar su identidad.',
    emoji: '🕵️',
  },
  {
    id: 'chef-burn',
    title: 'Chef',
    need: 'Un chef estrella al que se le queman hasta los tostados.',
    emoji: '👨‍🍳',
  },
  {
    id: 'monk-wifi',
    title: 'Monje',
    need: 'Un monje que ha descubierto el WiFi y no sabe cómo volver a la calma.',
    emoji: '🧘',
  },
  {
    id: 'alien-ikea',
    title: 'Extraterrestre',
    need: 'Un extraterrestre perdido en IKEA que solo entiende señales de tráfico.',
    emoji: '👽',
  },
  {
    id: 'grandma-tiktok',
    title: 'Abuela',
    need: 'Una abuela que quiere hacerse viral en TikTok sin que la estafen.',
    emoji: '👵',
  },
  {
    id: 'dj-silence',
    title: 'DJ',
    need: 'Un DJ que ha perdido el oído izquierdo y el sentido del tempo.',
    emoji: '🎧',
  },
  {
    id: 'robot-feelings',
    title: 'Robot',
    need: 'Un robot que acaba de sentir celos por primera vez.',
    emoji: '🤖',
  },
  {
    id: 'bride-chaos',
    title: 'Novia',
    need: 'Una novia el día de la boda a la que se le ha escapado el pastel.',
    emoji: '👰',
  },
  {
    id: 'detective-socks',
    title: 'Detective',
    need: 'Un detective que solo resuelve crímenes relacionados con calcetines perdidos.',
    emoji: '🔍',
  },
  {
    id: 'influencer-truth',
    title: 'Influencer',
    need: 'Una influencer que necesita parecer auténtica en un anuncio pagado.',
    emoji: '📱',
  },
  {
    id: 'firefighter-cats',
    title: 'Bombero',
    need: 'Un bombero alérgico a los gatos que siempre los rescata de árboles.',
    emoji: '🚒',
  },
  {
    id: 'scientist-soup',
    title: 'Científica',
    need: 'Una científica loca que intenta demostrar que la sopa tiene conciencia.',
    emoji: '🧪',
  },
  {
    id: 'king-bored',
    title: 'Rey',
    need: 'Un rey medieval aburrido de que todo el mundo le diga que sí.',
    emoji: '👑',
  },
  {
    id: 'ghost-roommate',
    title: 'Fantasma',
    need: 'Un fantasma amable que quiere ser buen compañero de piso.',
    emoji: '👻',
  },
  {
    id: 'surfer-office',
    title: 'Surfista',
    need: 'Un surfista obligado a trabajar en una oficina sin ventanas.',
    emoji: '🏄',
  },
  {
    id: 'teacher-chaos',
    title: 'Profe',
    need: 'Una profesora con una clase de 30 niños el día anterior a vacaciones.',
    emoji: '👩‍🏫',
  },
  {
    id: 'millionaire-bored',
    title: 'Multimillonario',
    need: 'Un multimillonario aburrido que ya lo ha comprado todo… dos veces.',
    emoji: '💰',
  },
  {
    id: 'mermaid-city',
    title: 'Sirena',
    need: 'Una sirena que se ha mudado a Madrid y echa de menos el mar.',
    emoji: '🧜',
  },
];

export const ADULT_CUSTOMERS: readonly CustomerBrief[] = [
  {
    id: 'ex-toxic',
    title: 'Ex tóxico',
    need: 'Un ex tóxico que quiere “solo quedar a hablar” a las 3 de la mañana.',
    emoji: '💔',
  },
  {
    id: 'after-diva',
    title: 'Diva del after',
    need: 'Una diva del after que necesita llegar a casa sin que amanezca.',
    emoji: '🥂',
  },
  {
    id: 'hangover-sunday',
    title: 'Resacoso',
    need: 'Un resacoso de domingo que tiene una comida familiar en una hora.',
    emoji: '🥴',
  },
];

export function wordPool(adultMode: boolean): string[] {
  if (!adultMode) return [...WORDS];
  return [...WORDS, ...ADULT_WORDS];
}

export function customerPool(adultMode: boolean): CustomerBrief[] {
  if (!adultMode) return [...CUSTOMERS];
  return [...CUSTOMERS, ...ADULT_CUSTOMERS];
}
