import type {
  Customer,
  Difficulty,
  ObjectionType,
  TwistEvent,
  WordCard,
} from './types';

export const OBJECTION_TYPES: readonly ObjectionType[] = [
  { id: 'price', label: 'Precio', promptHint: 'Queja por el precio o valor.', minDifficulty: 'easy' },
  { id: 'doubt', label: 'Duda', promptHint: 'Duda de que funcione de verdad.', minDifficulty: 'easy' },
  { id: 'logic', label: 'Lógica', promptHint: 'Pregunta lógica sencilla sobre el uso.', minDifficulty: 'easy' },
  { id: 'fear', label: 'Miedo', promptHint: 'Miedo a un efecto secundario absurdo.', minDifficulty: 'easy' },
  { id: 'comparison', label: 'Comparación', promptHint: 'Compara con algo que ya tiene.', minDifficulty: 'normal' },
  { id: 'time', label: 'Tiempo', promptHint: 'No tiene tiempo para aprender a usarlo.', minDifficulty: 'easy' },
  { id: 'trust', label: 'Confianza', promptHint: 'Desconfía del vendedor.', minDifficulty: 'normal' },
  { id: 'identity', label: 'Identidad', promptHint: 'Cree que el producto no encaja con quién es.', minDifficulty: 'normal' },
  { id: 'side_effect', label: 'Efecto secundario', promptHint: 'Inventa un efecto secundario inquietante.', minDifficulty: 'normal' },
  { id: 'absurd_literal', label: 'Literal', promptHint: 'Toma una metáfora del pitch de forma literal.', minDifficulty: 'normal' },
  { id: 'contradiction', label: 'Contradicción', promptHint: 'Señala una contradicción en el pitch.', minDifficulty: 'hard' },
  { id: 'status', label: 'Estatus', promptHint: 'Le preocupa qué pensarán los demás.', minDifficulty: 'normal' },
  { id: 'practicality', label: 'Práctica', promptHint: 'Pregunta por logística absurda (pilas, tamaño, limpieza).', minDifficulty: 'easy' },
  { id: 'emotion', label: 'Emoción', promptHint: 'Reacciona con drama emocional exagerado.', minDifficulty: 'easy' },
  { id: 'rival', label: 'Rival', promptHint: 'Dice que un rival ya le ofreció algo similar.', minDifficulty: 'normal' },
  { id: 'legality', label: 'Legalidad', promptHint: 'Sospecha que es ilegal o prohibido.', minDifficulty: 'hard' },
  { id: 'comfort', label: 'Comodidad', promptHint: 'Le parece incómodo o poco estético.', minDifficulty: 'easy' },
  { id: 'surprise', label: 'Sorpresa', promptHint: 'Objeción completamente inesperada pero en personaje.', minDifficulty: 'hard' },
  { id: 'morality', label: 'Moral', promptHint: 'Cuestiona si es ético venderle esto.', minDifficulty: 'hard' },
  { id: 'patience', label: 'Paciencia', promptHint: 'Se está quedando sin paciencia y pide el cierre YA.', minDifficulty: 'normal' },
];

export const WORDS: readonly WordCard[] = [
  { word: 'Paraguas', tags: ['sol', 'agua', 'playa', 'protección'] },
  { word: 'Calcetín', tags: ['ropa', 'pies', 'comodidad', 'secreto'] },
  { word: 'Radio', tags: ['sonido', 'comunicación', 'ruido'] },
  { word: 'Microondas', tags: ['comida', 'calor', 'casa'] },
  { word: 'Dinosaurio', tags: ['miedo', 'poder', 'pasado', 'absurdo'] },
  { word: 'Café', tags: ['energía', 'mañana', 'olor'] },
  { word: 'Cohete', tags: ['espacio', 'velocidad', 'viaje'] },
  { word: 'Globo', tags: ['aire', 'fiesta', 'elevación'] },
  { word: 'Queso', tags: ['comida', 'olor', 'lujo'] },
  { word: 'Linterna', tags: ['luz', 'oscuridad', 'miedo'] },
  { word: 'Robot', tags: ['tecnología', 'compañía', 'trabajo'] },
  { word: 'Almohada', tags: ['sueño', 'comodidad', 'silencio'] },
  { word: 'Burbuja', tags: ['protección', 'fragilidad', 'aire'] },
  { word: 'Taladro', tags: ['ruido', 'poder', 'herramienta'] },
  { word: 'Piña', tags: ['comida', 'tropical', 'fiesta'] },
  { word: 'Imán', tags: ['atracción', 'metal', 'magia'] },
  { word: 'Salsa', tags: ['comida', 'sabor', 'caos'] },
  { word: 'Casco', tags: ['protección', 'guerra', 'seguridad'] },
  { word: 'Whisky', tags: ['lujo', 'noche', 'valentía'] },
  { word: 'Wifi', tags: ['tecnología', 'conexión', 'adicción'] },
  { word: 'Mermelada', tags: ['dulce', 'casa', 'abuela'] },
  { word: 'Drone', tags: ['vigilancia', 'aire', 'tecnología'] },
  { word: 'Cactus', tags: ['desierto', 'protección', 'soledad'] },
  { word: 'Ventilador', tags: ['aire', 'calor', 'ruido'] },
  { word: 'Mochila', tags: ['viaje', 'secreto', 'carga'] },
  { word: 'Láser', tags: ['tecnología', 'precisión', 'peligro'] },
  { word: 'Sandalia', tags: ['playa', 'verano', 'comodidad'] },
  { word: 'Batería', tags: ['energía', 'tecnología', 'urgencia'] },
  { word: 'Sirena', tags: ['mar', 'canto', 'peligro'] },
  { word: 'Chocolate', tags: ['dulce', 'consuelo', 'lujo'] },
  { word: 'Tornillo', tags: ['herramienta', 'fijación', 'detalle'] },
  { word: 'Nube', tags: ['cielo', 'sueño', 'lluvia'] },
  { word: 'Espejo', tags: ['identidad', 'verdad', 'vanidad'] },
  { word: 'Kayak', tags: ['agua', 'viaje', 'equilibrio'] },
  { word: 'Perfume', tags: ['olor', 'atracción', 'lujo'] },
  { word: 'Trampolín', tags: ['salto', 'riesgo', 'fiesta'] },
  { word: 'Cuchara', tags: ['comida', 'casa', 'simple'] },
  { word: 'Hashtag', tags: ['viral', 'redes', 'estatus'] },
  { word: 'Meme', tags: ['humor', 'viral', 'absurdo'] },
  { word: 'Podcast', tags: ['voz', 'historia', 'compañía'] },
  { word: 'Sombrero', tags: ['estatus', 'disfraz', 'sol'] },
  { word: 'Hielo', tags: ['frío', 'bebida', 'tiempo'] },
  { word: 'Tesoro', tags: ['dinero', 'secreto', 'aventura'] },
  { word: 'Laberinto', tags: ['confusión', 'juego', 'miedo'] },
  { word: 'Selfie', tags: ['vanidad', 'redes', 'prueba'] },
  { word: 'Guante', tags: ['protección', 'toque', 'disfraz'] },
  { word: 'Cargador', tags: ['energía', 'urgencia', 'tecnología'] },
  { word: 'Tambor', tags: ['ruido', 'ritmo', 'fiesta'] },
  { word: 'Volcán', tags: ['peligro', 'calor', 'drama'] },
  { word: 'Arcoíris', tags: ['magia', 'esperanza', 'color'] },
  { word: 'Píldora', tags: ['cura', 'riesgo', 'secreto'] },
  { word: 'Antena', tags: ['señal', 'comunicación', 'espacio'] },
  { word: 'Espuma', tags: ['suave', 'baño', 'fiesta'] },
  { word: 'Filtro', tags: ['verdad', 'redes', 'protección'] },
  { word: 'Radar', tags: ['detección', 'miedo', 'espionaje'] },
  { word: 'Silla', tags: ['descanso', 'oficina', 'estatus'] },
  { word: 'Puente', tags: ['conexión', 'viaje', 'riesgo'] },
  { word: 'Diamante', tags: ['lujo', 'estatus', 'brillo'] },
  { word: 'Algoritmo', tags: ['tecnología', 'destino', 'control'] },
  { word: 'Inodoro', tags: ['absurdo', 'casa', 'urgencia'] },
  { word: 'Gorila', tags: ['fuerza', 'miedo', 'protección'] },
  { word: 'Faro', tags: ['luz', 'mar', 'guía'] },
  { word: 'Semilla', tags: ['futuro', 'crecimiento', 'esperanza'] },
  { word: 'Chicle', tags: ['pegajoso', 'infantil', 'tiempo'] },
  { word: 'Cuerda', tags: ['rescate', 'trampa', 'unión'] },
  { word: 'Máscara', tags: ['identidad', 'disfraz', 'miedo'] },
  { word: 'Olla', tags: ['comida', 'presión', 'casa'] },
  { word: 'Tijeras', tags: ['corte', 'decisión', 'peligro'] },
  { word: 'Trampa', tags: ['engaño', 'caza', 'astucia'] },
  { word: 'Reloj', tags: ['tiempo', 'urgencia', 'lujo'] },
  { word: 'Puerta', tags: ['oportunidad', 'secreto', 'salida'] },
  { word: 'Bolsillo', tags: ['secreto', 'dinero', 'robo'] },
  { word: 'Disfraz', tags: ['identidad', 'fiesta', 'espionaje'] },
  { word: 'Electricidad', tags: ['energía', 'peligro', 'modernidad'] },
  { word: 'Castillo', tags: ['lujo', 'defensa', 'fantasía'] },
  { word: 'Cueva', tags: ['escondite', 'miedo', 'secreto'] },
  { word: 'Jungla', tags: ['caos', 'aventura', 'naturaleza'] },
  { word: 'Desierto', tags: ['soledad', 'calor', 'supervivencia'] },
  { word: 'Niebla', tags: ['confusión', 'misterio', 'ocultar'] },
  { word: 'Tormenta', tags: ['caos', 'drama', 'peligro'] },
  { word: 'Eco', tags: ['memoria', 'voz', 'soledad'] },
  { word: 'Ruido', tags: ['caos', 'oficina', 'molestia'] },
  { word: 'Silencio', tags: ['paz', 'secreto', 'tensión'] },
  { word: 'Caos', tags: ['desorden', 'fiesta', 'improvisación'] },
  { word: 'Milagro', tags: ['magia', 'esperanza', 'engaño'] },
  { word: 'Secreto', tags: ['confidencial', 'poder', 'chantaje'] },
  { word: 'Chisme', tags: ['redes', 'drama', 'información'] },
  { word: 'Pereza', tags: ['comodidad', 'trabajo', 'evasión'] },
  { word: 'Hambre', tags: ['comida', 'urgencia', 'deseo'] },
  { word: 'Risa', tags: ['humor', 'alivio', 'contagio'] },
  { word: 'Magia', tags: ['imposible', 'espectáculo', 'engaño'] },
  { word: 'Tiempo', tags: ['urgencia', 'reloj', 'viaje'] },
  { word: 'Futuro', tags: ['tecnología', 'miedo', 'promesa'] },
  { word: 'Vacaciones', tags: ['playa', 'descanso', 'fuga'] },
  { word: 'Miedo', tags: ['pánico', 'protección', 'valor'] },
  { word: 'Sueño', tags: ['descanso', 'fantasía', 'inconsciente'] },
  { word: 'Mentira', tags: ['engaño', 'política', 'teatro'] },
  { word: 'Suerte', tags: ['azar', 'juego', 'esperanza'] },
  { word: 'Drama', tags: ['teatro', 'emoción', 'exageración'] },
  { word: 'Bocina', tags: ['ruido', 'alerta', 'atención'] },
  { word: 'Pizza', tags: ['comida', 'fiesta', 'consuelo'] },
  { word: 'Brújula', tags: ['dirección', 'viaje', 'pérdida'] },
  { word: 'Paracaídas', tags: ['rescate', 'riesgo', 'aire'] },
  { word: 'Candado', tags: ['secreto', 'seguridad', 'celos'] },
  { word: 'Termómetro', tags: ['salud', 'miedo', 'control'] },
  { word: 'Bufanda', tags: ['frío', 'estilo', 'disfraz'] },
  { word: 'Martillo', tags: ['fuerza', 'reparación', 'caos'] },
  { word: 'Velcro', tags: ['fijación', 'infantil', 'práctica'] },
  { word: 'Auricular', tags: ['sonido', 'aislamiento', 'música'] },
  { word: 'Mapa', tags: ['viaje', 'pérdida', 'tesoro'] },
  { word: 'Jabón', tags: ['limpieza', 'olvido', 'ritual'] },
  { word: 'Tostadora', tags: ['mañana', 'fuego', 'casa'] },
  { word: 'Parche', tags: ['arreglo', 'herida', 'improvisación'] },
  { word: 'Megáfono', tags: ['voz', 'protesta', 'atención'] },
  { word: 'Peluca', tags: ['disfraz', 'identidad', 'teatro'] },
];

export const ADULT_WORDS: readonly WordCard[] = [
  { word: 'After', tags: ['noche', 'fiesta', 'caos'] },
  { word: 'Resaca', tags: ['dolor', 'mañana', 'arrepentimiento'] },
  { word: 'Tinder', tags: ['ligar', 'espejo', 'mentira'] },
  { word: 'Ex', tags: ['drama', 'celos', 'memoria'] },
  { word: 'Tentación', tags: ['deseo', 'riesgo', 'noche'] },
  { word: 'Hotel', tags: ['secreto', 'lujo', 'fuga'] },
  { word: 'Champán', tags: ['lujo', 'fiesta', 'estatus'] },
  { word: 'Escándalo', tags: ['drama', 'redes', 'riesgo'] },
];

function C(
  partial: Omit<Customer, 'patience' | 'skepticism' | 'humor'> & {
    patience: number;
    skepticism: number;
    humor: number;
  },
): Customer {
  return partial;
}

export const CUSTOMERS: readonly Customer[] = [
  C({
    id: 'vampire-beach',
    name: 'El Vampiro',
    description: 'Un vampiro elegante que quiere disfrutar de unas vacaciones en la playa.',
    personality: 'Elegante, dramático y extremadamente preocupado por el sol.',
    need: 'Quiere disfrutar de unas vacaciones en la playa sin convertirse en polvo.',
    secretConcern: 'Le aterra parecer un turista normal.',
    patience: 55,
    skepticism: 70,
    humor: 65,
    emoji: '🧛',
    tags: ['sol', 'playa', 'protección', 'noche', 'lujo'],
  }),
  C({
    id: 'pirate-lost',
    name: 'El Pirata',
    description: 'Un pirata que pierde constantemente objetos en el mar.',
    personality: 'Desconfiado, brusco y obsesionado con el precio.',
    need: 'Quiere dejar de perder objetos en el mar.',
    secretConcern: 'No sabe nadar del todo bien.',
    patience: 35,
    skepticism: 85,
    humor: 40,
    emoji: '🏴‍☠️',
    tags: ['agua', 'tesoro', 'mar', 'dinero', 'aventura'],
  }),
  C({
    id: 'kid-absurd',
    name: 'El Niño',
    description: 'Un niño que quiere algo que sus padres consideran absurdo.',
    personality: 'Insistente, imaginativo y muy manipulador.',
    need: 'Quiere conseguir algo que sus padres consideran absurdo.',
    secretConcern: 'Sus padres ya han dicho que no tres veces.',
    patience: 80,
    skepticism: 25,
    humor: 90,
    emoji: '🧒',
    tags: ['juguete', 'magia', 'padres', 'absurdo', 'fiesta'],
  }),
  C({
    id: 'astro-alone',
    name: 'El Astronauta',
    description: 'Un astronauta con miedo a quedarse solo en el espacio.',
    personality: 'Técnico, ansioso y sediento de compañía.',
    need: 'Quiere no sentirse solo en la estación espacial.',
    secretConcern: 'Habla con las plantas y le da vergüenza.',
    patience: 60,
    skepticism: 55,
    humor: 50,
    emoji: '🧑‍🚀',
    tags: ['espacio', 'soledad', 'compañía', 'tecnología', 'miedo'],
  }),
  C({
    id: 'politician-humble',
    name: 'El Político',
    description: 'Un político que quiere parecer humilde sin dejar de ser famoso.',
    personality: 'Resbaladizo, vanidoso y adicto a los titulares.',
    need: 'Quiere parecer humilde en cámara.',
    secretConcern: 'Su ego necesita aplausos cada 12 minutos.',
    patience: 40,
    skepticism: 75,
    humor: 45,
    emoji: '🗳️',
    tags: ['estatus', 'mentira', 'redes', 'teatro', 'poder'],
  }),
  C({
    id: 'spy-date',
    name: 'La Espía',
    description: 'Una espía que necesita ligar sin revelar su identidad.',
    personality: 'Fría, sarcástica y hiperobservadora.',
    need: 'Quiere ligar en una cena sin delatarse.',
    secretConcern: 'Se le escapa el acento falso cuando bebe.',
    patience: 50,
    skepticism: 90,
    humor: 55,
    emoji: '🕵️',
    tags: ['identidad', 'secreto', 'disfraz', 'atracción', 'espionaje'],
  }),
  C({
    id: 'chef-burn',
    name: 'El Chef',
    description: 'Un chef estrella al que se le quema hasta el agua.',
    personality: 'Orgulloso, explosivo y perfeccionista herido.',
    need: 'Quiere volver a cocinar sin humillar a su brigada.',
    secretConcern: 'Come noodles a escondidas.',
    patience: 30,
    skepticism: 65,
    humor: 35,
    emoji: '👨‍🍳',
    tags: ['comida', 'fuego', 'orgullo', 'caos', 'presión'],
  }),
  C({
    id: 'monk-wifi',
    name: 'El Monje',
    description: 'Un monje que descubrió el WiFi y perdió la calma.',
    personality: 'Sereno en teoría, adicto en la práctica.',
    need: 'Quiere recuperar la paz sin renunciar del todo a internet.',
    secretConcern: 'Tiene 47 pestañas abiertas de memes.',
    patience: 70,
    skepticism: 40,
    humor: 70,
    emoji: '🧘',
    tags: ['paz', 'adicción', 'tecnología', 'silencio', 'caos'],
  }),
  C({
    id: 'alien-ikea',
    name: 'El Extraterrestre',
    description: 'Un alien perdido en IKEA que no entiende humanos.',
    personality: 'Literal, curioso y peligrosamente confiado.',
    need: 'Quiere entender a los humanos lo bastante para salir de la tienda.',
    secretConcern: 'Cree que las baldas son un sistema de castas.',
    patience: 85,
    skepticism: 20,
    humor: 80,
    emoji: '👽',
    tags: ['confusión', 'casa', 'herramienta', 'idioma', 'viaje'],
  }),
  C({
    id: 'grandma-tiktok',
    name: 'La Abuela',
    description: 'Una abuela que quiere hacerse viral sin que la estafen.',
    personality: 'Dulce, desconfiada con bancos y valiente en trends.',
    need: 'Quiere viralidad segura.',
    secretConcern: 'Ya envió dinero a un príncipe una vez.',
    patience: 65,
    skepticism: 80,
    humor: 75,
    emoji: '👵',
    tags: ['viral', 'redes', 'seguridad', 'familia', 'baile'],
  }),
  C({
    id: 'dj-tempo',
    name: 'El DJ',
    description: 'Un DJ que ha perdido el oído izquierdo y el tempo.',
    personality: 'Nocturno, dramático y adicto al feedback.',
    need: 'Quiere volver a pinchar sin que lo abucheen.',
    secretConcern: 'Baila mejor que mezcla.',
    patience: 45,
    skepticism: 50,
    humor: 60,
    emoji: '🎧',
    tags: ['sonido', 'fiesta', 'ritmo', 'ruido', 'noche'],
  }),
  C({
    id: 'robot-jealous',
    name: 'El Robot',
    description: 'Un robot que acaba de sentir celos por primera vez.',
    personality: 'Lógico, literal y emocionalmente nuevo.',
    need: 'Quiere gestionar los celos sin cortocircuito.',
    secretConcern: 'Envidia a una tostadora.',
    patience: 90,
    skepticism: 60,
    humor: 40,
    emoji: '🤖',
    tags: ['emoción', 'tecnología', 'celos', 'lógica', 'compañía'],
  }),
  C({
    id: 'bride-chaos',
    name: 'La Novia',
    description: 'Una novia el día de la boda con el pastel desaparecido.',
    personality: 'Al borde del colapso, perfeccionista y sentimental.',
    need: 'Quiere salvar la boda en 20 minutos.',
    secretConcern: 'El pastel estaba mejor que el novio.',
    patience: 15,
    skepticism: 55,
    humor: 30,
    emoji: '👰',
    tags: ['urgencia', 'fiesta', 'drama', 'comida', 'estatus'],
  }),
  C({
    id: 'detective-socks',
    name: 'El Detective',
    description: 'Un detective especializado en calcetines perdidos.',
    personality: 'Serio, obsesivo y ridículamente solemne.',
    need: 'Quiere resolver el caso del calcetín desaparecido.',
    secretConcern: 'Él mismo tiene un cajón caótico.',
    patience: 50,
    skepticism: 85,
    humor: 45,
    emoji: '🔍',
    tags: ['misterio', 'calcetín', 'prueba', 'lógica', 'secreto'],
  }),
  C({
    id: 'influencer-authentic',
    name: 'La Influencer',
    description: 'Una influencer que necesita parecer auténtica en un anuncio.',
    personality: 'Brillante, insegura y adicta al engagement.',
    need: 'Quiere vender sin parecer que vende.',
    secretConcern: 'Su “mañana natural” tarda 90 minutos.',
    patience: 40,
    skepticism: 70,
    humor: 55,
    emoji: '📱',
    tags: ['redes', 'verdad', 'filtro', 'estatus', 'viral'],
  }),
  C({
    id: 'firefighter-cats',
    name: 'El Bombero',
    description: 'Un bombero alérgico a los gatos que siempre los rescata.',
    personality: 'Heroico, resignado y estornudón.',
    need: 'Quiere rescatar gatos sin hincharse como un globo.',
    secretConcern: 'Le gustan los gatos… a distancia.',
    patience: 55,
    skepticism: 45,
    humor: 60,
    emoji: '🚒',
    tags: ['protección', 'alergia', 'rescate', 'miedo', 'deber'],
  }),
  C({
    id: 'scientist-soup',
    name: 'La Científica',
    description: 'Una científica que cree que la sopa tiene conciencia.',
    personality: 'Brillante, caótica y convincentemente loca.',
    need: 'Quiere demostrar su teoría sin que la echen del lab.',
    secretConcern: 'Habla con el caldo.',
    patience: 60,
    skepticism: 35,
    humor: 70,
    emoji: '🧪',
    tags: ['ciencia', 'comida', 'locura', 'prueba', 'futuro'],
  }),
  C({
    id: 'king-bored',
    name: 'El Rey',
    description: 'Un rey medieval aburrido de que todos le digan que sí.',
    personality: 'Caprichoso, teatral y peligroso cuando se aburre.',
    need: 'Quiere algo que le diga la verdad… o al menos le entretenga.',
    secretConcern: 'Extraña que alguien le lleve la contraria.',
    patience: 25,
    skepticism: 50,
    humor: 55,
    emoji: '👑',
    tags: ['poder', 'lujo', 'verdad', 'teatro', 'aburrimiento'],
  }),
  C({
    id: 'ghost-roommate',
    name: 'El Fantasma',
    description: 'Un fantasma amable que quiere ser buen compañero de piso.',
    personality: 'Educado, melancólico y un poco clingy.',
    need: 'Quiere convivir sin asustar a la gente.',
    secretConcern: 'Se pone triste si nadie le deja notas.',
    patience: 75,
    skepticism: 30,
    humor: 65,
    emoji: '👻',
    tags: ['casa', 'compañía', 'miedo', 'silencio', 'amabilidad'],
  }),
  C({
    id: 'surfer-office',
    name: 'El Surfista',
    description: 'Un surfista atrapado en una oficina sin ventanas.',
    personality: 'Relajado, rebelde y alérgico a las reuniones.',
    need: 'Quiere sentir el océano sin dimitir… todavía.',
    secretConcern: 'Su fondo de pantalla es una ola en loop.',
    patience: 50,
    skepticism: 40,
    humor: 75,
    emoji: '🏄',
    tags: ['mar', 'libertad', 'oficina', 'aire', 'vacaciones'],
  }),
  C({
    id: 'teacher-chaos',
    name: 'La Profe',
    description: 'Una profesora con 30 niños el día antes de vacaciones.',
    personality: 'Cansada, ingeniosa y al borde del sarcasmo.',
    need: 'Quiere sobrevivir la última hora de clase.',
    secretConcern: 'Sueña con una baja fingida.',
    patience: 20,
    skepticism: 60,
    humor: 70,
    emoji: '👩‍🏫',
    tags: ['caos', 'niños', 'control', 'ruido', 'urgencia'],
  }),
  C({
    id: 'millionaire-bored',
    name: 'El Multimillonario',
    description: 'Un multimillonario que ya lo compró todo dos veces.',
    personality: 'Blasé, exigente y fácilmente impresionable por lo absurdo.',
    need: 'Quiere algo que no pueda comprar… o eso cree.',
    secretConcern: 'Le aburre hasta su propio yate.',
    patience: 30,
    skepticism: 90,
    humor: 50,
    emoji: '💰',
    tags: ['lujo', 'aburrimiento', 'novedad', 'estatus', 'dinero'],
  }),
  C({
    id: 'mermaid-city',
    name: 'La Sirena',
    description: 'Una sirena mudada a Madrid que echa de menos el mar.',
    personality: 'Poética, dramática y maladaptada urbana.',
    need: 'Quiere recuperar el mar en el asfalto.',
    secretConcern: 'Llora en las fuentes públicas.',
    patience: 55,
    skepticism: 45,
    humor: 60,
    emoji: '🧜',
    tags: ['mar', 'ciudad', 'nostalgia', 'agua', 'magia'],
  }),
  C({
    id: 'last-earth',
    name: 'La Última Persona',
    description: 'La última persona en la Tierra busca compañía.',
    personality: 'Melancólica, ingeniosa y peligrosamente abierta a cualquier gadget.',
    need: 'Quiere no sentirse tan sola.',
    secretConcern: 'Habla con maniquíes y no lo juzgues.',
    patience: 80,
    skepticism: 25,
    humor: 55,
    emoji: '🌍',
    tags: ['soledad', 'compañía', 'fin', 'tecnología', 'esperanza'],
  }),
  C({
    id: 'ninja-noise',
    name: 'El Ninja',
    description: 'Un ninja cuyo piso nuevo cruje demasiado.',
    personality: 'Disciplinado, silencioso y muy literal.',
    need: 'Quiere moverse sin que lo oigan ni los vecinos.',
    secretConcern: 'Pisa fuerte cuando tiene hambre.',
    patience: 70,
    skepticism: 65,
    humor: 25,
    emoji: '🥷',
    tags: ['silencio', 'sigilo', 'casa', 'disciplina', 'ruido'],
  }),
  C({
    id: 'vampire-accountant',
    name: 'El Contable Nocturno',
    description: 'Un contable vampiro harto de turnos de noche eternos.',
    personality: 'Metódico, quejica y obsesionado con el Excel.',
    need: 'Quiere optimizar su eternidad laboral.',
    secretConcern: 'Le dan miedo las auditorías.',
    patience: 45,
    skepticism: 80,
    humor: 35,
    emoji: '🧾',
    tags: ['noche', 'trabajo', 'tiempo', 'orden', 'estrés'],
  }),
  C({
    id: 'clown-serious',
    name: 'El Payaso Serio',
    description: 'Un payaso que quiere que por fin le tomen en serio.',
    personality: 'Melancólico, talentoso y sensible a las risas.',
    need: 'Quiere respeto profesional sin dejar de ser payaso.',
    secretConcern: 'Llora con documentales de pingüinos.',
    patience: 50,
    skepticism: 55,
    humor: 85,
    emoji: '🤡',
    tags: ['humor', 'estatus', 'teatro', 'emoción', 'identidad'],
  }),
  C({
    id: 'time-tourist',
    name: 'La Turista del Tiempo',
    description: 'Una viajera temporal perdida en el siglo XXI.',
    personality: 'Curiosa, impaciente y llena de spoilers.',
    need: 'Quiere orientarse sin estropear la línea temporal.',
    secretConcern: 'Ya sabe quién gana Eurovisión… y se le escapa.',
    patience: 40,
    skepticism: 50,
    humor: 70,
    emoji: '⏳',
    tags: ['tiempo', 'viaje', 'futuro', 'confusión', 'mapa'],
  }),
  C({
    id: 'dragon-hoa',
    name: 'El Dragón de Comunidad',
    description: 'Un dragón que preside la comunidad de vecinos.',
    personality: 'Autoritario, fogoso y obsesionado con las actas.',
    need: 'Quiere imponer orden sin quemar el edificio.',
    secretConcern: 'Le dan alergia los boletines.',
    patience: 20,
    skepticism: 75,
    humor: 40,
    emoji: '🐉',
    tags: ['fuego', 'poder', 'casa', 'reglas', 'estatus'],
  }),
  C({
    id: 'barista-art',
    name: 'La Barista',
    description: 'Una barista que odia cuando piden “un café normal”.',
    personality: 'Artista, snob del grano y agotada.',
    need: 'Quiere que valoren su arte líquido.',
    secretConcern: 'Bebe café de máquina a escondidas.',
    patience: 35,
    skepticism: 60,
    humor: 55,
    emoji: '☕',
    tags: ['café', 'arte', 'mañana', 'orgullo', 'sabor'],
  }),
  C({
    id: 'gamer-sleep',
    name: 'El Gamer',
    description: 'Un gamer que no ha dormido en 36 horas y tiene un examen.',
    personality: 'Paranoico, creativo y hiperconectado.',
    need: 'Quiere aprobar… o al menos parecer despierto.',
    secretConcern: 'Su rango es más alto que su media.',
    patience: 25,
    skepticism: 40,
    humor: 80,
    emoji: '🎮',
    tags: ['sueño', 'energía', 'tecnología', 'urgencia', 'caos'],
  }),
  C({
    id: 'witch-modern',
    name: 'La Bruja Moderna',
    description: 'Una bruja que intenta adaptar hechizos a apps.',
    personality: 'Mística, práctica y cansada de clientes “aesthetic”.',
    need: 'Quiere magia compatible con smartphone.',
    secretConcern: 'Su caldera es una Instant Pot.',
    patience: 55,
    skepticism: 45,
    humor: 65,
    emoji: '🧙',
    tags: ['magia', 'tecnología', 'ritual', 'moderno', 'poder'],
  }),
  C({
    id: 'mailman-dogs',
    name: 'El Cartero',
    description: 'Un cartero perseguido por todos los perros del barrio.',
    personality: 'Resiliente, nervioso y profesional hasta el final.',
    need: 'Quiere entregar paquetes sin ser el almuerzo.',
    secretConcern: 'Le gustan los perros… en fotos.',
    patience: 45,
    skepticism: 50,
    humor: 50,
    emoji: '📬',
    tags: ['miedo', 'protección', 'trabajo', 'velocidad', 'calle'],
  }),
  C({
    id: 'actor-forgot',
    name: 'El Actor',
    description: 'Un actor que olvida el texto minutos antes de salir.',
    personality: 'Dramático, vanidoso y en pánico elegante.',
    need: 'Quiere improvisar sin que se note.',
    secretConcern: 'Solo recuerda los anuncios de yogurt.',
    patience: 20,
    skepticism: 35,
    humor: 60,
    emoji: '🎭',
    tags: ['teatro', 'memoria', 'pánico', 'estatus', 'improvisación'],
  }),
  C({
    id: 'farmer-wifi',
    name: 'La Agricultora',
    description: 'Una agricultora cuya cosecha depende de una app inestable.',
    personality: 'Práctica, sarcástica y harta de actualizaciones.',
    need: 'Quiere que la tecnología deje de arruinarle los tomates.',
    secretConcern: 'Habla a las plantas mejor que a la app.',
    patience: 50,
    skepticism: 70,
    humor: 55,
    emoji: '🚜',
    tags: ['naturaleza', 'tecnología', 'comida', 'paciencia', 'caos'],
  }),
  C({
    id: 'yeti-heat',
    name: 'El Yeti',
    description: 'Un yeti que se mudó a un clima demasiado cálido.',
    personality: 'Tímido, peludo y siempre sudando.',
    need: 'Quiere refrescarse sin derretirse socialmente.',
    secretConcern: 'Odia los selfies térmicos.',
    patience: 60,
    skepticism: 40,
    humor: 50,
    emoji: '🧊',
    tags: ['frío', 'calor', 'disfraz', 'comodidad', 'viaje'],
  }),
  C({
    id: 'librarian-chaos',
    name: 'La Bibliotecaria',
    description: 'Una bibliotecaria en guerra contra el ruido infinito.',
    personality: 'Estricta, ingeniosa y potencialmente terrorífica.',
    need: 'Quiere silencio… o al menos una tregua.',
    secretConcern: 'Escucha heavy metal con auriculares.',
    patience: 30,
    skepticism: 65,
    humor: 40,
    emoji: '📚',
    tags: ['silencio', 'orden', 'ruido', 'control', 'secreto'],
  }),
  C({
    id: 'pilot-fear',
    name: 'El Piloto',
    description: 'Un piloto comercial que acaba de descubrir miedo a volar.',
    personality: 'Profesional, en crisis y muy consciente de la ironía.',
    need: 'Quiere subir al avión sin drama visible.',
    secretConcern: 'Prefiere el tren, pero no lo admite.',
    patience: 40,
    skepticism: 55,
    humor: 45,
    emoji: '✈️',
    tags: ['miedo', 'aire', 'trabajo', 'control', 'valentía'],
  }),
  C({
    id: 'dentist-phobia',
    name: 'La Dentista',
    description: 'Una dentista con fobia a… los dientes ajenos.',
    personality: 'Competente, contradictoria y ansiosa.',
    need: 'Quiere ejercer sin pánico.',
    secretConcern: 'Sueña con encías que hablan.',
    patience: 45,
    skepticism: 50,
    humor: 35,
    emoji: '🦷',
    tags: ['miedo', 'trabajo', 'control', 'protección', 'ironía'],
  }),
  C({
    id: 'superhero-laundry',
    name: 'El Superhéroe',
    description: 'Un superhéroe cuya capa nunca sale limpia.',
    personality: 'Épico, inseguro y muy de marca personal.',
    need: 'Quiere lucir heroico sin oler a lavadora pública.',
    secretConcern: 'Su archienemigo tiene mejor tintorería.',
    patience: 50,
    skepticism: 45,
    humor: 70,
    emoji: '🦸',
    tags: ['estatus', 'limpieza', 'identidad', 'drama', 'imagen'],
  }),
  C({
    id: 'oracle-spam',
    name: 'El Oráculo',
    description: 'Un oráculo inundado de notificaciones push del destino.',
    personality: 'Profundo, irritado y adicto a predecir tonterías.',
    need: 'Quiere filtrar el futuro para quedarse con lo importante.',
    secretConcern: 'Predijo un spoil de serie y se arrepiente.',
    patience: 55,
    skepticism: 60,
    humor: 65,
    emoji: '🔮',
    tags: ['futuro', 'filtro', 'información', 'caos', 'magia'],
  }),
  C({
    id: 'baby-ceo',
    name: 'El Bebé CEO',
    description: 'Un bebé genio que dirige una startup de sonajeros.',
    personality: 'Tiránico, brillante y sin paciencia adulta.',
    need: 'Quiere escalar la empresa antes de la siesta.',
    secretConcern: 'Depende de un chupete estratégico.',
    patience: 10,
    skepticism: 70,
    humor: 85,
    emoji: '👶',
    tags: ['poder', 'urgencia', 'absurdo', 'negocio', 'infantil'],
  }),
  C({
    id: 'muse-blocked',
    name: 'La Musa Bloqueada',
    description: 'Una musa con bloqueo creativo que odia los clichés.',
    personality: 'Exigente, poética y cruelmente honesta.',
    need: 'Quiere inspiración fresca YA.',
    secretConcern: 'Está reciclando ideas de 2012.',
    patience: 35,
    skepticism: 80,
    humor: 50,
    emoji: '🎨',
    tags: ['creatividad', 'arte', 'inspiración', 'crítica', 'novedad'],
  }),
  C({
    id: 'zombie-diet',
    name: 'El Zombi Dietista',
    description: 'Un zombi que intenta comer más sano… dentro de lo posible.',
    personality: 'Lento, educado y con hambre existencial.',
    need: 'Quiere alternativas a cerebros que no le den culpa.',
    secretConcern: 'Extraña las ensaladas de cuando estaba vivo.',
    patience: 70,
    skepticism: 40,
    humor: 75,
    emoji: '🧟',
    tags: ['comida', 'hambre', 'salud', 'absurdo', 'culpa'],
  }),
  C({
    id: 'mayor-pigeon',
    name: 'La Alcaldesa',
    description: 'Una alcaldesa en guerra diplomática con las palomas.',
    personality: 'Diplomática, agotada y muy de rueda de prensa.',
    need: 'Quiere una solución que no salga en portada por lo malo.',
    secretConcern: 'Una paloma anidó en su despacho.',
    patience: 40,
    skepticism: 65,
    humor: 45,
    emoji: '🏛️',
    tags: ['ciudad', 'poder', 'caos', 'imagen', 'control'],
  }),
  C({
    id: 'sailor-land',
    name: 'El Marinero',
    description: 'Un marinero con mareo… en tierra firme.',
    personality: 'Brusco, supersticioso y perdidosamente leal.',
    need: 'Quiere estabilizarse sin volver al barco todavía.',
    secretConcern: 'Le marean los ascensores.',
    patience: 45,
    skepticism: 55,
    humor: 40,
    emoji: '⛵',
    tags: ['mar', 'equilibrio', 'viaje', 'superstición', 'casa'],
  }),
  C({
    id: 'magician-fail',
    name: 'La Maga',
    description: 'Una maga a la que siempre se le ve el truco.',
    personality: 'Carismática, frustrada y perfeccionista del asombro.',
    need: 'Quiere un truco que nadie pueda explicar.',
    secretConcern: 'Su conejo la traiciona en directo.',
    patience: 50,
    skepticism: 50,
    humor: 70,
    emoji: '🪄',
    tags: ['magia', 'espectáculo', 'engaño', 'sorpresa', 'orgullo'],
  }),
  C({
    id: 'hiker-lost',
    name: 'El Excursionista',
    description: 'Un excursionista que se pierde incluso con GPS.',
    personality: 'Optimista, despistado y peligrosamente confiado.',
    need: 'Quiere encontrar el camino sin llamar a emergencias otra vez.',
    secretConcern: 'El mapa está del revés desde hace dos horas.',
    patience: 65,
    skepticism: 35,
    humor: 60,
    emoji: '🥾',
    tags: ['mapa', 'viaje', 'pérdida', 'naturaleza', 'orientación'],
  }),
  C({
    id: 'vampire-influencer',
    name: 'La Vampira Influencer',
    description: 'Una vampira que solo puede grabar de noche y pierde alcance.',
    personality: 'Ambiciosa, glamurosa y obsesionada con el algoritmo.',
    need: 'Quiere crecer en redes sin salir al sol.',
    secretConcern: 'Su rival sube stories al mediodía.',
    patience: 40,
    skepticism: 60,
    humor: 55,
    emoji: '🦇',
    tags: ['redes', 'noche', 'sol', 'estatus', 'algoritmo'],
  }),
  C({
    id: 'butler-chaos',
    name: 'El Mayordomo',
    description: 'Un mayordomo cuya mansión se ha vuelto un caos total.',
    personality: 'Impecable, sarcástico y al borde de la dimisión elegante.',
    need: 'Quiere restaurar el orden sin gritar.',
    secretConcern: 'Escondió el buen vino “por seguridad”.',
    patience: 55,
    skepticism: 70,
    humor: 50,
    emoji: '🤵',
    tags: ['orden', 'lujo', 'caos', 'servicio', 'secreto'],
  }),
  C({
    id: 'storm-chaser',
    name: 'La Cazatormentas',
    description: 'Una cazatormentas a la que las nubes le tienen manía.',
    personality: 'Audaz, científica y un poco imprudente.',
    need: 'Quiere datos buenos sin que el cielo la castigue.',
    secretConcern: 'Su furgoneta tiene más parches que ventanas.',
    patience: 45,
    skepticism: 50,
    humor: 55,
    emoji: '⛈️',
    tags: ['tormenta', 'ciencia', 'riesgo', 'datos', 'aventura'],
  }),
];

export const ADULT_CUSTOMERS: readonly Customer[] = [
  C({
    id: 'ex-toxic',
    name: 'El Ex Tóxico',
    description: 'Un ex que quiere “solo hablar” a las 3 a.m.',
    personality: 'Manipulador, dramático y peligrosamente carismático.',
    need: 'Quiere reabrir la herida con estilo.',
    secretConcern: 'Le han dejado en visto y no lo digiere.',
    patience: 30,
    skepticism: 40,
    humor: 50,
    emoji: '💔',
    tags: ['drama', 'noche', 'celos', 'mentira', 'emoción'],
  }),
  C({
    id: 'after-diva',
    name: 'La Diva del After',
    description: 'Una diva que necesita llegar a casa sin que amanezca.',
    personality: 'Exigente, glamurosa y con cero paciencia.',
    need: 'Quiere cerrar la noche en victoria.',
    secretConcern: 'Le da terror el sol de las 7:12.',
    patience: 15,
    skepticism: 55,
    humor: 60,
    emoji: '🥂',
    tags: ['noche', 'fiesta', 'lujo', 'urgencia', 'imagen'],
  }),
  C({
    id: 'hangover-sunday',
    name: 'El Resacoso',
    description: 'Un resacoso con comida familiar en una hora.',
    personality: 'Frágil, paranoico y ridículamente negociador.',
    need: 'Quiere parecer funcional ante su familia.',
    secretConcern: 'Todavía huele a after.',
    patience: 25,
    skepticism: 35,
    humor: 70,
    emoji: '🥴',
    tags: ['dolor', 'familia', 'urgencia', 'disfraz', 'cura'],
  }),
];

export const EVENTS: readonly TwistEvent[] = [
  {
    id: 'bad-news-flaw',
    kind: 'bad_news',
    title: '🚨 MALAS NOTICIAS',
    body: 'El cliente acaba de descubrir que tu producto tiene una pega importante. Continúa.',
    reactionSeconds: 20,
    minDifficulty: 'easy',
  },
  {
    id: 'plot-similar',
    kind: 'plot_twist',
    title: '🔥 GIRO DE GUION',
    body: 'El cliente te informa de que ya tiene un producto parecido. Convéncele de que el tuyo es mejor.',
    reactionSeconds: 20,
    minDifficulty: 'easy',
  },
  {
    id: 'price-too-high',
    kind: 'price_shock',
    title: '💰 PRECIO',
    body: 'El cliente considera que tu producto es demasiado caro. Defiende el precio.',
    reactionSeconds: 15,
    minDifficulty: 'easy',
  },
  {
    id: 'angry-scam',
    kind: 'angry_customer',
    title: '😡 CLIENTE ENFADADO',
    body: 'El cliente cree que estás intentando engañarle. Tienes 20 segundos para recuperar su confianza.',
    reactionSeconds: 20,
    minDifficulty: 'normal',
  },
  {
    id: 'competitor-call',
    kind: 'competitor',
    title: '📞 LLAMADA DEL RIVAL',
    body: 'En mitad de la charla le llama un competidor con una oferta. Quédate con él.',
    reactionSeconds: 20,
    minDifficulty: 'normal',
  },
  {
    id: 'time-bus',
    kind: 'time_pressure',
    title: '🚌 SE LE VA EL AUTOBÚS',
    body: 'El cliente se levanta: se le va el transporte. Cierra la venta YA.',
    reactionSeconds: 15,
    minDifficulty: 'easy',
  },
  {
    id: 'witness-friend',
    kind: 'witness',
    title: '👀 TESTIGO',
    body: 'Aparece un amigo del cliente que se ríe de tu producto. Gánate a los dos.',
    reactionSeconds: 20,
    minDifficulty: 'normal',
  },
  {
    id: 'demo-bug',
    kind: 'bug',
    title: '🐛 FALLO EN DIRECTO',
    body: 'Durante la demo el producto “falla”. Improvisa una explicación brillante.',
    reactionSeconds: 20,
    minDifficulty: 'normal',
  },
  {
    id: 'goes-viral',
    kind: 'viral',
    title: '📣 SE HACE VIRAL',
    body: 'Alguien está grabando. Todo lo que digas puede volverse clip. Úsalo a tu favor.',
    reactionSeconds: 15,
    minDifficulty: 'normal',
  },
  {
    id: 'boss-watching',
    kind: 'boss',
    title: '👔 JEFE MIRANDO',
    body: 'El jefe del cliente está escuchando. Habla como si cerraras un contrato gordo.',
    reactionSeconds: 20,
    minDifficulty: 'hard',
  },
  {
    id: 'sudden-allergy',
    kind: 'allergy',
    title: '🤧 ALERGIA REPENTINA',
    body: 'El cliente dice que es alérgico a una de tus palabras. Reencuadra el producto.',
    reactionSeconds: 20,
    minDifficulty: 'normal',
  },
  {
    id: 'shipping-delay',
    kind: 'shipping',
    title: '📦 ENVÍO',
    body: 'Descubre que tarda tres meses en llegar. Justifica la espera.',
    reactionSeconds: 15,
    minDifficulty: 'easy',
  },
  {
    id: 'no-warranty',
    kind: 'warranty',
    title: '🧾 SIN GARANTÍA',
    body: 'No hay garantía. Convéncele de que aun así merece la pena.',
    reactionSeconds: 15,
    minDifficulty: 'normal',
  },
  {
    id: 'moral-doubt',
    kind: 'moral',
    title: '⚖️ DILEMA MORAL',
    body: 'El cliente pregunta si es ético comprarlo. Responde en personaje.',
    reactionSeconds: 20,
    minDifficulty: 'hard',
  },
  {
    id: 'memory-gap',
    kind: 'memory',
    title: '🧠 AMNESIA SELECTIVA',
    body: 'El cliente dice que no recuerda nada de tu pitch. Resúmelo en una frase letal.',
    reactionSeconds: 15,
    minDifficulty: 'easy',
  },
  {
    id: 'language-shift',
    kind: 'language',
    title: '🗣️ CAMBIO DE IDIOMA',
    body: 'El cliente exige que se lo expliques “como si tuviera cinco años”.',
    reactionSeconds: 15,
    minDifficulty: 'easy',
  },
  {
    id: 'power-out',
    kind: 'power',
    title: '💡 SE VA LA LUZ',
    body: 'Se va la luz. Termina la venta en la oscuridad (sin apoyarte en pantallas).',
    reactionSeconds: 15,
    minDifficulty: 'normal',
  },
  {
    id: 'sudden-rain',
    kind: 'rain',
    title: '🌧️ LLUVIA ÉPICA',
    body: 'Empieza a llover sobre la negociación. Usa el momento.',
    reactionSeconds: 15,
    minDifficulty: 'easy',
  },
  {
    id: 'mirror-test',
    kind: 'mirror',
    title: '🪞 PRUEBA DEL ESPEJO',
    body: 'El cliente te pide que te vendas el producto a ti primero.',
    reactionSeconds: 20,
    minDifficulty: 'hard',
  },
  {
    id: 'hungry-now',
    kind: 'hungry',
    title: '🍕 HAMBRE SUPREMA',
    body: 'El cliente solo puede pensar en comida. Conecta tu producto con eso.',
    reactionSeconds: 15,
    minDifficulty: 'easy',
  },
  {
    id: 'lost-wallet',
    kind: 'lost_wallet',
    title: '🪙 CARTERA PERDIDA',
    body: 'Dice que ha perdido la cartera. Vende igual (crédito, trueque, lo que sea).',
    reactionSeconds: 20,
    minDifficulty: 'normal',
  },
  {
    id: 'influencer-live',
    kind: 'influencer',
    title: '📸 LIVE IMPROVISADO',
    body: 'Quiere hacer un live contigo. Da el discurso para audiencia.',
    reactionSeconds: 20,
    minDifficulty: 'normal',
  },
  {
    id: 'science-peer',
    kind: 'science',
    title: '🔬 REVISIÓN POR PARES',
    body: 'Aparece un “experto” que pide pruebas. Improvisa evidencia absurda creíble.',
    reactionSeconds: 20,
    minDifficulty: 'hard',
  },
  {
    id: 'ancient-curse',
    kind: 'curse',
    title: '☠️ MALDICIÓN',
    body: 'El cliente sospecha que el producto está maldito. Deshaz el maleficio verbalmente.',
    reactionSeconds: 20,
    minDifficulty: 'hard',
  },
  {
    id: 'gift-mode',
    kind: 'gift',
    title: '🎁 MODO REGALO',
    body: 'Resulta que lo compra para otra persona. Reorienta el pitch al destinatario.',
    reactionSeconds: 15,
    minDifficulty: 'easy',
  },
  {
    id: 'countdown-10',
    kind: 'countdown',
    title: '⏱️ CUENTA ATRÁS',
    body: 'El cliente cuenta desde 10. Cierra antes de que llegue a cero.',
    reactionSeconds: 10,
    minDifficulty: 'hard',
  },
  {
    id: 'sibling-veto',
    kind: 'sibling',
    title: '👨‍👩‍👧 VETO FAMILIAR',
    body: 'Un familiar odia tu idea. Convence al cliente de plantarle cara.',
    reactionSeconds: 20,
    minDifficulty: 'normal',
  },
  {
    id: 'one-star',
    kind: 'review',
    title: '⭐ RESEÑA 1 ESTRELLA',
    body: 'Alguien dejó una reseña horrible inventada. Contrarresta el daño.',
    reactionSeconds: 15,
    minDifficulty: 'normal',
  },
  {
    id: 'upsell-trap',
    kind: 'upgrade',
    title: '🆙 UPSSELL',
    body: 'El cliente pide la versión “premium” que no existe. Inventa el upgrade.',
    reactionSeconds: 20,
    minDifficulty: 'hard',
  },
  {
    id: 'awkward-silence',
    kind: 'silence',
    title: '😶 SILENCIO INCÓMODO',
    body: 'El cliente se queda en silencio mirándote. Rompe el hielo y cierra.',
    reactionSeconds: 15,
    minDifficulty: 'normal',
  },
];

const DIFF_RANK: Record<Difficulty, number> = { easy: 0, normal: 1, hard: 2 };

export function wordPool(adultMode: boolean): WordCard[] {
  return adultMode ? [...WORDS, ...ADULT_WORDS] : [...WORDS];
}

export function customerPool(adultMode: boolean): Customer[] {
  return adultMode ? [...CUSTOMERS, ...ADULT_CUSTOMERS] : [...CUSTOMERS];
}

export function eventsForDifficulty(difficulty: Difficulty): TwistEvent[] {
  const rank = DIFF_RANK[difficulty];
  return EVENTS.filter((e) => DIFF_RANK[e.minDifficulty] <= rank);
}

export function objectionTypesForDifficulty(difficulty: Difficulty): ObjectionType[] {
  const rank = DIFF_RANK[difficulty];
  return OBJECTION_TYPES.filter((o) => DIFF_RANK[o.minDifficulty] <= rank);
}
