/** Cartas de palabra y clientes para Snake Oil (castellano). */

export const WORD_CARDS: readonly string[] = [
  'Aceite',
  'Agua',
  'Almohada',
  'Antena',
  'Arena',
  'Bala',
  'Banana',
  'Barba',
  'Batería',
  'Bici',
  'Bolsillo',
  'Bomba',
  'Botella',
  'Brújula',
  'Burbuja',
  'Cable',
  'Café',
  'Caja',
  'Calcetín',
  'Cámara',
  'Cañón',
  'Capa',
  'Caramelo',
  'Casco',
  'Cebo',
  'Cepillo',
  'Cerebro',
  'Chicle',
  'Chimenea',
  'Chocolate',
  'Cinturón',
  'Clavo',
  'Cohete',
  'Colchón',
  'Cometa',
  'Control',
  'Cuerda',
  'Cuchara',
  'Diente',
  'Dinero',
  'Disfraz',
  'Drone',
  'Escudo',
  'Espejo',
  'Espuma',
  'Faro',
  'Filtro',
  'Fuego',
  'Gafas',
  'Gel',
  'Globo',
  'Goma',
  'Gorila',
  'Guante',
  'Hielo',
  'Hilo',
  'Hormiga',
  'Humano',
  'Imán',
  'Inodoro',
  'Jabón',
  'Jugo',
  'Kayak',
  'Láser',
  'Leche',
  'Linterna',
  'Lobo',
  'Lupa',
  'Máscara',
  'Mermelada',
  'Micro',
  'Mochila',
  'Motor',
  'Muelle',
  'Nube',
  'Ojo',
  'Olla',
  'Oreja',
  'Pala',
  'Pan',
  'Pantalón',
  'Papel',
  'Paraguas',
  'Pasta',
  'Perfume',
  'Pez',
  'Piano',
  'Piedra',
  'Píldora',
  'Piña',
  'Pistola',
  'Plátano',
  'Pluma',
  'Polvo',
  'Puerta',
  'Queso',
  'Radar',
  'Radio',
  'Rayo',
  'Reloj',
  'Robot',
  'Rueda',
  'Salsa',
  'Sandalia',
  'Semilla',
  'Silla',
  'Sirena',
  'Sombrero',
  'Sopa',
  'Sombra',
  'Taladro',
  'Tambor',
  'Taza',
  'Teléfono',
  'Tienda',
  'Tijeras',
  'Tornillo',
  'Tortuga',
  'Trampa',
  'Tren',
  'Tubería',
  'Vacuna',
  'Vela',
  'Veneno',
  'Ventana',
  'Virus',
  'Vuelo',
  'Whisky',
  'Yoga',
  'Zapato',
  'Zumo',
  'Amor',
  'Miedo',
  'Sueño',
  'Mentira',
  'Verdad',
  'Suerte',
  'Caos',
  'Silencio',
  'Grito',
  'Beso',
  'Drama',
  'Magia',
  'Poder',
  'Tiempo',
  'Espacio',
  'Noche',
  'Día',
  'Fiesta',
  'Trabajo',
  'Vacaciones',
  'Futuro',
  'Pasado',
  'Secreto',
  'Chisme',
  'Desastre',
  'Milagro',
  'Envidia',
  'Orgullo',
  'Pereza',
  'Hambre',
  'Sed',
  'Risa',
  'Llanto',
  'Baile',
  'Canto',
  'Olor',
  'Sabor',
  'Toque',
  'Luz',
  'Oscuridad',
  'Velocidad',
  'Fuerza',
  'Belleza',
  'Fealdad',
  'Ruido',
  'Eco',
  'Niebla',
  'Tormenta',
  'Arcoíris',
  'Volcán',
  'Isla',
  'Desierto',
  'Jungla',
  'Ciudad',
  'Pueblo',
  'Castillo',
  'Cueva',
  'Puente',
  'Camino',
  'Laberinto',
  'Tesoro',
  'Basura',
  'Oro',
  'Plata',
  'Diamante',
  'Plástico',
  'Metal',
  'Madera',
  'Cristal',
  'Humedad',
  'Calor',
  'Frío',
  'Electricidad',
  'Gasolina',
  'Internet',
  'Wifi',
  'Cargador',
  'Selfie',
  'Meme',
  'Podcast',
  'Streaming',
  'Algoritmo',
  'Hashtag',
];

export const ADULT_WORD_CARDS: readonly string[] = [
  'Ligoteo',
  'Resaca',
  'After',
  'Tanga',
  'Tacones',
  'Champán',
  'Whisky',
  'Porro',
  'Tinder',
  'Ex',
  'Celos',
  'Chantaje',
  'Confesión',
  'Tentación',
  'Pecado',
  'Látigo',
  'Esposas',
  'Masaje',
  'Aceite',
  'Oscuridad',
  'Hotel',
  'Taxi',
  'Medianoche',
  'Secreto',
  'Mentira',
  'Drama',
  'Escándalo',
  'Selfie',
  'Stories',
  'Borracho',
  'Beso',
  'Abrazo',
  'Cama',
  'Sofá',
  'Ducha',
  'Juego',
  'Reto',
  'Castigo',
  'Premio',
  'Deseo',
];

export const CUSTOMERS: readonly string[] = [
  'Un pirata',
  'Una abuela',
  'Un astronauta',
  'Un chef estrella',
  'Un detective',
  'Una influencer',
  'Un fontanero',
  'Un mago',
  'Una profesora',
  'Un futbolista',
  'Una espía',
  'Un vampiro',
  'Una sirena',
  'Un cowboy',
  'Una reina',
  'Un robot',
  'Un bebé',
  'Un abuelo cascarrabias',
  'Una youtuber',
  'Un médico de urgencias',
  'Un DJ',
  'Una artista callejera',
  'Un monje',
  'Una superheroína',
  'Un granjero',
  'Una periodista',
  'Un extraterrestre',
  'La última persona en la Tierra',
  'Un político en campaña',
  'Una novia el día de la boda',
  'Un niño de 8 años',
  'Un millonario aburrido',
  'Una científica loca',
  'Un bombero',
  'Una cantante de ópera',
  'Un taxista nocturno',
  'Una coach de vida',
  'Un hacker',
  'Una bruja moderna',
  'Un instructor de yoga',
  'Una actriz de telenovela',
  'Un marinero',
  'Una juez severa',
  'Un payaso de circo',
  'Una arqueóloga',
  'Un barista hipster',
  'Una influencer de mascotas',
  'Un rey medieval',
  'Una sobreviviente de reality',
  'Un fantasma amable',
];

export const ADULT_CUSTOMERS: readonly string[] = [
  'Un ex tóxico',
  'Una soltera empedernida',
  'Un ligón de discoteca',
  'Una diva del after',
  'Un casado aburrido',
  'Una coach de seducción',
  'Un influencer de ligues',
  'Una persona en crisis de los 40',
  'Un resacoso de domingo',
  'Una amiga del alma cotilla',
];

/** Quita duplicados manteniendo orden. */
export function uniqueWords(words: readonly string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const w of words) {
    const key = w.trim().toLocaleLowerCase('es');
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push(w.trim());
  }
  return out;
}

export function buildWordDeck(adultMode: boolean): string[] {
  const base = uniqueWords(WORD_CARDS);
  if (!adultMode) return base;
  return uniqueWords([...base, ...ADULT_WORD_CARDS]);
}

export function buildCustomerDeck(adultMode: boolean): string[] {
  const base = uniqueWords(CUSTOMERS);
  if (!adultMode) return base;
  return uniqueWords([...base, ...ADULT_CUSTOMERS]);
}
