/** Packs listos para Papelitos por categoría. */

export interface PaperCategory {
  id: string;
  name: string;
  adult?: boolean;
  slips: readonly string[];
}

export const PAPER_CATEGORIES: readonly PaperCategory[] = [
  {
    id: 'famosos',
    name: 'Famosos',
    slips: [
      'Bad Bunny',
      'Rosalía',
      'Messi',
      'Ronaldo',
      'Shakira',
      'Beyoncé',
      'Taylor Swift',
      'Pedro Sánchez',
      'Ibai',
      'AuronPlay',
      'Penélope Cruz',
      'Javier Bardem',
      'The Rock',
      'Zendaya',
      'Harry Styles',
      'Adele',
      'Elon Musk',
      'Oprah',
      'Quevedo',
      'Aitana',
      'Nadal',
      'Piqué',
      'Cristina Pedroche',
      'Pablo Motos',
      'Belén Esteban',
      'Dua Lipa',
      'Billie Eilish',
      'Tom Cruise',
      'Leonardo DiCaprio',
      'Margot Robbie',
    ],
  },
  {
    id: 'cine',
    name: 'Cine y series',
    slips: [
      'Titanic',
      'El Señor de los Anillos',
      'Harry Potter',
      'Star Wars',
      'Friends',
      'La Casa de Papel',
      'Stranger Things',
      'Juego de Tronos',
      'Breaking Bad',
      'The Office',
      'Matrix',
      'Avatar',
      'Frozen',
      'Shrek',
      'Toy Story',
      'El Padrino',
      'Pesadilla en Elm Street',
      'Coco',
      'Up',
      'Los Simpson',
      'Dragon Ball',
      'Naruto',
      'One Piece',
      'Merlí',
      'Élite',
      'Vis a vis',
      'Aquí no hay quien viva',
      'La que se avecina',
      'Pokémon',
      'Spider-Man',
    ],
  },
  {
    id: 'canciones',
    name: 'Canciones',
    slips: [
      'Despacito',
      'Macarena',
      'Aserejé',
      'Livin la Vida Loca',
      'Bohemian Rhapsody',
      'Shape of You',
      'Thriller',
      'Billie Jean',
      'Yesterday',
      'Imagine',
      'La Flaca',
      'Resistiré',
      'Bailando',
      'Waka Waka',
      'Havana',
      'Blinding Lights',
      'Levitating',
      'Gasolina',
      'Tusa',
      'Provenza',
      'Saoko',
      'Tití me preguntó',
      'La Bachata',
      'Beso',
      'Columbia',
      'Pepas',
      'Dákiti',
      'Suerte',
      'Corazón partío',
      'La gata bajo la lluvia',
    ],
  },
  {
    id: 'lugares',
    name: 'Lugares',
    slips: [
      'París',
      'Nueva York',
      'Tokio',
      'Barcelona',
      'Madrid',
      'Ibiza',
      'Machu Picchu',
      'Gran Cañón',
      'Sagrada Familia',
      'Torre Eiffel',
      'Coliseo',
      'Pirámides de Egipto',
      'Disneyland',
      'Times Square',
      'Playa',
      'Montaña',
      'Desierto',
      'Jungla',
      'Antártida',
      'Volcán',
      'Casino',
      'Hospital',
      'Colegio',
      'Oficina',
      'Gimnasio',
      'Supermercado',
      'Aeropuerto',
      'Metro',
      'Zoológico',
      'Biblioteca',
    ],
  },
  {
    id: 'comida',
    name: 'Comida',
    slips: [
      'Paella',
      'Tortilla de patatas',
      'Pizza',
      'Sushi',
      'Hamburguesa',
      'Tacos',
      'Croissant',
      'Churros',
      'Gazpacho',
      'Fabada',
      'Pulpo a la gallega',
      'Jamón ibérico',
      'Chocolate',
      'Helado',
      'Café',
      'Cerveza',
      'Sangría',
      'Aguacate',
      'Plátano',
      'Queso',
      'Pasta',
      'Ramen',
      'Kebab',
      'Patatas fritas',
      'Nachos',
      'Brownies',
      'Tarta de queso',
      'Huevo frito',
      'Bocadillo de calamares',
      'Pincho de tortilla',
    ],
  },
  {
    id: 'objetos',
    name: 'Objetos',
    slips: [
      'Paraguas',
      'Móvil',
      'Auriculares',
      'Llaves',
      'Gafas',
      'Reloj',
      'Mochila',
      'Cepillo de dientes',
      'Toalla',
      'Almohada',
      'Sartén',
      'Tijeras',
      'Lápiz',
      'Cuaderno',
      'Cargador',
      'Mando de la tele',
      'Lámpara',
      'Silla',
      'Espejo',
      'Candado',
      'Bicicleta',
      'Patinete',
      'Maleta',
      'Pasaporte',
      'Monedero',
      'Anillo',
      'Sombrero',
      'Bufanda',
      'Zapatillas',
      'Calcetines',
    ],
  },
  {
    id: 'adult',
    name: 'Adultos +18',
    adult: true,
    slips: [
      'Tinder',
      'Resaca',
      'After',
      'Liguero',
      'Preservativo',
      'Masaje con final feliz',
      'Ligoteo',
      'Amigos con derecho',
      'Nudes',
      'Sexting',
      'Fiesta de disfraces subidos de tono',
      'Juguete de adulto',
      'Striptease',
      'Beso robado',
      'Cita a ciegas',
      'Ex tóxico',
      'Celos',
      'Ligoteo en el metro',
      'Fin de semana perdido',
      'Chupito de tequila',
      'Bailar pegados',
      'Habitación de hotel',
      'WhatsApp a las 3 am',
      'Secretos de pareja',
      'Juego de verdad o reto',
      'Canción de ligoteo',
      'Salida de emergencias del ligue',
      'Cita que sale mal',
      'Invitación a casa',
      'Mañana después de la fiesta',
    ],
  },
];

export function categoriesForMode(adultMode: boolean): PaperCategory[] {
  return PAPER_CATEGORIES.filter((c) => (adultMode ? true : !c.adult));
}
