import type { WordPair } from './words';

/**
 * Pack +18 para Mr White / Heads Up / Just One.
 * Solo se usa si el jugador activa «Versión adultos».
 * Farsante: mismo tono, palabra distinta (no un sinónimo casi idéntico).
 * Pista Mr White: vibe cercana, sin delatar el taco.
 */
export const ADULT_WORD_PAIRS: readonly WordPair[] = [
  ['Coño', 'Mierda', 'Bronca de bar'],
  ['Joder', 'Hostia', 'Tropiezo inesperado'],
  ['Mierda', 'Joder', 'Día chungo'],
  ['Cabrón', 'Gilipollas', 'Discusión absurda'],
  ['Puta', 'Zorra', 'Insulto de pelea'],
  ['Gilipollas', 'Imbécil', 'Bronca entre colegas'],
  ['Hostia', 'Joder', 'Susto fuerte'],
  ['Pollas', 'Huevos', 'Chiste de barra'],
  ['Cojones', 'Huevos', 'Valor temerario'],
  ['Tetas', 'Culo', 'Vestido ajustado'],
  ['Culo', 'Tetas', 'Vaqueros rotos'],
  ['Follar', 'Ligar', 'Noche larga'],
  ['Correrse', 'Acabar', 'Respiración agitada'],
  ['Mamada', 'Sexo oral', 'Habitación a oscuras'],
  ['Ligar', 'Follar', 'Bar de noche'],
  ['Resaca', 'Migraña', 'Mañana después'],
  ['Porno', 'Lencería', 'Pestaña de incógnito'],
  ['Baile erótico', 'Striptease', 'Local con luces rojas'],
  ['Orgasmo', 'Clímax', 'Sábanas revueltas'],
  ['Preservativo', 'Pastilla', 'Farmacia de guardia'],
  ['Pastilla azul', 'Viagra', 'Bromas de farmacia'],
  ['Sexo oral', 'Mamada', 'Confidencia entre amigos'],
  ['Sexo anal', 'Sado', 'Límite atrevido'],
  ['Tanga', 'Hilo', 'Cajón de ropa'],
  ['Sujetador', 'Tanga', 'Probador de tienda'],
  ['Lencería', 'Picardías', 'Regalo envuelto'],
  ['Consolador', 'Vibrador', 'Cajón con llave'],
  ['Vibrador', 'Consolador', 'Pedido discreto'],
  ['Sado', 'Fetiche', 'Acuerdo en pareja'],
  ['Fetiche', 'Sado', 'Secreto compartido'],
  ['Intercambio de parejas', 'Infidelidad', 'Fiesta privada'],
  ['Infidelidad', 'Cornudo', 'Mensaje borrado'],
  ['Cornudo', 'Infidelidad', 'Rumores de pareja'],
  ['Amigovio', 'Follamigo', 'Relación'],
  ['Ligoteo', 'Coqueteo', 'Bar'],
  ['Borracho', 'Pedo', 'Alcohol'],
  ['Pedo', 'Coño', 'Gases'],
  ['Eructo', 'Regüeldo', 'Gases'],
  ['Vomitar', 'Devolver', 'Resaca'],
  ['Meada', 'Orina', 'Baño'],
  ['Cagar', 'Defecar', 'Baño'],
  ['Peo', 'Flatulencia', 'Gases'],
  ['Chorra', 'Polla', 'Conversación en voz baja'],
  ['Chocho', 'Vagina', 'Puerta con llave'],
  ['Pechochos', 'Tetas', 'Respiro entrecortado'],
  ['Nalgas', 'Culo', 'Puerta con llave'],
  ['Beso negro', 'Coño', 'Sexo oral'],
  ['Triolismo', 'Coño', 'Conversación en voz baja'],
  ['Sexo grupal', 'Coño', 'Respiro entrecortado'],
  ['Orgía', 'Fiesta sexual', 'Rincón del bar'],
  ['Mirón', 'Coño', 'Conversación en voz baja'],
  ['Exhibicionista', 'Mirón al revés', 'Secreto compartido'],
  ['Sexteo', 'Desnudos', 'Móvil'],
  ['Desnudos', 'Fotos calientes', 'Móvil'],
  ['Plataforma de fans', 'Contenido +18', 'Secreto compartido'],
  ['App de ligue', 'Ligues', 'App con fotos'],
  ['Dejar en visto', 'Desaparición', 'Ligue'],
  ['Zona de amigos', 'Coño', 'Ligue'],
  ['Zorra', 'Puta', 'Pelea de borrachos'],
  ['Hijo de puta', 'Insulto fuerte', 'Pelea de borrachos'],
  ['Capullo', 'Gilipollas', 'Pelea de borrachos'],
  ['Imbécil', 'Idiota', 'Discusión absurda'],
  ['Lameculos', 'Pelota', 'Noche larga'],
  ['Mamón', 'Chupóptero', 'Rincón del bar'],
  ['Tontolaba', 'Idiota', 'Rincón del bar'],
  ['Pajero', 'Vicioso', 'Confidencia entre amigos'],
  ['Calentorro', 'Fogonazo', 'Confidencia entre amigos'],
  ['Empollón', 'Calentón', 'Noche de verano'],
  ['Corrida', 'Eyaculación', 'Noche de verano'],
  ['Lubricante', 'Gel', 'Noche de verano'],
  ['Postura del perrito', 'A cuatro', 'Noche en el bar tensa'],
  ['Misionero', 'Clásico', 'Noche en el bar loca'],
  ['A caballo', 'A horcajadas', 'Noche en el bar íntima'],
  ['Rapidito', 'Coño', 'Noche en el bar discreta'],
  ['Rapidito en el baño', 'Coño', 'Noche en el bar improvisada'],
  ['Fiesta de madrugada', 'Después de fiesta', 'Copas encima de la mesa'],
  ['Límite', 'Palabra de seguridad', 'Sadomaso'],
  ['Azotes', 'Nalgadas', 'Sadomaso'],
  ['Esposas', 'Ataduras', 'Sadomaso'],
  ['Antifaz', 'Máscara', 'Juego de roles'],
  ['Látigo', 'Fusta', 'Noche en el bar inesperada'],
  ['Dominadora', 'Coño', 'Juego de roles'],
  ['Sumiso', 'Esclavo', 'Límite negociado'],
  ['Cornudo consentido', 'Coño', 'Mirada prolongada'],
  ['Esposa libre', 'Coño', 'Noche en el bar compartida'],
  ['Penetrar con arnés', 'Coño', 'Noche larga'],
  ['Arnés', 'Coño', 'Noche en el bar incómoda'],
  ['Agujero del placer', 'Coño', 'Noche en el bar divertida'],
  ['Sexo en el coche', 'Coño', 'Exterior'],
  ['Sexo en público', 'Coño', 'Riesgo'],
  ['Sexo en el avión', 'Coño', 'Riesgo'],
  ['Semen', 'Leche', 'Fluido'],
  ['Flujo', 'Lubricación', 'Noche en el bar privada'],
  ['Clítoris', 'Punto G', 'Respiro entrecortado'],
  ['Punto G', 'Placer', 'Noche en el bar rápida'],
  ['Próstata', 'Punto P', 'Noche en el bar larga'],
  ['Testículos', 'Huevos', 'Habitación a oscuras'],
  ['Escroto', 'Saco', 'Noche en el bar borracha'],
  ['Prepucio', 'Piel', 'Noche en el bar romántica'],
  ['Labios', 'Vulva', 'Sabanas revueltas'],
  ['Pecho', 'Teta', 'Ducha caliente'],
  ['Pezón', 'Pechuga', 'Puerta con llave'],
  ['Ombligo', 'Piercing', 'Ducha caliente'],
  ['Ingle', 'Zona baja', 'Baño privado'],
  ['Entrepiemas', 'Muslos', 'Noche en el bar picante'],
  ['Kama sutra', 'Posturas', 'Libro'],
  ['Cincuenta sombras', 'Romance erótico', 'Libro'],
  ['Revista erótica', 'Coño', 'Medios'],
  ['Burdel', 'Prostíbulo', 'Local'],
  ['Puticlub', 'Coño', 'Local'],
  ['Sauna gay', 'Baños', 'Local'],
  ['Cuarto oscuro', 'Coño', 'Noche en el bar absurda'],
  ['Juguete a distancia', 'App de juguete', 'Tecnología'],
  ['Modelo de cámara', 'Emisor en directo +18', 'Noche en el bar memorable'],
  ['Patrocinador', 'Coño', 'Relación'],
  ['Mantenida', 'Coño', 'Relación'],
  ['Acompañante de pago', 'Coño', 'Trabajo'],
  ['Gigoló', 'Acompañante', 'Trabajo'],
  ['Prostituta', 'Trabajador sexual', 'Trabajo'],
  ['Putero', 'Cliente', 'Noche en el bar vergonzosa'],
  ['Chulo', 'Proxeneta', 'Calle'],
  ['Folladero', 'Garito', 'Noche en el bar entrañable'],
  ['Ligue de una noche', 'Coño', 'Bar de copas'],
  ['Polvo', 'Follada', 'Noche en el bar surrealista'],
  ['Echar un polvo', 'Follar', 'Noche de verano tensa'],
  ['Paja', 'Masturbación', 'Solo'],
  ['Masturbarse', 'Tocarse', 'Solo'],
  ['Sueño húmedo', 'Ensueño', 'Noche de verano loca'],
  ['Calentura', 'Lujuria', 'Noche de verano íntima'],
  ['Morbo', 'Excitación', 'Noche de verano discreta'],
  ['Guarrada', 'Coño', 'Noche de verano improvisada'],
  ['Guarro', 'Cerdo', 'Noche de verano inesperada'],
  ['Cerda', 'Zorra', 'Noche de verano compartida'],
  ['Bisexual', 'Coño', 'Orientación'],
  ['Pansexual', 'Sin etiqueta', 'Orientación'],
  ['Poliamor', 'Varias parejas', 'Mensaje a medianoche'],
  ['Pareja abierta', 'Coño', 'Mensaje a medianoche'],
  ['Cornuda consentida', 'Coño', 'App con fotos'],
  ['Humillación', 'Degradación', 'Noche de verano incómoda'],
  ['Nalgadas', 'Azotes', 'Noche de verano divertida'],
  ['Juego con cera', 'Coño', 'Noche de verano privada'],
  ['Juego con hielo', 'Coño', 'Noche de verano rápida'],
  ['Juego de rol', 'Disfraz', 'Fantasía'],
  ['Juego de enfermera', 'Coño', 'Fantasía'],
  ['Fantasía del jefe', 'Coño', 'Noche de verano larga'],
  ['Fantasía del profe', 'Coño', 'Noche de verano borracha'],
  ['Uniforme sexy', 'Disfraz', 'Noche de verano romántica'],
  ['Medias de red', 'Lencería', 'Noche de verano picante'],
  ['Portaligas', 'Lencería', 'Noche de verano absurda'],
  ['Body abierto', 'Picardías', 'Noche de verano memorable'],
  ['Camisón corto', 'Coño', 'Noche de verano vergonzosa'],
  ['Anillo para el pene', 'Coño', 'Habitación a oscuras'],
  ['Tapón anal', 'Coño', 'Noche de verano entrañable'],
  ['Bolas anales', 'Coño', 'Noche de verano surrealista'],
  ['Masturbador', 'Coño', 'Noche entre amigos tensa'],
  ['Máquina sexual', 'Coño', 'Noche entre amigos loca'],
  ['Vapores', 'Amilo', 'Noche entre amigos íntima'],
  ['Éxtasis', 'Pastilla', 'Noche entre amigos discreta'],
  ['Porro', 'Canuto', 'Noche entre amigos improvisada'],
  ['Pipa de agua', 'Coño', 'Noche entre amigos inesperada'],
  ['Chupito', 'Trago', 'Bar'],
  ['Cubata', 'Combinado', 'Bar'],
  ['Combinado hasta morir', 'Borrachera', 'Noche entre amigos compartida'],
  ['Despedida de soltero', 'Coño', 'Noche entre amigos incómoda'],
  ['Bailarina erótica', 'Striptease', 'Noche entre amigos divertida'],
  ['Baile privado', 'Coño', 'Noche entre amigos privada'],
  ['Baile de barra', 'Coño', 'Noche entre amigos rápida'],
  ['Perreo', 'Coño', 'Noche entre amigos larga'],
  ['Perreo intenso', 'Reggaetón', 'Noche entre amigos borracha'],
  ['Beso con lengua', 'Coño', 'Noche entre amigos romántica'],
  ['Morreo', 'Frenazo', 'Noche entre amigos picante'],
  ['Peto', 'Manoseo', 'Manos'],
  ['Mano inocente', 'Debajo de la ropa', 'Manos'],
  ['Dedos', 'Penetración digital', 'Manos'],
  ['Sesenta y nueve', '69', 'Sexo oral'],
  ['Garganta profunda', 'Coño', 'Sexo oral'],
  ['Acabada en la cara', 'Coño', 'Noche entre amigos absurda'],
  ['Acabada dentro', 'Coño', 'Noche entre amigos memorable'],
  ['Sacar fuera', 'Coño', 'Noche entre amigos vergonzosa'],
  ['Sin condón', 'Coño', 'Riesgo'],
  ['Prueba de embarazo', 'Coño', 'Noche entre amigos entrañable'],
  ['Pastilla del día después', 'Emergencia', 'Noche entre amigos surrealista'],
  ['Infección sexual', 'Enfermedad', 'Noche en voz baja tensa'],
  ['Herpes', 'Llaga', 'Noche en voz baja loca'],
  ['Candidiasis', 'Hongos', 'Noche en voz baja íntima'],
  ['Hemorroides', 'Almorranas', 'Noche en voz baja discreta'],
  ['Estreñimiento', 'Tapón', 'Baño'],
  ['Diarrea', 'Cagalera', 'Noche en voz baja improvisada'],
  ['Estreñido', 'Aprieto', 'Noche en voz baja inesperada'],
  ['Lavativa', 'Enema', 'Noche en voz baja compartida'],
  ['Bidé', 'Lavado', 'Noche en voz baja incómoda'],
  ['Orinal', 'Coño', 'Noche en voz baja divertida'],
  ['Cagada monumental', 'Lío', 'Error'],
  ['La cagaste', 'La liastes', 'Error'],
  ['Me la suda', 'Me importa un pepino', 'Desprecio'],
  ['Me importa una mierda', 'Pasotismo', 'Desprecio'],
  ['Que te jodan', 'Noche larga', 'Noche en voz baja privada'],
  ['Vete a la mierda', 'Lárgate', 'Insulto entre colegas'],
  ['Que te den por culo', 'Coño', 'Sábanas revueltas'],
  ['Tocapelotas', 'Pesado', 'Noche en voz baja rápida'],
  ['Rompepelotas', 'Pesado', 'Noche en voz baja larga'],
  ['Huevón', 'Perezoso', 'Noche en voz baja borracha'],
  ['Huevos revueltos', 'Desayuno', 'Doble sentido'],
  ['Chupar rueda', 'Ciclismo', 'Doble sentido'],
  ['Meter un gol', 'Fútbol', 'Doble sentido'],
  ['Entrar por detrás', 'Fútbol', 'Noche en voz baja romántica'],
  ['Paliza', 'Golpiza', 'Bronca'],
  ['Hostia limpia', 'Puñetazo', 'Bronca'],
  ['Galleta', 'Bofetada', 'Bronca'],
  ['Leñazo', 'Golpe', 'Noche en voz baja picante'],
  ['Coñazo', 'Pesadez', 'Noche en voz baja absurda'],
  ['Jodón', 'Pesado', 'Noche en voz baja memorable'],
  ['Mierdoso', 'Asqueroso', 'Noche en voz baja vergonzosa'],
  ['Cabronada', 'Faena', 'Discusión absurda'],
  ['Putada', 'Faena', 'Insulto entre colegas'],
  ['Gilipollez', 'Tontería', 'Noche en voz baja entrañable'],
  ['Hostión', 'Golpe', 'Noche en voz baja surrealista'],
  ['Pollazo', 'Golpe', 'Sábanas revueltas'],
  ['Cojonudo', 'Genial', 'Taco positivo'],
  ['De puta madre', 'Genial', 'Taco positivo'],
  ['La hostia', 'Brutal', 'Taco positivo'],
  ['Flipante', 'Alucinante', 'Noche de fiesta tensa'],
  ['Me cago en todo', 'Cabreo', 'Noche de fiesta loca'],
  ['Me cago en la leche', 'Cabreo', 'Noche de fiesta íntima'],
  ['Me cago en Dios', 'Cabreo', 'Noche de fiesta discreta'],
  ['Leche', 'Semen', 'Noche de fiesta improvisada'],
  ['Crema', 'Semen', 'Noche de fiesta inesperada'],
  ['Nata', 'Semen', 'Noche de fiesta compartida'],
  ['Chorro', 'Eyaculación', 'Noche de fiesta incómoda'],
  ['Chorrito', 'Eyaculación', 'Noche de fiesta divertida'],
  ['Acabar dentro', 'Noche larga', 'Noche de fiesta privada'],
  ['Acabar fuera', 'Sacar fuera', 'Noche de fiesta rápida'],
  ['Con condón', 'Coño', 'Noche de fiesta larga'],
  ['Forro', 'Preservativo', 'Noche de fiesta borracha'],
  ['Goma', 'Condón', 'Noche de fiesta romántica'],
  ['Diafragma', 'Método', 'Noche de fiesta picante'],
  ['Píldora', 'Anticonceptivo', 'Noche de fiesta absurda'],
  ['Marcha atrás', 'Coño', 'Noche de fiesta memorable'],
  ['Calcular días', 'Ritmo', 'Noche de fiesta vergonzosa'],
  ['Pastilla abortiva', 'Farmacia', 'Noche de fiesta entrañable'],
  ['Ecografía', 'Embarazo', 'Noche de fiesta surrealista'],
  ['Triple prueba', 'Infección sexual', 'Noche en casa tensa'],
  ['Serología', 'Análisis', 'Noche en casa loca'],
  ['Vacuna del papiloma', 'Prevención', 'Noche en casa íntima'],
  ['Prevención del VIH', 'Coño', 'Noche en casa discreta'],
  ['Urgencia del VIH', 'Emergencia', 'Noche en casa improvisada'],
  ['Cistitis', 'Infección', 'Noche en casa inesperada'],
  ['Prostatitis', 'Infección', 'Noche en casa compartida'],
  ['Fimosis', 'Prepucio', 'Noche en casa incómoda'],
  ['Frenillo', 'Genital', 'Noche en casa divertida'],
  ['Circuncisión', 'Cirugía', 'Noche en casa privada'],
  ['Vasectomía', 'Cirugía', 'Noche en casa rápida'],
  ['Ligadura', 'Cirugía', 'Noche en casa larga'],
  ['Implante anticonceptivo', 'Brazo', 'Noche en casa borracha'],
  ['Anticonceptivo interno', 'Coño', 'Noche en casa romántica'],
  ['Anillo vaginal', 'Anticonceptivo', 'Noche en casa picante'],
  ['Parche anticonceptivo', 'Hormonas', 'Noche en casa absurda'],
  ['Gel estimulante', 'Lubricante', 'Noche en casa memorable'],
  ['Aceite de masaje', 'Coño', 'Noche en casa vergonzosa'],
  ['Pluma de cosquillas', 'Juego', 'Noche en casa entrañable'],
  ['Venda', 'Antifaz', 'Noche en casa surrealista'],
  ['Mordaza', 'Bola', 'Noche de madrugada tensa'],
  ['Collar de sumisión', 'Coño', 'Juego de roles'],
  ['Correa', 'Paseo', 'Noche de madrugada loca'],
  ['Paleta', 'Coño', 'Noche de madrugada íntima'],
  ['Fusta', 'Látigo corto', 'Cuarto con candado'],
  ['Fusta corta', 'Látigo', 'Cuero y cadenas'],
  ['Nalgada seca', 'Azote', 'Noche de madrugada discreta'],
  ['Marcas', 'Moretones', 'Noche de madrugada improvisada'],
  ['Cuidados posteriores', 'Coño', 'Noche de madrugada inesperada'],
  ['Negociación', 'Límites', 'Noche de madrugada compartida'],
  ['Semáforo', 'Límites', 'Noche de madrugada incómoda'],
  ['Rojo', 'Parar', 'Noche de madrugada divertida'],
  ['Ámbar', 'Despacio', 'Noche de madrugada privada'],
  ['Verde', 'Seguir', 'Noche de madrugada rápida'],
  ['Juego de golpes', 'Coño', 'Noche de madrugada larga'],
  ['Ataduras', 'Coño', 'Noche de madrugada borracha'],
  ['Atadura japonesa', 'Cuerda', 'Noche de madrugada romántica'],
  ['Cuerda japonesa', 'Coño', 'Noche de madrugada picante'],
  ['Suspensión', 'Colgado', 'Noche de madrugada absurda'],
  ['Privación sensorial', 'Coño', 'Noche de madrugada memorable'],
  ['Juego de temperatura', 'Coño', 'Noche de madrugada vergonzosa'],
  ['Juego eléctrico', 'Descargas', 'Noche de madrugada entrañable'],
  ['Juego de mascota', 'Animalito', 'Noche de madrugada surrealista'],
  ['Fetiche de papi', 'Rol', 'Noche en la calle tensa'],
  ['Juego de edad', 'Rol', 'Noche en la calle loca'],
  ['Juego médico', 'Clínica', 'Noche en la calle íntima'],
  ['No consentimiento pactado', 'Coño', 'Noche en la calle discreta'],
  ['Fetiche de elogios', 'Coño', 'Noche en la calle improvisada'],
  ['Degradación', 'Insultos eróticos', 'Noche en la calle inesperada'],
  ['Disponible siempre', 'Coño', 'Noche en la calle compartida'],
  ['Juego en público', 'Coño', 'Noche en la calle incómoda'],
  ['Balcón', 'Exterior', 'Noche en la calle divertida'],
  ['Ascensor', 'Riesgo', 'Noche en la calle privada'],
  ['Probador', 'Tienda', 'Noche en la calle rápida'],
  ['Cine vacío', 'Sala', 'Noche en la calle larga'],
  ['Playa nudista', 'Coño', 'Exterior'],
  ['Camping salvaje', 'Tienda', 'Exterior'],
  ['Jacuzzi privado', 'Agua', 'Noche en la calle borracha'],
  ['Ducha juntos', 'Baño', 'Noche en la calle romántica'],
  ['Baño del bar', 'Rapidito', 'Noche en la calle picante'],
  ['Terraza de fiesta', 'Exterior', 'Después de la discoteca'],
  ['Trastero', 'Rincón', 'Cajas olvidadas'],
  ['Aparcamiento', 'Coche', 'Noche en la calle absurda'],
  ['VTC caliente', 'Vuelta', 'Noche en la calle memorable'],
  ['Taxi de madrugada', 'Vuelta', 'Grupo de amigos'],
  ['Resacón histórico', 'Noche larga', 'Noche en la calle vergonzosa'],
  ['Mareo de alcohol', 'Resaca leve', 'Noche en la calle entrañable'],
  ['Boca de algodón', 'Resaca leve', 'Noche en la calle surrealista'],
  ['Dolor de cabeza', 'Resaca leve', 'Noche del grupo tensa'],
  ['Agua con gas y paracetamol', 'Resaca leve', 'Noche del grupo loca'],
  ['Kebab de madrugada', 'Resaca leve', 'Copas encima de la mesa'],
  ['Pizza a las 4', 'Resaca leve', 'Noche del grupo íntima'],
  ['Tabaco de mentira', 'Porro', 'Noche del grupo discreta'],
  ['Porro mal liado', 'Canuto', 'Noche del grupo improvisada'],
  ['Humazo', 'Humo', 'Noche del grupo inesperada'],
  ['Colocón', 'Colgado', 'Noche del grupo compartida'],
  ['Bajón', 'Caída', 'Noche del grupo incómoda'],
  ['Subidón', 'Éxtasis', 'Noche del grupo divertida'],
  ['Pastilleo', 'Noche larga', 'Noche del grupo privada'],
  ['Raya', 'Coca', 'Noche del grupo rápida'],
  ['Farlopa', 'Coca', 'Noche del grupo larga'],
  ['Chute', 'Inyección', 'Noche del grupo borracha'],
  ['Ketamina', 'Coño', 'Noche del grupo romántica'],
  ['Setas', 'Alucinógenos', 'Noche del grupo picante'],
  ['Ácido', 'Viaje alucinógeno', 'Noche del grupo absurda'],
  ['G de fiesta', 'Droga líquida', 'Grupo de amigos'],
  ['Popper en la disco', 'Vapores', 'Noche del grupo memorable'],
  ['Esnifar', 'Coño', 'Noche del grupo vergonzosa'],
  ['Camello', 'Coño', 'Noche del grupo entrañable'],
  ['Camello del barrio', 'Coño', 'Noche del grupo surrealista'],
  ['Trapicheo', 'Venta', 'Noche en pareja tensa'],
  ['Colocarse', 'Drogarse', 'Noche en pareja loca'],
  ['Ir puesto', 'Colocado', 'Noche en pareja íntima'],
  ['Ir ciego', 'Borracho', 'Noche en pareja discreta'],
  ['Ir petao', 'Borracho', 'Noche en pareja improvisada'],
  ['Ir hasta el culo', 'Borracho', 'Noche en pareja inesperada'],
  ['Blanco total', 'Borracho', 'Noche en pareja compartida'],
  ['Apagón etílico', 'Coño', 'Noche en pareja incómoda'],
  ['No me acuerdo de nada', 'Apagón etílico', 'Noche en pareja divertida'],
  ['Historias vergonzosas', 'Resaca social', 'Noche en pareja privada'],
  ['Beso a desconocido', 'Ligue', 'Noche en pareja rápida'],
  ['Ligue de baño', 'Rapidito', 'Bar de copas'],
  ['Número falso', 'Dejar en visto', 'Ligue'],
  ['Dar migajas', 'Coño', 'Noche en pareja larga'],
  ['Orbitar', 'Coño', 'Noche en pareja borracha'],
  ['Casi pareja', 'Coño', 'Bar de copas'],
  ['Pareja a medias en redes', 'Coño', 'Plan de fin de semana'],
  ['Pareja pública en redes', 'Coño', 'Mensaje a medianoche'],
  ['Tener de reserva', 'Banquillo', 'Noche en pareja romántica'],
  ['Vuelve el ex', 'Coño', 'Noche en pareja picante'],
  ['Colchón afectivo', 'Coño', 'Noche en pareja absurda'],
  ['Otras apps a la vez', 'Coño', 'App con fotos'],
  ['Perfil falso', 'Coño', 'Noche en pareja memorable'],
  ['Bombardeo afectivo', 'Coño', 'Noche en pareja vergonzosa'],
  ['Manipulación afectiva', 'Coño', 'Noche en pareja entrañable'],
  ['Halago hiriente', 'Pique', 'Noche en pareja surrealista'],
  ['Ligón de manual', 'Coño', 'Noche del viaje tensa'],
  ['Primer mensaje', 'Coño', 'App'],
  ['Deslizar a la derecha', 'Me gusta', 'App'],
  ['Deslizar a la izquierda', 'Paso', 'App'],
  ['Súper me gusta', 'Destacado', 'Noche del viaje loca'],
  ['Coincidencia', 'Coño', 'Noche del viaje íntima'],
  ['Quitar coincidencia', 'Borrar', 'Noche del viaje discreta'],
  ['Biografía falsa', 'Perfil', 'Noche del viaje improvisada'],
  ['Foto de hace 10 años', 'Perfil', 'Noche del viaje inesperada'],
  ['Foto con filtro', 'Perfil', 'Noche del viaje compartida'],
  ['Foto en la playa', 'Perfil', 'Noche del viaje incómoda'],
  ['Foto del gimnasio', 'Perfil', 'Noche del viaje divertida'],
  ['Foto con el ex recortado', 'Perfil', 'Noche del viaje privada'],
  ['Quedada para un café', 'Primera cita', 'Noche del viaje rápida'],
  ['Quedada para un vermú', 'Primera cita', 'Noche del viaje larga'],
  ['Quedada en casa', 'Ver una serie y follar', 'Noche del viaje borracha'],
  ['Ver una serie y follar', 'Coño', 'Noche del viaje romántica'],
  ['Ver una serie', 'Excusa', 'Noche del viaje picante'],
  ['Masaje con final feliz', 'Coño', 'Noche del viaje absurda'],
  ['Final feliz', 'Acabar', 'Noche del viaje memorable'],
  ['Masaje prostático', 'Punto P', 'Noche del viaje vergonzosa'],
  ['Estimulación anal', 'Tapón anal', 'Noche del viaje entrañable'],
  ['Sentarse en la cara', 'Coño', 'Noche del viaje surrealista'],
  ['Paja con la mano', 'Coño', 'Noche en la cocina tensa'],
  ['Paja con los pies', 'Coño', 'Noche en la cocina loca'],
  ['Paja con tetas', 'Coño', 'Noche en la cocina íntima'],
  ['Entre muslos', 'Coño', 'Sabanas revueltas'],
  ['Frotarse vestidos', 'Coño', 'Noche en la cocina discreta'],
  ['Frotamiento', 'Noche larga', 'Noche en la cocina improvisada'],
  ['Llevar al límite', 'Coño', 'Noche en la cocina inesperada'],
  ['Orgasmo a medias', 'Coño', 'Noche en la cocina compartida'],
  ['Varios orgasmos', 'Coño', 'Noche en la cocina incómoda'],
  ['Eyaculación femenina', 'Chorrito', 'Noche en la cocina divertida'],
  ['Orgasmo prostático', 'Punto P', 'Noche en la cocina privada'],
  ['Juego con pezones', 'Coño', 'Noche en la cocina rápida'],
  ['Juego con tetas', 'Coño', 'Noche en la cocina larga'],
  ['Hablar guarro', 'Coño', 'Noche en la cocina borracha'],
  ['Sexo telefónico', 'Coño', 'Noche en la cocina romántica'],
  ['Videollamada caliente', 'Coño', 'Noche en la cocina picante'],
  ['Cámara a cámara', 'Coño', 'Noche en la cocina absurda'],
  ['Menú de propinas', 'Coño', 'Noche en la cocina memorable'],
  ['Espectáculo privado', 'Coño', 'Noche en la cocina vergonzosa'],
  ['Foto de polla', 'Coño', 'Móvil'],
  ['Foto íntima', 'Coño', 'Noche en la cocina entrañable'],
  ['Filtración de desnudos', 'Coño', 'Noche en la cocina surrealista'],
  ['Porno de venganza', 'Coño', 'Noche del piso tensa'],
  ['Consentimiento explícito', 'Sí claro', 'Ética'],
  ['Retirar el consentimiento', 'Parar', 'Ética'],
  ['Preguntar si todo va bien', '¿Todo bien?', 'Ética'],
  ['Sobriedad y consentimiento', 'Límites', 'Noche del piso loca'],
  ['No es no', 'Límite', 'Noche del piso íntima'],
  ['Solo sí es sí', 'Consentimiento', 'Noche del piso discreta'],
  ['Acoso callejero', 'Piropo basura', 'Noche del piso improvisada'],
  ['Mano en el culo', 'Agarrón', 'Calle'],
  ['Mirada lasciva', 'Mirón', 'Calle'],
  ['Frotarse en el metro', 'Coño', 'Noche del piso inesperada'],
  ['Debajo de la falda', 'Coño', 'Noche del piso compartida'],
  ['Voyeurismo no consentido', 'Mirón', 'Noche del piso incómoda'],
  ['Exhibición', 'Mostrar genitales', 'Noche del piso divertida'],
  ['Enseñar el culo', 'Mostrar culo', 'Noche del piso privada'],
  ['Correr desnudo', 'Coño', 'Noche del piso rápida'],
  ['Topless playa', 'Pechos al aire', 'Noche del piso larga'],
  ['Desnudo integral', 'Nudismo', 'Playa'],
  ['Bronceado de culo', 'Marcas', 'Playa'],
  ['Crema solar en zonas íntimas', 'Playa', 'Noche del piso borracha'],
  ['Pelo púbico', 'Vello', 'Noche del piso romántica'],
  ['Depilación brasileña', 'Cera', 'Noche del piso picante'],
  ['Depilación total', 'Cera total', 'Noche del piso absurda'],
  ['Franja de vello', 'Coño', 'Noche del piso memorable'],
  ['Monte de Venus', 'Coño', 'Noche del piso vergonzosa'],
  ['Afeitado íntimo', 'Cuchilla', 'Noche del piso entrañable'],
  ['Irritación de cera', 'Rojo', 'Noche del piso surrealista'],
  ['Foliculitis', 'Granos', 'Noche en el after tensa'],
  ['Estrías', 'Marcas', 'Noche en el after loca'],
  ['Celulitis', 'Piel de naranja', 'Noche en el after íntima'],
  ['Barriga cervecera', 'Curro', 'Noche en el after discreta'],
  ['Camino de vello', 'Coño', 'Noche en el after improvisada'],
  ['Vello del pecho', 'Coño', 'Espejo del dormitorio'],
  ['Sisas', 'Axilas', 'Noche en el after inesperada'],
  ['Hedor a sexo', 'Olor', 'Noche en el after compartida'],
  ['Aliento a alcohol y sexo', 'Mañana', 'Resaca'],
  ['Sábana manchada', 'Lavadora', 'Noche en el after incómoda'],
  ['Toalla de emergencia', 'Baño', 'Noche en el after divertida'],
  ['Papel higiénico impropio', 'Baño', 'Noche en el after privada'],
  ['Ducha fría después', 'Bajón', 'Noche en el after rápida'],
  ['Cigarro postcoital', 'Cliché', 'Noche en el after larga'],
  ['La pequeña muerte', 'Orgasmo', 'Noche en el after borracha'],
  ['Mirarse a los ojos', 'Intimidad', 'Noche en el after romántica'],
  ['Risa nerviosa en la cama', 'Torpeza', 'Noche en el after picante'],
  ['Diente contra diente', 'Beso torpe', 'Noche en el after absurda'],
  ['Ortodoncia al besar', 'Beso', 'Noche en el after memorable'],
  ['Babeo excesivo', 'Beso', 'Noche en el after vergonzosa'],
  ['Chupar el cuello', 'Marca en el cuello', 'Noche en el after entrañable'],
  ['Chupetón visible', 'Moratón', 'Noche en el after surrealista'],
  ['Arañazos en la espalda', 'Marcas', 'Noche del trabajo tensa'],
  ['Mordisco en el hombro', 'Marcas', 'Noche del trabajo loca'],
  ['Pelo agarrado', 'Jalón', 'Noche del trabajo íntima'],
  ['Cachete en el culo', 'Nalgada', 'Noche del trabajo discreta'],
  ['Empujón rítmico', 'Follar', 'Noche del trabajo improvisada'],
  ['Cama que cruje', 'Ruido', 'Noche del trabajo inesperada'],
  ['Vecinos escuchando', 'Ruido', 'Noche del trabajo compartida'],
  ['Paredes de papel', 'Ruido', 'Noche del trabajo incómoda'],
  ['Gritos ahogados', 'Almohada', 'Noche del trabajo divertida'],
  ['Morder la almohada', 'Silencio', 'Noche del trabajo privada'],
  ['Lista de canciones sexy', 'Música', 'Noche del trabajo rápida'],
  ['Luz baja', 'Ambiente', 'Noche del trabajo larga'],
  ['Velas que huelen a vainilla', 'Ambiente', 'Noche del trabajo borracha'],
  ['Sábana de satén', 'Cama', 'Noche del trabajo romántica'],
  ['Lencería nueva', 'Ropa', 'Noche del trabajo picante'],
  ['Ropa interior del día a día', 'Coño', 'Noche del trabajo absurda'],
  ['Calzoncillos del abuelo', 'Ropa', 'Noche del trabajo memorable'],
  ['Calcetines puestos', 'Torpeza', 'Noche del trabajo vergonzosa'],
  ['Sujetador imposible', 'Broche', 'Noche del trabajo entrañable'],
  ['Cremallera atascada', 'Ropa', 'Noche del trabajo surrealista'],
  ['Tirante que se rompe', 'Picardías', 'Noche en la playa tensa'],
  ['Tacones en la cama', 'Ropa', 'Noche en la playa loca'],
  ['Camisa a medio abrir', 'Ropa', 'Noche en la playa íntima'],
  ['Vaqueros difíciles', 'Ropa', 'Noche en la playa discreta'],
  ['Cinturón a contrarreloj', 'Ropa', 'Noche en la playa improvisada'],
  ['Condón al revés', 'Torpeza', 'Noche en la playa inesperada'],
  ['Condón caducado', 'Riesgo', 'Noche en la playa compartida'],
  ['Condón que se rompe', 'Susto', 'Noche en la playa incómoda'],
  ['Buscar el condón a oscuras', 'Torpeza', 'Noche en la playa divertida'],
  ['Cartera sin condón', 'Faena', 'Noche en la playa privada'],
  ['Farmacia de guardia', 'Emergencia', 'Noche en la playa rápida'],
  ['Máquina expendedor de condones', 'Baño', 'Noche en la playa larga'],
  ['Lubricante frío', 'Susto', 'Noche en la playa borracha'],
  ['Lubricante con sabor', 'Gel', 'Noche en la playa romántica'],
  ['Lubricante que pica', 'Gel', 'Noche en la playa picante'],
  ['Aceite que rompe el látex', 'Error', 'Noche en la playa absurda'],
  ['Posición imposible', 'Kama sutra', 'Noche en la playa memorable'],
  ['Calambre en la pierna', 'Torpeza', 'Espejo del dormitorio'],
  ['Pierna dormida', 'Torpeza', 'Espejo del dormitorio'],
  ['Se sale', 'Torpeza', 'Noche en la playa vergonzosa'],
  ['No entra', 'Torpeza', 'Noche en la playa entrañable'],
  ['Demasiado seco', 'Lubricante', 'Noche en la playa surrealista'],
  ['Demasiado rápido', 'Llevar al límite', 'Noche del barrio tensa'],
  ['Se te baja', 'Vergüenza', 'Noche del barrio loca'],
  ['Ansiedad de rendimiento', 'Nervios', 'Noche del barrio íntima'],
  ['Fingir el orgasmo', 'Teatro', 'Noche del barrio discreta'],
  ['Preguntar ¿ya?', 'Torpeza', 'Noche del barrio improvisada'],
  ['Mirar el móvil en la cama', 'Faena', 'Noche del barrio inesperada'],
  ['Dormirse después de acabar', 'Clásico', 'Noche del barrio compartida'],
  ['Cucharita', 'Abrazo', 'Noche del barrio incómoda'],
  ['Cucharota', 'Postura lateral', 'Noche del barrio divertida'],
  ['Cucharita pequeña', 'Coño', 'Noche del barrio privada'],
  ['Hablar del ex en la cama', 'Error', 'Noche del barrio rápida'],
  ['Decir el nombre equivocado', 'Horror', 'Noche del barrio larga'],
  ['Reírse de un pedo', 'Torpeza', 'Noche del barrio borracha'],
  ['Pedo en pleno acto', 'Vergüenza', 'Noche del barrio romántica'],
  ['Ruidos intestinales', 'Vergüenza', 'Noche del barrio picante'],
  ['Estómago vacío ruge', 'Vergüenza', 'Noche del barrio absurda'],
  ['Ir al baño a escondidas', 'Pausa', 'Noche del barrio memorable'],
  ['Lavarse los dientes antes', 'Higiene', 'Noche del barrio vergonzosa'],
  ['Ducha previa', 'Higiene', 'Noche del barrio entrañable'],
  ['Aliento a ajo', 'Faena', 'Noche del barrio surrealista'],
  ['Sudor de gimnasio', 'Olor', 'Noche en el coche tensa'],
  ['Colonia excesiva', 'Olor', 'Noche en el coche loca'],
  ['Feromonas de bote', 'Colonia', 'Noche en el coche íntima'],
  ['Ropa interior limpia por si acaso', 'Previsión', 'Noche en el coche discreta'],
  ['Afeitarse por si acaso', 'Previsión', 'Noche en el coche improvisada'],
  ['Sábanas limpias por si acaso', 'Previsión', 'Noche en el coche inesperada'],
  ['Copas de más', 'Alcohol', 'Noche en el coche compartida'],
  ['Valor de alcohol', 'Coraje', 'Noche en el coche incómoda'],
  ['Confesiones borrachas', 'Fiesta', 'Bar con música alta'],
  ['Bailar pegado', 'Perreo', 'Noche en el coche divertida'],
  ['Manos en la cintura', 'Baile', 'Noche en el coche privada'],
  ['Frotar en la pista', 'Perreo', 'Noche en el coche rápida'],
  ['Beso en la pista', 'Ligue', 'Noche en el coche larga'],
  ['Sacar a bailar', 'Ligue', 'Noche en el coche borracha'],
  ['Invitar a chupitos', 'Ligue', 'Noche en el coche romántica'],
  ['Pagar la ronda', 'Ligue', 'Noche en el coche picante'],
  ['Pedir el número', 'Ligue', 'Noche en el coche absurda'],
  ['Red social en vez de número', 'Ligue', 'Noche en el coche memorable'],
  ['Seguir en todas las redes', 'Acecho ligero', 'Noche en el coche vergonzosa'],
  ['Espiar historias', 'Coño', 'Noche en el coche entrañable'],
  ['Ver la ubicación', 'Espiar', 'Noche en el coche surrealista'],
  ['Preguntar a amigos comunes', 'Cotilleo de bar', 'Noche del curro tensa'],
  ['Cotillear el ex', 'Noche larga', 'Noche del curro loca'],
  ['Comparar con el ex', 'Error', 'Noche del curro íntima'],
  ['Revisar el móvil', 'Celos', 'Noche del curro discreta'],
  ['Contraseña compartida', 'Confianza', 'Noche del curro improvisada'],
  ['Celos en la discoteca', 'Bronca', 'Madrugada en la calle'],
  ['Bronca de madrugada', 'Pareja', 'Copas encima de la mesa'],
  ['Sexo de reconciliación', 'Coño', 'Noche del curro inesperada'],
  ['Sexo de despedida', 'Adiós', 'Noche del curro compartida'],
  ['Sexo aburrido de sofá', 'Rutina', 'Noche del curro incómoda'],
  ['Rutina de siempre los viernes', 'Coño', 'Noche del curro divertida'],
  ['Calendario de ovulación', 'Apps', 'Noche del curro privada'],
  ['App de ciclos', 'Regla', 'Mirada prolongada'],
  ['Dolor menstrual', 'Regla', 'Noche del curro rápida'],
  ['Cólico bestial', 'Regla', 'Noche del curro larga'],
  ['Tampones', 'Regla', 'Noche del curro borracha'],
  ['Compresa', 'Regla', 'Noche del curro romántica'],
  ['Copa menstrual', 'Regla', 'Noche del curro picante'],
  ['Mancha en la sábana', 'Regla', 'Noche del curro absurda'],
  ['Sexo con la regla', 'Periodo', 'Noche del curro memorable'],
  ['Toalla roja', 'Regla', 'Noche del curro vergonzosa'],
  ['Antojo absurdo', 'Embarazo', 'Noche del curro entrañable'],
  ['Test de farmacia positivo', 'Susto', 'Noche del curro surrealista'],
  ['Test de farmacia negativo', 'Alivio', 'Noche en el baño tensa'],
  ['Retraso', 'Susto', 'Noche en el baño loca'],
  ['Síntomas raros', 'Susto', 'Noche en el baño íntima'],
  ['Visita al ginecólogo', 'Consulta', 'Noche en el baño discreta'],
  ['Visita al urólogo', 'Consulta', 'Noche en el baño improvisada'],
  ['Exploración íntima', 'Consulta', 'Noche en el baño inesperada'],
  ['Espéculo', 'Consulta', 'Noche en el baño compartida'],
  ['Tacto rectal', 'Consulta', 'Noche en el baño incómoda'],
  ['Eco transvaginal', 'Consulta', 'Noche en el baño divertida'],
  ['Citología', 'Frotis', 'Noche en el baño privada'],
  ['Cultivo de orina', 'Análisis', 'Noche en el baño rápida'],
  ['Espermiograma', 'Análisis', 'Noche en el baño larga'],
  ['Banco de semen', 'Fecundación asistida', 'Noche en el baño borracha'],
  ['Donante anónimo', 'Fecundación asistida', 'Noche en el baño romántica'],
  ['Fertilización in vitro', 'Fecundación asistida', 'Noche en el baño picante'],
  ['Inseminación', 'Fecundación asistida', 'Noche en el baño absurda'],
  ['Heteronorma', 'Coño', 'Orientación'],
  ['Salir del armario', 'Coño', 'Noche en el baño memorable'],
  ['Orgullo', 'Coño', 'Noche en el baño vergonzosa'],
  ['Transformista', 'Actuación', 'Noche en el baño entrañable'],
  ['Baile de bola', 'Coño', 'Noche en el baño surrealista'],
  ['Comunidad fetiche', 'Coño', 'Tarde en el bar tensa'],
  ['Quedada fetiche', 'Coño', 'Tarde en el bar loca'],
  ['Fiesta en mazmorra', 'Coño', 'Cuarto con candado'],
  ['Fiesta sexual', 'Coño', 'Bar con música alta'],
  ['Taller de consentimiento', 'Coño', 'Tarde en el bar íntima'],
  ['Sexualidad positiva', 'Cultura', 'Tarde en el bar discreta'],
  ['Aceptar el cuerpo en la cama', 'Autoestima en pareja', 'Tarde en el bar improvisada'],
  ['Inseguridad con el cuerpo', 'Nervios', 'Tarde en el bar inesperada'],
  ['Luz apagada por vergüenza', 'Nervios', 'Tarde en el bar compartida'],
  ['Camiseta puesta en la cama', 'Nervios', 'Tarde en el bar incómoda'],
  ['Compararse con el porno', 'Trampa', 'Tarde en el bar divertida'],
  ['Expectativas de porno', 'Irreal', 'Tarde en el bar privada'],
  ['Duración de película porno', 'Ficción', 'Tarde en el bar rápida'],
  ['Actores que no paran', 'Ficción', 'Tarde en el bar larga'],
  ['Guion ridículo de porno', 'Repartidor de pizza', 'Medios'],
  ['Fontanero porno', 'Cliché', 'Medios'],
  ['Hermanastra porno', 'Cliché', 'Tarde en el bar borracha'],
  ['Profe particular porno', 'Cliché', 'Tarde en el bar romántica'],
  ['Masajista porno', 'Cliché', 'Tarde en el bar picante'],
  ['Vecina que pide sal', 'Cliché', 'Tarde en el bar absurda'],
  ['Repartidor de pizza', 'Cliché', 'Tarde en el bar memorable'],
  ['Sofá de prueba', 'Cliché', 'Tarde en el bar vergonzosa'],
  ['Cámara subjetiva', 'Coño', 'Tarde en el bar entrañable'],
  ['Casero', 'Coño', 'Tarde en el bar surrealista'],
  ['Compilatorio de acabadas dentro', 'Coño', 'Tarde de verano tensa'],
  ['Anime erótico', 'Coño', 'Tarde de verano loca'],
  ['Regla treinta y cuatro', 'Internet', 'Tarde de verano íntima'],
  ['Contenido adulto', 'Etiqueta', 'Tarde de verano discreta'],
  ['Anticipo de desnudos', 'Meme', 'Tarde de verano improvisada'],
  ['Foto provocadora', 'Coño', 'Tarde de verano inesperada'],
  ['Foto en lencería', 'Redes', 'Tarde de verano compartida'],
  ['Historia destacada caliente', 'Redes', 'Tarde de verano incómoda'],
  ['Círculo cercano +18', 'Red social', 'Tarde de verano divertida'],
  ['Canal de mensajería caliente', 'Coño', 'Tarde de verano privada'],
  ['Pack filtrado', 'Filtración', 'Tarde de verano rápida'],
  ['Suscripción mensual', 'Plataforma de fans', 'Tarde de verano larga'],
  ['Pagar propinas', 'Coño', 'Tarde de verano borracha'],
  ['Vídeo por encargo', 'Coño', 'Tarde de verano romántica'],
  ['Valorar la polla', 'Opinión sincera', 'Tarde de verano picante'],
  ['Instrucciones para pajearse', 'Coño', 'Tarde de verano absurda'],
  ['Fetiche de tragar', 'Coño', 'Tarde de verano memorable'],
  ['Humillación del tamaño', 'Coño', 'Tarde de verano vergonzosa'],
  ['Dominación financiera', 'Dinero', 'Cuarto con candado'],
  ['Dominadora financiera', 'Sugar mommy', 'Límite negociado'],
  ['Tributo', 'Pago', 'Tarde de verano entrañable'],
  ['Vaciar la cartera', 'Dinero', 'Tarde de verano surrealista'],
  ['Custodia de la llave', 'Castidad', 'Tarde entre amigos tensa'],
  ['Jaula de castidad', 'Coño', 'Tarde entre amigos loca'],
  ['Control del orgasmo', 'Coño', 'Tarde entre amigos íntima'],
  ['Negación del orgasmo', 'Coño', 'Tarde entre amigos discreta'],
  ['Provocación y negación', 'Coño', 'Tarde entre amigos improvisada'],
  ['Calentar por dentro', 'Coño', 'Tarde entre amigos inesperada'],
  ['Fetiche de fecundación', 'Fantasía de embarazo', 'Tarde entre amigos compartida'],
  ['Fetiche de embarazo', 'Fantasía de embarazo', 'Tarde entre amigos incómoda'],
  ['Fetiche de lactancia', 'Leche', 'Tarde entre amigos divertida'],
  ['Agonizar con ganas de mear', 'Coño', 'Tarde entre amigos privada'],
  ['Lluvia dorada', 'Orina', 'Tarde entre amigos rápida'],
  ['Coprofilia', 'Heces', 'Tarde entre amigos larga'],
  ['Juego con sangre', 'Coño', 'Tarde entre amigos borracha'],
  ['Juego con cuchillo', 'Coño', 'Tarde entre amigos romántica'],
  ['Juego con fuego', 'Coño', 'Tarde entre amigos picante'],
  ['Juego con agujas', 'Coño', 'Tarde entre amigos absurda'],
  ['Juego de asfixxia', 'Coño', 'Tarde entre amigos memorable'],
  ['Agarre del cuello', 'Coño', 'Tarde entre amigos vergonzosa'],
  ['Tirones de pelo', 'Coño', 'Tarde entre amigos entrañable'],
  ['Escupir', 'Coño', 'Tarde entre amigos surrealista'],
  ['Cachetear', 'Coño', 'Tarde en voz baja tensa'],
  ['Cachete en la cara', 'Coño', 'Tarde en voz baja loca'],
  ['Arcadas', 'Náuseas', 'Tarde en voz baja íntima'],
  ['Babeo', 'Coño', 'Tarde en voz baja discreta'],
  ['Mamada babosa', 'Babeo', 'Tarde en voz baja improvisada'],
  ['Hasta el fondo', 'Coño', 'Tarde en voz baja inesperada'],
  ['Golpes en los huevos', 'Patada', 'Tarde en voz baja compartida'],
  ['Tortura genital', 'Coño', 'Tarde en voz baja incómoda'],
  ['Banco de fantasías', 'Recuerdos', 'Solo'],
  ['Fantasía recurrente', 'Mente', 'Tarde en voz baja divertida'],
  ['Historial de incógnito', 'Navegador', 'Tarde en voz baja privada'],
  ['Borrar historial', 'Navegador', 'Tarde en voz baja rápida'],
  ['Navegación privada por vergüenza', 'Internet', 'Tarde en voz baja larga'],
  ['Cuenta alternativa', 'Secundaria', 'Tarde en voz baja borracha'],
  ['Cuenta anónima', 'Anónimo', 'Tarde en voz baja romántica'],
  ['Foro adulto', 'Coño', 'Tarde en voz baja picante'],
  ['Servidor adulto', 'Coño', 'Tarde en voz baja absurda'],
  ['Chat de voz caliente', 'Audio', 'Tarde en voz baja memorable'],
  ['Susurros eróticos', 'Audio', 'Tarde en voz baja vergonzosa'],
  ['Audio caliente', 'Nota de voz', 'Tarde en voz baja entrañable'],
  ['Nota de voz jadeando', 'Audio', 'Tarde en voz baja surrealista'],
  ['Buenos días con foto', 'Desnudo matutino', 'Tarde de fiesta tensa'],
  ['Buenas noches con audio', 'Sexteo', 'Tarde de fiesta loca'],
  ['Emoji de berenjena', 'Símbolo', 'Tarde de fiesta íntima'],
  ['Emoji de melocotón', 'Símbolo', 'Tarde de fiesta discreta'],
  ['Emoji de gotas', 'Símbolo', 'Tarde de fiesta improvisada'],
  ['Emoji de chile', 'Símbolo', 'Tarde de fiesta inesperada'],
  ['Texto sugerente', 'Indirecta', 'Tarde de fiesta compartida'],
  ['Indirectas en historias', 'Celos', 'Tarde de fiesta incómoda'],
  ['Canción dedicada en historias', 'Ligue', 'Tarde de fiesta divertida'],
  ['Publicar y borrar', 'Inseguridad', 'Tarde de fiesta privada'],
  ['Bloqueo suave', 'Coño', 'Tarde de fiesta rápida'],
  ['Bloqueo total', 'Coño', 'Tarde de fiesta larga'],
  ['Silenciar historias', 'Coño', 'Tarde de fiesta borracha'],
  ['Círculo cercano sin ti', 'Excluido', 'Tarde de fiesta romántica'],
];

export const ADULT_WORDS: readonly string[] = ADULT_WORD_PAIRS.map(([w]) => w);
