import type { WordPair } from './words.js';

/**
 * Pack +18 para Mr White / Heads Up / Just One.
 * Solo se usa si el jugador activa «Versión adultos».
 * Farsante: mismo tono, palabra distinta (no un sinónimo casi idéntico).
 * Pista Mr White: vibe cercana, sin delatar el taco.
 */
export const ADULT_WORD_PAIRS: readonly WordPair[] = [
  ['Coño', 'Mierda', 'Bronca de bar'],
  ['Joder', 'Hostia', 'Tropiezo inesperado'],
  ['Mierda', 'Joder', 'Día chungo'],
  ['Cabrón', 'Gilipollas', 'Discusión absurda'],
  ['Puta', 'Zorra', 'Insulto de pelea'],
  ['Gilipollas', 'Imbécil', 'Bronca entre colegas'],
  ['Hostia', 'Joder', 'Susto fuerte'],
  ['Pollas', 'Huevos', 'Chiste de barra'],
  ['Cojones', 'Huevos', 'Valor temerario'],
  ['Tetas', 'Culo', 'Vestido ajustado'],
  ['Culo', 'Tetas', 'Vaqueros rotos'],
  ['Follar', 'Ligar', 'Noche larga'],
  ['Correrse', 'Acabar', 'Respiración agitada'],
  ['Mamada', 'Sexo oral', 'Habitación a oscuras'],
  ['Ligar', 'Follar', 'Bar de noche'],
  ['Resaca', 'Migraña', 'Mañana después'],
  ['Porno', 'Lencería', 'Pestaña de incógnito'],
  ['Baile erótico', 'Striptease', 'Local con luces rojas'],
  ['Orgasmo', 'Clímax', 'Sábanas revueltas'],
  ['Preservativo', 'Pastilla', 'Farmacia de guardia'],
  ['Pastilla azul', 'Viagra', 'Bromas de farmacia'],
  ['Sexo oral', 'Mamada', 'Confidencia entre amigos'],
  ['Sexo anal', 'Sado', 'Límite atrevido'],
  ['Tanga', 'Hilo', 'Cajón de ropa'],
  ['Sujetador', 'Tanga', 'Probador de tienda'],
  ['Lencería', 'Picardías', 'Regalo envuelto'],
  ['Consolador', 'Vibrador', 'Cajón con llave'],
  ['Vibrador', 'Consolador', 'Pedido discreto'],
  ['Sado', 'Fetiche', 'Acuerdo en pareja'],
  ['Fetiche', 'Sado', 'Secreto compartido'],
  ['Intercambio de parejas', 'Infidelidad', 'Fiesta privada'],
  ['Infidelidad', 'Cornudo', 'Mensaje borrado'],
  ['Cornudo', 'Infidelidad', 'Rumores de pareja'],
  ['Amigovio', 'Follamigo', 'Relación'],
  ['Ligoteo', 'Coqueteo', 'Bar'],
  ['Borracho', 'Pedo', 'Alcohol'],
  ['Pedo', 'Coño', 'Gases'],
  ['Eructo', 'Regüeldo', 'Gases'],
  ['Vomitar', 'Devolver', 'Resaca'],
  ['Meada', 'Orina', 'Baño'],
  ['Cagar', 'Defecar', 'Baño'],
  ['Peo', 'Flatulencia', 'Gases'],
  ['Chorra', 'Polla', 'Ambiente picante'],
  ['Chocho', 'Vagina', 'Ambiente picante'],
  ['Pechochos', 'Tetas', 'Ambiente picante'],
  ['Nalgas', 'Culo', 'Ambiente picante'],
  ['Beso negro', 'Coño', 'Sexo oral'],
  ['Triolismo', 'Coño', 'Ambiente picante'],
  ['Sexo grupal', 'Coño', 'Ambiente picante'],
  ['Orgía', 'Fiesta sexual', 'Ambiente picante'],
  ['Mirón', 'Coño', 'Ambiente picante'],
  ['Exhibicionista', 'Mirón al revés', 'Ambiente picante'],
  ['Sexteo', 'Desnudos', 'Móvil'],
  ['Desnudos', 'Fotos calientes', 'Móvil'],
  ['Plataforma de fans', 'Contenido +18', 'Ambiente picante'],
  ['App de ligue', 'Ligues', 'Ambiente picante'],
  ['Dejar en visto', 'Desaparición', 'Ligue'],
  ['Zona de amigos', 'Coño', 'Ligue'],
  ['Zorra', 'Puta', 'Ambiente picante'],
  ['Hijo de puta', 'Insulto fuerte', 'Ambiente picante'],
  ['Capullo', 'Gilipollas', 'Ambiente picante'],
  ['Imbécil', 'Idiota', 'Ambiente picante'],
  ['Lameculos', 'Pelota', 'Ambiente picante'],
  ['Mamón', 'Chupóptero', 'Ambiente picante'],
  ['Tontolaba', 'Idiota', 'Ambiente picante'],
  ['Pajero', 'Vicioso', 'Ambiente picante'],
  ['Calentorro', 'Fogonazo', 'Ambiente picante'],
  ['Empollón', 'Calentón', 'Ambiente picante'],
  ['Corrida', 'Eyaculación', 'Ambiente picante'],
  ['Lubricante', 'Gel', 'Ambiente picante'],
  ['Postura del perrito', 'A cuatro', 'Ambiente picante'],
  ['Misionero', 'Clásico', 'Ambiente picante'],
  ['A caballo', 'A horcajadas', 'Ambiente picante'],
  ['Rapidito', 'Coño', 'Ambiente picante'],
  ['Rapidito en el baño', 'Coño', 'Fiesta'],
  ['Fiesta de madrugada', 'Después de fiesta', 'Ambiente picante'],
  ['Límite', 'Palabra de seguridad', 'Sadomaso'],
  ['Azotes', 'Nalgadas', 'Sadomaso'],
  ['Esposas', 'Ataduras', 'Sadomaso'],
  ['Antifaz', 'Máscara', 'Sadomaso'],
  ['Látigo', 'Fusta', 'Sadomaso'],
  ['Dominadora', 'Coño', 'Sadomaso'],
  ['Sumiso', 'Esclavo', 'Sadomaso'],
  ['Cornudo consentido', 'Coño', 'Ambiente picante'],
  ['Esposa libre', 'Coño', 'Ambiente picante'],
  ['Penetrar con arnés', 'Coño', 'Ambiente picante'],
  ['Arnés', 'Coño', 'Ambiente picante'],
  ['Agujero del placer', 'Coño', 'Ambiente picante'],
  ['Sexo en el coche', 'Coño', 'Exterior'],
  ['Sexo en público', 'Coño', 'Riesgo'],
  ['Sexo en el avión', 'Coño', 'Riesgo'],
  ['Semen', 'Leche', 'Fluido'],
  ['Flujo', 'Lubricación', 'Ambiente picante'],
  ['Clítoris', 'Punto G', 'Ambiente picante'],
  ['Punto G', 'Placer', 'Ambiente picante'],
  ['Próstata', 'Punto P', 'Ambiente picante'],
  ['Testículos', 'Huevos', 'Ambiente picante'],
  ['Escroto', 'Saco', 'Ambiente picante'],
  ['Prepucio', 'Piel', 'Ambiente picante'],
  ['Labios', 'Vulva', 'Ambiente picante'],
  ['Pecho', 'Teta', 'Ambiente picante'],
  ['Pezón', 'Pechuga', 'Ambiente picante'],
  ['Ombligo', 'Piercing', 'Ambiente picante'],
  ['Ingle', 'Zona baja', 'Ambiente picante'],
  ['Entrepiemas', 'Muslos', 'Ambiente picante'],
  ['Kama sutra', 'Posturas', 'Libro'],
  ['Cincuenta sombras', 'Romance erótico', 'Libro'],
  ['Revista erótica', 'Coño', 'Medios'],
  ['Revista erótica', 'Coño', 'Medios'],
  ['Burdel', 'Prostíbulo', 'Local'],
  ['Puticlub', 'Coño', 'Local'],
  ['Sauna gay', 'Baños', 'Local'],
  ['Cuarto oscuro', 'Coño', 'Local'],
  ['Agujero del placer', 'Coño', 'Local'],
  ['Juguete a distancia', 'App de juguete', 'Tecnología'],
  ['Modelo de cámara', 'Emisor en directo +18', 'Ambiente picante'],
  ['Patrocinador', 'Coño', 'Relación'],
  ['Mantenida', 'Coño', 'Relación'],
  ['Acompañante de pago', 'Coño', 'Trabajo'],
  ['Gigoló', 'Acompañante', 'Trabajo'],
  ['Prostituta', 'Trabajador sexual', 'Trabajo'],
  ['Putero', 'Cliente', 'Local'],
  ['Chulo', 'Proxeneta', 'Calle'],
  ['Folladero', 'Garito', 'Local'],
  ['Ligue de una noche', 'Coño', 'Fiesta'],
  ['Polvo', 'Follada', 'Ambiente picante'],
  ['Echar un polvo', 'Follar', 'Ambiente picante'],
  ['Paja', 'Masturbación', 'Solo'],
  ['Masturbarse', 'Tocarse', 'Solo'],
  ['Sueño húmedo', 'Ensueño', 'Ambiente picante'],
  ['Calentura', 'Lujuria', 'Ambiente picante'],
  ['Morbo', 'Excitación', 'Ambiente picante'],
  ['Guarrada', 'Coño', 'Ambiente picante'],
  ['Guarro', 'Cerdo', 'Ambiente picante'],
  ['Cerda', 'Zorra', 'Ambiente picante'],
  ['Bisexual', 'Coño', 'Orientación'],
  ['Pansexual', 'Sin etiqueta', 'Orientación'],
  ['Poliamor', 'Varias parejas', 'Relación'],
  ['Pareja abierta', 'Coño', 'Relación'],
  ['Cornuda consentida', 'Coño', 'Ambiente picante'],
  ['Humillación', 'Degradación', 'Sadomaso'],
  ['Nalgadas', 'Azotes', 'Sadomaso'],
  ['Juego con cera', 'Coño', 'Sadomaso'],
  ['Juego con hielo', 'Coño', 'Sadomaso'],
  ['Juego de rol', 'Disfraz', 'Fantasía'],
  ['Juego de enfermera', 'Coño', 'Fantasía'],
  ['Fantasía del jefe', 'Coño', 'Ambiente picante'],
  ['Fantasía del profe', 'Coño', 'Ambiente picante'],
  ['Uniforme sexy', 'Disfraz', 'Ropa'],
  ['Medias de red', 'Lencería', 'Ropa'],
  ['Portaligas', 'Lencería', 'Ropa'],
  ['Body abierto', 'Picardías', 'Ropa'],
  ['Camisón corto', 'Coño', 'Ropa'],
  ['Anillo para el pene', 'Coño', 'Ambiente picante'],
  ['Tapón anal', 'Coño', 'Ambiente picante'],
  ['Bolas anales', 'Coño', 'Ambiente picante'],
  ['Masturbador', 'Coño', 'Ambiente picante'],
  ['Máquina sexual', 'Coño', 'Ambiente picante'],
  ['Vapores', 'Amilo', 'Fiesta'],
  ['Éxtasis', 'Pastilla', 'Fiesta'],
  ['Porro', 'Canuto', 'Fiesta'],
  ['Pipa de agua', 'Coño', 'Fiesta'],
  ['Chupito', 'Trago', 'Bar'],
  ['Cubata', 'Combinado', 'Bar'],
  ['Combinado hasta morir', 'Borrachera', 'Bar'],
  ['Despedida de soltero', 'Coño', 'Fiesta'],
  ['Bailarina erótica', 'Baile erótico', 'Fiesta'],
  ['Baile privado', 'Coño', 'Local'],
  ['Baile de barra', 'Coño', 'Ambiente picante'],
  ['Perreo', 'Coño', 'Baile'],
  ['Perreo intenso', 'Reggaetón', 'Baile'],
  ['Beso con lengua', 'Coño', 'Ambiente picante'],
  ['Morreo', 'Frenazo', 'Beso'],
  ['Peto', 'Manoseo', 'Manos'],
  ['Mano inocente', 'Debajo de la ropa', 'Manos'],
  ['Dedos', 'Penetración digital', 'Manos'],
  ['Sesenta y nueve', '69', 'Sexo oral'],
  ['Garganta profunda', 'Coño', 'Sexo oral'],
  ['Acabada en la cara', 'Coño', 'Ambiente picante'],
  ['Acabada dentro', 'Coño', 'Ambiente picante'],
  ['Sacar fuera', 'Coño', 'Ambiente picante'],
  ['Sin condón', 'Coño', 'Riesgo'],
  ['Prueba de embarazo', 'Coño', 'Ambiente picante'],
  ['Pastilla del día después', 'Emergencia', 'Ambiente picante'],
  ['Infección sexual', 'Enfermedad', 'Salud'],
  ['Herpes', 'Llaga', 'Salud'],
  ['Candidiasis', 'Hongos', 'Salud'],
  ['Hemorroides', 'Almorranas', 'Salud'],
  ['Estreñimiento', 'Tapón', 'Baño'],
  ['Diarrea', 'Cagalera', 'Baño'],
  ['Estreñido', 'Aprieto', 'Baño'],
  ['Lavativa', 'Enema', 'Baño'],
  ['Bidé', 'Lavado', 'Baño'],
  ['Orinal', 'Coño', 'Baño'],
  ['Cagada monumental', 'Lío', 'Error'],
  ['La cagaste', 'La liastes', 'Error'],
  ['Me la suda', 'Me importa un pepino', 'Desprecio'],
  ['Me importa una mierda', 'Pasotismo', 'Desprecio'],
  ['Que te jodan', 'Que te den', 'Ambiente picante'],
  ['Vete a la mierda', 'Lárgate', 'Ambiente picante'],
  ['Que te den por culo', 'Coño', 'Ambiente picante'],
  ['Tocapelotas', 'Pesado', 'Ambiente picante'],
  ['Rompepelotas', 'Pesado', 'Ambiente picante'],
  ['Huevón', 'Perezoso', 'Ambiente picante'],
  ['Huevos revueltos', 'Desayuno', 'Doble sentido'],
  ['Chupar rueda', 'Ciclismo', 'Doble sentido'],
  ['Meter un gol', 'Fútbol', 'Doble sentido'],
  ['Entrar por detrás', 'Fútbol', 'Doble sentido'],
  ['Paliza', 'Golpiza', 'Bronca'],
  ['Hostia limpia', 'Puñetazo', 'Bronca'],
  ['Galleta', 'Bofetada', 'Bronca'],
  ['Leñazo', 'Golpe', 'Bronca'],
  ['Coñazo', 'Pesadez', 'Ambiente picante'],
  ['Jodón', 'Pesado', 'Ambiente picante'],
  ['Mierdoso', 'Asqueroso', 'Ambiente picante'],
  ['Cabronada', 'Faena', 'Ambiente picante'],
  ['Putada', 'Faena', 'Ambiente picante'],
  ['Gilipollez', 'Tontería', 'Ambiente picante'],
  ['Hostión', 'Golpe', 'Ambiente picante'],
  ['Pollazo', 'Golpe', 'Ambiente picante'],
  ['Cojonudo', 'Genial', 'Taco positivo'],
  ['De puta madre', 'Genial', 'Taco positivo'],
  ['La hostia', 'Brutal', 'Taco positivo'],
  ['Flipante', 'Alucinante', 'Taco positivo'],
  ['Me cago en todo', 'Cabreo', 'Ambiente picante'],
  ['Me cago en la leche', 'Cabreo', 'Ambiente picante'],
  ['Me cago en Dios', 'Cabreo', 'Ambiente picante'],
  ['Leche', 'Semen', 'Doble sentido'],
  ['Crema', 'Semen', 'Doble sentido'],
  ['Nata', 'Semen', 'Doble sentido'],
  ['Chorro', 'Eyaculación', 'Ambiente picante'],
  ['Chorrito', 'Eyaculación', 'Ambiente picante'],
  ['Acabar dentro', 'Acabada dentro', 'Ambiente picante'],
  ['Acabar fuera', 'Sacar fuera', 'Ambiente picante'],
  ['Sin condón', 'Coño', 'Riesgo'],
  ['Con condón', 'Coño', 'Ambiente picante'],
  ['Forro', 'Preservativo', 'Ambiente picante'],
  ['Goma', 'Condón', 'Ambiente picante'],
  ['Diafragma', 'Método', 'Ambiente picante'],
  ['Píldora', 'Anticonceptivo', 'Ambiente picante'],
  ['Marcha atrás', 'Coño', 'Riesgo'],
  ['Calcular días', 'Ritmo', 'Riesgo'],
  ['Pastilla abortiva', 'Farmacia', 'Salud'],
  ['Ecografía', 'Embarazo', 'Salud'],
  ['Triple prueba', 'Infección sexual', 'Salud'],
  ['Serología', 'Análisis', 'Salud'],
  ['Vacuna del papiloma', 'Prevención', 'Salud'],
  ['Prevención del VIH', 'Coño', 'Salud'],
  ['Urgencia del VIH', 'Emergencia', 'Salud'],
  ['Candidiasis', 'Hongos', 'Salud'],
  ['Cistitis', 'Infección', 'Salud'],
  ['Prostatitis', 'Infección', 'Salud'],
  ['Fimosis', 'Prepucio', 'Salud'],
  ['Frenillo', 'Genital', 'Salud'],
  ['Circuncisión', 'Cirugía', 'Salud'],
  ['Vasectomía', 'Cirugía', 'Salud'],
  ['Ligadura', 'Cirugía', 'Salud'],
  ['Implante anticonceptivo', 'Brazo', 'Ambiente picante'],
  ['Anticonceptivo interno', 'Coño', 'Ambiente picante'],
  ['Anillo vaginal', 'Anticonceptivo', 'Ambiente picante'],
  ['Parche anticonceptivo', 'Hormonas', 'Ambiente picante'],
  ['Gel estimulante', 'Lubricante', 'Ambiente picante'],
  ['Aceite de masaje', 'Coño', 'Ambiente picante'],
  ['Pluma de cosquillas', 'Juego', 'Ambiente picante'],
  ['Venda', 'Antifaz', 'Sadomaso'],
  ['Mordaza', 'Bola', 'Sadomaso'],
  ['Collar de sumisión', 'Coño', 'Sadomaso'],
  ['Correa', 'Paseo', 'Sadomaso'],
  ['Paleta', 'Coño', 'Sadomaso'],
  ['Fusta', 'Látigo corto', 'Sadomaso'],
  ['Fusta corta', 'Látigo', 'Sadomaso'],
  ['Nalgada seca', 'Azote', 'Sadomaso'],
  ['Marcas', 'Moretones', 'Sadomaso'],
  ['Cuidados posteriores', 'Coño', 'Sadomaso'],
  ['Negociación', 'Límites', 'Sadomaso'],
  ['Semáforo', 'Límites', 'Sadomaso'],
  ['Rojo', 'Parar', 'Sadomaso'],
  ['Ámbar', 'Despacio', 'Sadomaso'],
  ['Verde', 'Seguir', 'Sadomaso'],
  ['Juego de golpes', 'Coño', 'Sadomaso'],
  ['Ataduras', 'Coño', 'Sadomaso'],
  ['Atadura japonesa', 'Cuerda', 'Sadomaso'],
  ['Cuerda japonesa', 'Coño', 'Sadomaso'],
  ['Suspensión', 'Colgado', 'Sadomaso'],
  ['Privación sensorial', 'Coño', 'Sadomaso'],
  ['Juego de temperatura', 'Coño', 'Sadomaso'],
  ['Juego eléctrico', 'Descargas', 'Sadomaso'],
  ['Juego de mascota', 'Animalito', 'Sadomaso'],
  ['Fetiche de papi', 'Rol', 'Sadomaso'],
  ['Juego de edad', 'Rol', 'Sadomaso'],
  ['Juego médico', 'Clínica', 'Sadomaso'],
  ['No consentimiento pactado', 'Coño', 'Sadomaso'],
  ['Fetiche de elogios', 'Coño', 'Sadomaso'],
  ['Degradación', 'Insultos eróticos', 'Sadomaso'],
  ['Disponible siempre', 'Coño', 'Ambiente picante'],
  ['Juego en público', 'Coño', 'Ambiente picante'],
  ['Sexo en el coche', 'Coño', 'Ambiente picante'],
  ['Balcón', 'Exterior', 'Ambiente picante'],
  ['Ascensor', 'Riesgo', 'Ambiente picante'],
  ['Probador', 'Tienda', 'Ambiente picante'],
  ['Cine vacío', 'Sala', 'Ambiente picante'],
  ['Playa nudista', 'Coño', 'Exterior'],
  ['Camping salvaje', 'Tienda', 'Exterior'],
  ['Jacuzzi privado', 'Agua', 'Exterior'],
  ['Ducha juntos', 'Baño', 'Ambiente picante'],
  ['Baño del bar', 'Rapidito', 'Fiesta'],
  ['Terraza de fiesta', 'Exterior', 'Ambiente picante'],
  ['Trastero', 'Rincón', 'Fiesta'],
  ['Aparcamiento', 'Coche', 'Fiesta'],
  ['VTC caliente', 'Vuelta', 'Fiesta'],
  ['Taxi de madrugada', 'Vuelta', 'Fiesta'],
  ['Resacón histórico', 'Resaca', 'Fiesta'],
  ['Mareo de alcohol', 'Resaca', 'Fiesta'],
  ['Boca de algodón', 'Resaca', 'Fiesta'],
  ['Dolor de cabeza', 'Resaca', 'Fiesta'],
  ['Agua con gas y paracetamol', 'Resaca', 'Fiesta'],
  ['Kebab de madrugada', 'Resaca', 'Fiesta'],
  ['Pizza a las 4', 'Resaca', 'Fiesta'],
  ['Tabaco de mentira', 'Porro', 'Fiesta'],
  ['Porro mal liado', 'Canuto', 'Fiesta'],
  ['Humazo', 'Humo', 'Fiesta'],
  ['Colocón', 'Colgado', 'Fiesta'],
  ['Bajón', 'Caída', 'Fiesta'],
  ['Subidón', 'Éxtasis', 'Fiesta'],
  ['Pastilleo', 'Pastillas', 'Fiesta'],
  ['Raya', 'Coca', 'Fiesta'],
  ['Farlopa', 'Coca', 'Fiesta'],
  ['Chute', 'Inyección', 'Fiesta'],
  ['Ketamina', 'Coño', 'Fiesta'],
  ['Éxtasis', 'Pastilla', 'Fiesta'],
  ['Setas', 'Alucinógenos', 'Fiesta'],
  ['Ácido', 'Viaje alucinógeno', 'Fiesta'],
  ['G de fiesta', 'Droga líquida', 'Ambiente picante'],
  ['Popper en la disco', 'Vapores', 'Fiesta'],
  ['Esnifar', 'Coño', 'Fiesta'],
  ['Camello', 'Coño', 'Fiesta'],
  ['Camello del barrio', 'Coño', 'Fiesta'],
  ['Trapicheo', 'Venta', 'Fiesta'],
  ['Colocarse', 'Drogarse', 'Fiesta'],
  ['Ir puesto', 'Colocado', 'Fiesta'],
  ['Ir ciego', 'Borracho', 'Fiesta'],
  ['Ir petao', 'Borracho', 'Fiesta'],
  ['Ir hasta el culo', 'Borracho', 'Fiesta'],
  ['Blanco total', 'Borracho', 'Fiesta'],
  ['Apagón etílico', 'Coño', 'Fiesta'],
  ['No me acuerdo de nada', 'Apagón etílico', 'Fiesta'],
  ['Historias vergonzosas', 'Resaca social', 'Fiesta'],
  ['Beso a desconocido', 'Ligue', 'Fiesta'],
  ['Ligue de baño', 'Rapidito', 'Fiesta'],
  ['Número falso', 'Dejar en visto', 'Ligue'],
  ['Dejar en visto', 'Coño', 'Ligue'],
  ['Dar migajas', 'Coño', 'Ligue'],
  ['Orbitar', 'Coño', 'Ligue'],
  ['Casi pareja', 'Coño', 'Ligue'],
  ['Pareja a medias en redes', 'Coño', 'Ligue'],
  ['Pareja pública en redes', 'Coño', 'Ligue'],
  ['Tener de reserva', 'Banquillo', 'Ligue'],
  ['Vuelve el ex', 'Coño', 'Ligue'],
  ['Colchón afectivo', 'Coño', 'Ligue'],
  ['Otras apps a la vez', 'Coño', 'Ligue'],
  ['Perfil falso', 'Coño', 'Ligue'],
  ['Bombardeo afectivo', 'Coño', 'Ligue'],
  ['Manipulación afectiva', 'Coño', 'Ligue'],
  ['Halago hiriente', 'Pique', 'Ligue'],
  ['Ligón de manual', 'Coño', 'Ligue'],
  ['Primer mensaje', 'Coño', 'App'],
  ['Deslizar a la derecha', 'Me gusta', 'App'],
  ['Deslizar a la izquierda', 'Paso', 'App'],
  ['Súper me gusta', 'Destacado', 'App'],
  ['Coincidencia', 'Coño', 'App'],
  ['Quitar coincidencia', 'Borrar', 'App'],
  ['Biografía falsa', 'Perfil', 'App'],
  ['Foto de hace 10 años', 'Perfil', 'App'],
  ['Foto con filtro', 'Perfil', 'App'],
  ['Foto en la playa', 'Perfil', 'App'],
  ['Foto del gimnasio', 'Perfil', 'App'],
  ['Foto con el ex recortado', 'Perfil', 'App'],
  ['Quedada para un café', 'Primera cita', 'Ligue'],
  ['Quedada para un vermú', 'Primera cita', 'Ligue'],
  ['Quedada en casa', 'Ver una serie y follar', 'Ligue'],
  ['Ver una serie y follar', 'Coño', 'Ligue'],
  ['Ver una serie', 'Excusa', 'Ligue'],
  ['Masaje con final feliz', 'Coño', 'Ambiente picante'],
  ['Final feliz', 'Acabar', 'Ambiente picante'],
  ['Masaje prostático', 'Punto P', 'Ambiente picante'],
  ['Estimulación anal', 'Tapón anal', 'Ambiente picante'],
  ['Beso negro', 'Coño', 'Sexo oral'],
  ['Sentarse en la cara', 'Coño', 'Sexo oral'],
  ['Sentarse en la cara', 'Coño', 'Sexo oral'],
  ['Paja con la mano', 'Coño', 'Ambiente picante'],
  ['Paja con los pies', 'Coño', 'Ambiente picante'],
  ['Paja con tetas', 'Coño', 'Ambiente picante'],
  ['Paja con tetas', 'Coño', 'Ambiente picante'],
  ['Entre muslos', 'Coño', 'Ambiente picante'],
  ['Frotarse vestidos', 'Coño', 'Ambiente picante'],
  ['Frotamiento', 'Frotarse', 'Ambiente picante'],
  ['Llevar al límite', 'Coño', 'Ambiente picante'],
  ['Orgasmo a medias', 'Coño', 'Ambiente picante'],
  ['Varios orgasmos', 'Coño', 'Ambiente picante'],
  ['Chorrito', 'Coño', 'Ambiente picante'],
  ['Eyaculación femenina', 'Chorrito', 'Ambiente picante'],
  ['Orgasmo prostático', 'Punto P', 'Ambiente picante'],
  ['Juego con pezones', 'Coño', 'Ambiente picante'],
  ['Juego con tetas', 'Coño', 'Ambiente picante'],
  ['Hablar guarro', 'Coño', 'Ambiente picante'],
  ['Sexo telefónico', 'Coño', 'Ambiente picante'],
  ['Videollamada caliente', 'Coño', 'Ambiente picante'],
  ['Cámara a cámara', 'Coño', 'Ambiente picante'],
  ['Menú de propinas', 'Coño', 'Ambiente picante'],
  ['Espectáculo privado', 'Coño', 'Ambiente picante'],
  ['Foto de polla', 'Coño', 'Móvil'],
  ['Foto íntima', 'Coño', 'Móvil'],
  ['Filtración de desnudos', 'Coño', 'Ambiente picante'],
  ['Porno de venganza', 'Coño', 'Ambiente picante'],
  ['Consentimiento explícito', 'Sí claro', 'Ética'],
  ['Retirar el consentimiento', 'Parar', 'Ética'],
  ['Preguntar si todo va bien', '¿Todo bien?', 'Ética'],
  ['Sobriedad y consentimiento', 'Límites', 'Ética'],
  ['No es no', 'Límite', 'Ética'],
  ['Solo sí es sí', 'Consentimiento', 'Ética'],
  ['Acoso callejero', 'Piropo basura', 'Ambiente picante'],
  ['Mano en el culo', 'Agarrón', 'Calle'],
  ['Mirada lasciva', 'Mirón', 'Calle'],
  ['Frotarse en el metro', 'Coño', 'Calle'],
  ['Debajo de la falda', 'Coño', 'Calle'],
  ['Voyeurismo no consentido', 'Mirón', 'Calle'],
  ['Exhibición', 'Mostrar genitales', 'Calle'],
  ['Enseñar el culo', 'Mostrar culo', 'Calle'],
  ['Correr desnudo', 'Coño', 'Calle'],
  ['Topless playa', 'Pechos al aire', 'Ambiente picante'],
  ['Desnudo integral', 'Nudismo', 'Playa'],
  ['Bronceado de culo', 'Marcas', 'Playa'],
  ['Crema solar en zonas íntimas', 'Playa', 'Playa'],
  ['Pelo púbico', 'Vello', 'Ambiente picante'],
  ['Depilación brasileña', 'Cera', 'Ambiente picante'],
  ['Depilación total', 'Cera total', 'Ambiente picante'],
  ['Franja de vello', 'Coño', 'Ambiente picante'],
  ['Monte de Venus', 'Coño', 'Ambiente picante'],
  ['Afeitado íntimo', 'Cuchilla', 'Ambiente picante'],
  ['Irritación de cera', 'Rojo', 'Ambiente picante'],
  ['Foliculitis', 'Granos', 'Ambiente picante'],
  ['Estrías', 'Marcas', 'Ambiente picante'],
  ['Celulitis', 'Piel de naranja', 'Ambiente picante'],
  ['Barriga cervecera', 'Curro', 'Ambiente picante'],
  ['Camino de vello', 'Coño', 'Ambiente picante'],
  ['Vello del pecho', 'Coño', 'Ambiente picante'],
  ['Sisas', 'Axilas', 'Ambiente picante'],
  ['Hedor a sexo', 'Olor', 'Ambiente picante'],
  ['Aliento a alcohol y sexo', 'Mañana', 'Resaca'],
  ['Sábana manchada', 'Lavadora', 'Ambiente picante'],
  ['Toalla de emergencia', 'Baño', 'Ambiente picante'],
  ['Papel higiénico impropio', 'Baño', 'Ambiente picante'],
  ['Ducha fría después', 'Bajón', 'Ambiente picante'],
  ['Cigarro postcoital', 'Cliché', 'Ambiente picante'],
  ['La pequeña muerte', 'Orgasmo', 'Ambiente picante'],
  ['Mirarse a los ojos', 'Intimidad', 'Ambiente picante'],
  ['Risa nerviosa en la cama', 'Torpeza', 'Ambiente picante'],
  ['Diente contra diente', 'Beso torpe', 'Beso'],
  ['Ortodoncia al besar', 'Beso', 'Beso'],
  ['Babeo excesivo', 'Beso', 'Beso'],
  ['Chupar el cuello', 'Chupetón', 'Beso'],
  ['Chupetón visible', 'Moratón', 'Beso'],
  ['Arañazos en la espalda', 'Marcas', 'Ambiente picante'],
  ['Mordisco en el hombro', 'Marcas', 'Ambiente picante'],
  ['Pelo agarrado', 'Jalón', 'Ambiente picante'],
  ['Cachete en el culo', 'Nalgada', 'Ambiente picante'],
  ['Empujón rítmico', 'Follar', 'Ambiente picante'],
  ['Cama que cruje', 'Ruido', 'Ambiente picante'],
  ['Vecinos escuchando', 'Ruido', 'Ambiente picante'],
  ['Paredes de papel', 'Ruido', 'Ambiente picante'],
  ['Gritos ahogados', 'Almohada', 'Ambiente picante'],
  ['Morder la almohada', 'Silencio', 'Ambiente picante'],
  ['Lista de canciones sexy', 'Música', 'Ambiente picante'],
  ['Luz baja', 'Ambiente', 'Ambiente picante'],
  ['Velas que huelen a vainilla', 'Ambiente', 'Ambiente picante'],
  ['Sábana de satén', 'Cama', 'Ambiente picante'],
  ['Lencería nueva', 'Ropa', 'Ambiente picante'],
  ['Ropa interior del día a día', 'Coño', 'Ambiente picante'],
  ['Calzoncillos del abuelo', 'Ropa', 'Ambiente picante'],
  ['Calcetines puestos', 'Torpeza', 'Ambiente picante'],
  ['Sujetador imposible', 'Broche', 'Ropa'],
  ['Cremallera atascada', 'Ropa', 'Ropa'],
  ['Tirante que se rompe', 'Picardías', 'Ropa'],
  ['Tacones en la cama', 'Ropa', 'Ambiente picante'],
  ['Camisa a medio abrir', 'Ropa', 'Ambiente picante'],
  ['Vaqueros difíciles', 'Ropa', 'Ambiente picante'],
  ['Cinturón a contrarreloj', 'Ropa', 'Ambiente picante'],
  ['Condón al revés', 'Torpeza', 'Ambiente picante'],
  ['Condón caducado', 'Riesgo', 'Ambiente picante'],
  ['Condón que se rompe', 'Susto', 'Ambiente picante'],
  ['Buscar el condón a oscuras', 'Torpeza', 'Ambiente picante'],
  ['Cartera sin condón', 'Faena', 'Ambiente picante'],
  ['Farmacia de guardia', 'Emergencia', 'Ambiente picante'],
  ['Máquina expendedor de condones', 'Baño', 'Ambiente picante'],
  ['Lubricante frío', 'Susto', 'Ambiente picante'],
  ['Lubricante con sabor', 'Gel', 'Ambiente picante'],
  ['Lubricante que pica', 'Gel', 'Ambiente picante'],
  ['Aceite que rompe el látex', 'Error', 'Ambiente picante'],
  ['Posición imposible', 'Kama sutra', 'Ambiente picante'],
  ['Calambre en la pierna', 'Torpeza', 'Ambiente picante'],
  ['Pierna dormida', 'Torpeza', 'Ambiente picante'],
  ['Se sale', 'Torpeza', 'Ambiente picante'],
  ['No entra', 'Torpeza', 'Ambiente picante'],
  ['Demasiado seco', 'Lubricante', 'Ambiente picante'],
  ['Demasiado rápido', 'Llevar al límite', 'Ambiente picante'],
  ['Se te baja', 'Vergüenza', 'Ambiente picante'],
  ['Ansiedad de rendimiento', 'Nervios', 'Ambiente picante'],
  ['Fingir el orgasmo', 'Teatro', 'Ambiente picante'],
  ['Preguntar ¿ya?', 'Torpeza', 'Ambiente picante'],
  ['Mirar el móvil en la cama', 'Faena', 'Ambiente picante'],
  ['Dormirse después de acabar', 'Clásico', 'Ambiente picante'],
  ['Cucharita', 'Abrazo', 'Ambiente picante'],
  ['Cucharota', 'Cucharita', 'Ambiente picante'],
  ['Cucharita pequeña', 'Coño', 'Ambiente picante'],
  ['Hablar del ex en la cama', 'Error', 'Ambiente picante'],
  ['Decir el nombre equivocado', 'Horror', 'Ambiente picante'],
  ['Reírse de un pedo', 'Torpeza', 'Ambiente picante'],
  ['Pedo en pleno acto', 'Vergüenza', 'Ambiente picante'],
  ['Ruidos intestinales', 'Vergüenza', 'Ambiente picante'],
  ['Estómago vacío ruge', 'Vergüenza', 'Ambiente picante'],
  ['Ir al baño a escondidas', 'Pausa', 'Ambiente picante'],
  ['Lavarse los dientes antes', 'Higiene', 'Ambiente picante'],
  ['Ducha previa', 'Higiene', 'Ambiente picante'],
  ['Aliento a ajo', 'Faena', 'Beso'],
  ['Sudor de gimnasio', 'Olor', 'Ambiente picante'],
  ['Colonia excesiva', 'Olor', 'Ambiente picante'],
  ['Feromonas de bote', 'Colonia', 'Ambiente picante'],
  ['Ropa interior limpia por si acaso', 'Previsión', 'Ambiente picante'],
  ['Afeitarse por si acaso', 'Previsión', 'Ambiente picante'],
  ['Sábanas limpias por si acaso', 'Previsión', 'Ambiente picante'],
  ['Copas de más', 'Alcohol', 'Fiesta'],
  ['Valor de alcohol', 'Coraje', 'Fiesta'],
  ['Confesiones borrachas', 'Fiesta', 'Fiesta'],
  ['Bailar pegado', 'Perreo', 'Baile'],
  ['Manos en la cintura', 'Baile', 'Baile'],
  ['Frotar en la pista', 'Perreo', 'Baile'],
  ['Beso en la pista', 'Ligue', 'Fiesta'],
  ['Sacar a bailar', 'Ligue', 'Fiesta'],
  ['Invitar a chupitos', 'Ligue', 'Bar'],
  ['Pagar la ronda', 'Ligue', 'Bar'],
  ['Pedir el número', 'Ligue', 'Bar'],
  ['Red social en vez de número', 'Ligue', 'Bar'],
  ['Seguir en todas las redes', 'Acecho ligero', 'Ligue'],
  ['Espiar historias', 'Coño', 'Ligue'],
  ['Ver la ubicación', 'Espiar', 'Ligue'],
  ['Preguntar a amigos comunes', 'Cotilleo', 'Ligue'],
  ['Cotillear el ex', 'Cotilleo', 'Ligue'],
  ['Comparar con el ex', 'Error', 'Relación'],
  ['Revisar el móvil', 'Celos', 'Relación'],
  ['Contraseña compartida', 'Confianza', 'Relación'],
  ['Celos en la discoteca', 'Bronca', 'Relación'],
  ['Bronca de madrugada', 'Pareja', 'Relación'],
  ['Sexo de reconciliación', 'Coño', 'Ambiente picante'],
  ['Sexo de despedida', 'Adiós', 'Ambiente picante'],
  ['Sexo aburrido de sofá', 'Rutina', 'Ambiente picante'],
  ['Rutina de siempre los viernes', 'Coño', 'Ambiente picante'],
  ['Calendario de ovulación', 'Apps', 'Relación'],
  ['App de ciclos', 'Regla', 'Salud'],
  ['Dolor menstrual', 'Regla', 'Salud'],
  ['Cólico bestial', 'Regla', 'Salud'],
  ['Tampones', 'Regla', 'Salud'],
  ['Compresa', 'Regla', 'Salud'],
  ['Copa menstrual', 'Regla', 'Salud'],
  ['Mancha en la sábana', 'Regla', 'Salud'],
  ['Sexo con la regla', 'Periodo', 'Ambiente picante'],
  ['Toalla roja', 'Regla', 'Ambiente picante'],
  ['Antojo absurdo', 'Embarazo', 'Relación'],
  ['Test de farmacia positivo', 'Susto', 'Salud'],
  ['Test de farmacia negativo', 'Alivio', 'Salud'],
  ['Retraso', 'Susto', 'Salud'],
  ['Síntomas raros', 'Susto', 'Salud'],
  ['Visita al ginecólogo', 'Consulta', 'Salud'],
  ['Visita al urólogo', 'Consulta', 'Salud'],
  ['Exploración íntima', 'Consulta', 'Salud'],
  ['Espéculo', 'Consulta', 'Salud'],
  ['Tacto rectal', 'Consulta', 'Salud'],
  ['Eco transvaginal', 'Consulta', 'Salud'],
  ['Citología', 'Frotis', 'Salud'],
  ['Cultivo de orina', 'Análisis', 'Salud'],
  ['Espermiograma', 'Análisis', 'Salud'],
  ['Banco de semen', 'Fertilidad', 'Salud'],
  ['Donante anónimo', 'Fertilidad', 'Salud'],
  ['Fertilización in vitro', 'Fertilidad', 'Salud'],
  ['Inseminación', 'Fertilidad', 'Salud'],
  ['Heteronorma', 'Coño', 'Orientación'],
  ['Salir del armario', 'Coño', 'Orientación'],
  ['Orgullo', 'Coño', 'Orientación'],
  ['Transformista', 'Actuación', 'Cultura'],
  ['Baile de bola', 'Coño', 'Cultura'],
  ['Comunidad fetiche', 'Coño', 'Cultura'],
  ['Quedada fetiche', 'Coño', 'Cultura'],
  ['Fiesta en mazmorra', 'Coño', 'Cultura'],
  ['Fiesta sexual', 'Coño', 'Cultura'],
  ['Taller de consentimiento', 'Coño', 'Cultura'],
  ['Sexualidad positiva', 'Cultura', 'Cultura'],
  ['Aceptar el cuerpo en la cama', 'Aceptación', 'Cultura'],
  ['Inseguridad con el cuerpo', 'Nervios', 'Ambiente picante'],
  ['Luz apagada por vergüenza', 'Nervios', 'Ambiente picante'],
  ['Camiseta puesta en la cama', 'Nervios', 'Ambiente picante'],
  ['Compararse con el porno', 'Trampa', 'Ambiente picante'],
  ['Expectativas de porno', 'Irreal', 'Ambiente picante'],
  ['Duración de película porno', 'Ficción', 'Ambiente picante'],
  ['Actores que no paran', 'Ficción', 'Ambiente picante'],
  ['Guion ridículo de porno', 'Repartidor de pizza', 'Medios'],
  ['Fontanero porno', 'Cliché', 'Medios'],
  ['Hermanastra porno', 'Cliché', 'Medios'],
  ['Profe particular porno', 'Cliché', 'Medios'],
  ['Masajista porno', 'Cliché', 'Medios'],
  ['Vecina que pide sal', 'Cliché', 'Medios'],
  ['Repartidor de pizza', 'Cliché', 'Medios'],
  ['Sofá de prueba', 'Cliché', 'Medios'],
  ['Cámara subjetiva', 'Coño', 'Medios'],
  ['Casero', 'Coño', 'Medios'],
  ['Casero', 'Coño', 'Medios'],
  ['Compilatorio de acabadas dentro', 'Coño', 'Medios'],
  ['Anime erótico', 'Coño', 'Medios'],
  ['Regla treinta y cuatro', 'Internet', 'Medios'],
  ['Contenido adulto', 'Etiqueta', 'Ambiente picante'],
  ['Anticipo de desnudos', 'Meme', 'Ambiente picante'],
  ['Foto provocadora', 'Coño', 'Redes'],
  ['Foto en lencería', 'Redes', 'Redes'],
  ['Historia destacada caliente', 'Redes', 'Redes'],
  ['Círculo cercano +18', 'Red social', 'Redes'],
  ['Canal de mensajería caliente', 'Coño', 'Ambiente picante'],
  ['Pack filtrado', 'Filtración', 'Ambiente picante'],
  ['Suscripción mensual', 'Plataforma de fans', 'Ambiente picante'],
  ['Pagar propinas', 'Coño', 'Ambiente picante'],
  ['Vídeo por encargo', 'Coño', 'Ambiente picante'],
  ['Valorar la polla', 'Valoración', 'Ambiente picante'],
  ['Instrucciones para pajearse', 'Coño', 'Ambiente picante'],
  ['Fetiche de tragar', 'Coño', 'Ambiente picante'],
  ['Humillación del tamaño', 'Coño', 'Ambiente picante'],
  ['Dominación financiera', 'Dinero', 'Ambiente picante'],
  ['Dominadora financiera', 'Dominatrix económica', 'Ambiente picante'],
  ['Tributo', 'Pago', 'Ambiente picante'],
  ['Vaciar la cartera', 'Dinero', 'Ambiente picante'],
  ['Custodia de la llave', 'Castidad', 'Sadomaso'],
  ['Jaula de castidad', 'Coño', 'Sadomaso'],
  ['Control del orgasmo', 'Coño', 'Sadomaso'],
  ['Negación del orgasmo', 'Coño', 'Sadomaso'],
  ['Provocación y negación', 'Coño', 'Sadomaso'],
  ['Calentar por dentro', 'Coño', 'Ambiente picante'],
  ['Fetiche de fecundación', 'Fantasía de embarazo', 'Ambiente picante'],
  ['Fetiche de embarazo', 'Fantasía de embarazo', 'Ambiente picante'],
  ['Fetiche de lactancia', 'Leche', 'Ambiente picante'],
  ['Agonizar con ganas de mear', 'Coño', 'Ambiente picante'],
  ['Lluvia dorada', 'Orina', 'Ambiente picante'],
  ['Coprofilia', 'Heces', 'Ambiente picante'],
  ['Juego con sangre', 'Coño', 'Sadomaso'],
  ['Juego con cuchillo', 'Coño', 'Sadomaso'],
  ['Juego con fuego', 'Coño', 'Sadomaso'],
  ['Juego con agujas', 'Coño', 'Sadomaso'],
  ['Juego de asfixxia', 'Coño', 'Sadomaso'],
  ['Agarre del cuello', 'Coño', 'Sadomaso'],
  ['Tirones de pelo', 'Coño', 'Ambiente picante'],
  ['Escupir', 'Coño', 'Ambiente picante'],
  ['Cachetear', 'Coño', 'Sadomaso'],
  ['Cachete en la cara', 'Coño', 'Sadomaso'],
  ['Arcadas', 'Náuseas', 'Sexo oral'],
  ['Babeo', 'Coño', 'Sexo oral'],
  ['Mamada babosa', 'Babeo', 'Sexo oral'],
  ['Hasta el fondo', 'Coño', 'Ambiente picante'],
  ['Golpes en los huevos', 'Patada', 'Ambiente picante'],
  ['Tortura genital', 'Coño', 'Sadomaso'],
  ['Banco de fantasías', 'Recuerdos', 'Solo'],
  ['Fantasía recurrente', 'Mente', 'Solo'],
  ['Historial de incógnito', 'Navegador', 'Ambiente picante'],
  ['Borrar historial', 'Navegador', 'Ambiente picante'],
  ['Navegación privada por vergüenza', 'Internet', 'Ambiente picante'],
  ['Cuenta alternativa', 'Secundaria', 'Ambiente picante'],
  ['Cuenta anónima', 'Anónimo', 'Ambiente picante'],
  ['Foro adulto', 'Coño', 'Ambiente picante'],
  ['Servidor adulto', 'Coño', 'Ambiente picante'],
  ['Chat de voz caliente', 'Audio', 'Ambiente picante'],
  ['Susurros eróticos', 'Audio', 'Ambiente picante'],
  ['Audio caliente', 'Nota de voz', 'Móvil'],
  ['Nota de voz jadeando', 'Audio', 'Móvil'],
  ['Buenos días con foto', 'Desnudo matutino', 'Móvil'],
  ['Buenas noches con audio', 'Sexteo', 'Móvil'],
  ['Emoji de berenjena', 'Símbolo', 'Móvil'],
  ['Emoji de melocotón', 'Símbolo', 'Móvil'],
  ['Emoji de gotas', 'Símbolo', 'Móvil'],
  ['Emoji de chile', 'Símbolo', 'Móvil'],
  ['Texto sugerente', 'Indirecta', 'Móvil'],
  ['Indirectas en historias', 'Celos', 'Redes'],
  ['Canción dedicada en historias', 'Ligue', 'Redes'],
  ['Publicar y borrar', 'Inseguridad', 'Redes'],
  ['Bloqueo suave', 'Coño', 'Redes'],
  ['Bloqueo total', 'Coño', 'Redes'],
  ['Silenciar historias', 'Coño', 'Redes'],
  ['Círculo cercano sin ti', 'Excluido', 'Redes'],
];

export const ADULT_WORDS: readonly string[] = ADULT_WORD_PAIRS.map(([w]) => w);
