import type { WordPair } from './words.js';

/**
 * Pack +18 para Mr White / Heads Up / Just One.
 * Solo se usa si el jugador activa «Versión adultos».
 */
export const ADULT_WORD_PAIRS: readonly WordPair[] = [
  ['Coño', 'Coña', 'Taco español'],
  ['Joder', 'Jodido', 'Taco'],
  ['Mierda', 'Caca', 'Excremento'],
  ['Cabrón', 'Cabronazo', 'Insulto'],
  ['Puta', 'Putón', 'Insulto'],
  ['Gilipollas', 'Idiota', 'Insulto'],
  ['Hostia', 'Ostia', 'Taco'],
  ['Pollas', 'Pene', 'Genital'],
  ['Cojones', 'Huevos', 'Genital'],
  ['Tetas', 'Pechos', 'Cuerpo'],
  ['Culo', 'Trasero', 'Cuerpo'],
  ['Follar', 'Copular', 'Sexo'],
  ['Correrse', 'Acabar', 'Sexo'],
  ['Mamada', 'Felación', 'Sexo oral'],
  ['Ligar', 'Lío pasajero', 'Noche'],
  ['Resaca', 'Migraña', 'Mañana después'],
  ['Porno', 'Porno', 'Internet'],
  ['Baile erótico', 'Baile erótico', 'Local nocturno'],
  ['Orgasmo', 'Clímax', 'Sexo'],
  ['Preservativo', 'Condón', 'Protección'],
  ['Pastilla azul', 'Pastilla azul', 'Farmacia'],
  ['Sexo oral', 'Chupada', 'Sexo'],
  ['Sexo anal', 'Por detrás', 'Sexo'],
  ['Tanga', 'Hilo', 'Ropa interior'],
  ['Sujetador', 'Sujetador', 'Ropa interior'],
  ['Lencería', 'Picardías', 'Ropa'],
  ['Consolador', 'Consolador', 'Juguete'],
  ['Vibrador', 'Masajeador', 'Juguete'],
  ['Sado', 'Sadomaso', 'Fetiche'],
  ['Fetiche', 'Fetiche', 'Deseo'],
  ['Intercambio de parejas', 'Intercambio', 'Pareja'],
  ['Infidelidad', 'Cuernos', 'Pareja'],
  ['Cornudo', 'Engañado', 'Pareja'],
  ['Amigovio', 'Follamigo', 'Relación'],
  ['Ligoteo', 'Coqueteo', 'Bar'],
  ['Borracho', 'Pedo', 'Alcohol'],
  ['Pedo', 'Tirarse un pedo', 'Gases'],
  ['Eructo', 'Regüeldo', 'Gases'],
  ['Vomitar', 'Devolver', 'Resaca'],
  ['Meada', 'Orina', 'Baño'],
  ['Cagar', 'Defecar', 'Baño'],
  ['Peo', 'Flatulencia', 'Gases'],
  ['Chorra', 'Polla', 'Genital'],
  ['Chocho', 'Vagina', 'Genital'],
  ['Pechochos', 'Tetas', 'Cuerpo'],
  ['Nalgas', 'Culo', 'Cuerpo'],
  ['Beso negro', 'Beso negro', 'Sexo oral'],
  ['Triolismo', 'Trío', 'Sexo'],
  ['Sexo grupal', 'Grupal', 'Sexo'],
  ['Orgía', 'Fiesta sexual', 'Sexo'],
  ['Mirón', 'Mirón', 'Fetiche'],
  ['Exhibicionista', 'Mirón al revés', 'Fetiche'],
  ['Sexteo', 'Desnudos', 'Móvil'],
  ['Desnudos', 'Fotos calientes', 'Móvil'],
  ['Plataforma de fans', 'Contenido +18', 'Internet'],
  ['App de ligue', 'Ligues', 'App'],
  ['Dejar en visto', 'Desaparición', 'Ligue'],
  ['Zona de amigos', 'Amigo', 'Ligue'],
  ['Zorra', 'Puta', 'Insulto'],
  ['Hijo de puta', 'Insulto fuerte', 'Insulto'],
  ['Capullo', 'Gilipollas', 'Insulto'],
  ['Imbécil', 'Idiota', 'Insulto'],
  ['Lameculos', 'Pelota', 'Insulto'],
  ['Mamón', 'Chupóptero', 'Insulto'],
  ['Tontolaba', 'Idiota', 'Insulto'],
  ['Pajero', 'Vicioso', 'Insulto'],
  ['Calentorro', 'Fogonazo', 'Deseo'],
  ['Empollón', 'Calentón', 'Deseo'],
  ['Corrida', 'Eyaculación', 'Sexo'],
  ['Lubricante', 'Gel', 'Sexo'],
  ['Postura del perrito', 'A cuatro', 'Sexo'],
  ['Misionero', 'Clásico', 'Sexo'],
  ['A caballo', 'A horcajadas', 'Sexo'],
  ['Rapidito', 'Rapidito', 'Sexo'],
  ['Rapidito en el baño', 'Rapidito', 'Fiesta'],
  ['Fiesta de madrugada', 'Después de fiesta', 'Noche'],
  ['Límite', 'Palabra de seguridad', 'Sadomaso'],
  ['Azotes', 'Nalgadas', 'Sadomaso'],
  ['Esposas', 'Ataduras', 'Sadomaso'],
  ['Antifaz', 'Máscara', 'Sadomaso'],
  ['Látigo', 'Fusta', 'Sadomaso'],
  ['Dominadora', 'Dominadora', 'Sadomaso'],
  ['Sumiso', 'Esclavo', 'Sadomaso'],
  ['Cornudo consentido', 'Cornudo consentido', 'Fetiche'],
  ['Esposa libre', 'Esposa libre', 'Fetiche'],
  ['Penetrar con arnés', 'Arnés', 'Fetiche'],
  ['Arnés', 'Arnés', 'Juguete'],
  ['Agujero del placer', 'Agujero', 'Fetiche'],
  ['Sexo en el coche', 'Coche', 'Exterior'],
  ['Sexo en público', 'En público', 'Riesgo'],
  ['Sexo en el avión', 'Avión', 'Riesgo'],
  ['Semen', 'Leche', 'Fluido'],
  ['Flujo', 'Lubricación', 'Cuerpo'],
  ['Clítoris', 'Punto G', 'Cuerpo'],
  ['Punto G', 'Placer', 'Cuerpo'],
  ['Próstata', 'Punto P', 'Cuerpo'],
  ['Testículos', 'Huevos', 'Genital'],
  ['Escroto', 'Saco', 'Genital'],
  ['Prepucio', 'Piel', 'Genital'],
  ['Labios', 'Vulva', 'Genital'],
  ['Pecho', 'Teta', 'Cuerpo'],
  ['Pezón', 'Pechuga', 'Cuerpo'],
  ['Ombligo', 'Piercing', 'Cuerpo'],
  ['Ingle', 'Zona baja', 'Cuerpo'],
  ['Entrepiemas', 'Muslos', 'Cuerpo'],
  ['Kama sutra', 'Posturas', 'Libro'],
  ['Cincuenta sombras', 'Romance erótico', 'Libro'],
  ['Revista erótica', 'Revista', 'Medios'],
  ['Revista erótica', 'Revista', 'Medios'],
  ['Burdel', 'Prostíbulo', 'Local'],
  ['Puticlub', 'Club', 'Local'],
  ['Sauna gay', 'Baños', 'Local'],
  ['Cuarto oscuro', 'Cuarto oscuro', 'Local'],
  ['Agujero del placer', 'Agujero', 'Local'],
  ['Juguete a distancia', 'App de juguete', 'Tecnología'],
  ['Modelo de cámara', 'Emisor en directo +18', 'Internet'],
  ['Patrocinador', 'Patrocinador', 'Relación'],
  ['Mantenida', 'Mantenida', 'Relación'],
  ['Acompañante de pago', 'Acompañante', 'Trabajo'],
  ['Gigoló', 'Acompañante', 'Trabajo'],
  ['Prostituta', 'Trabajador sexual', 'Trabajo'],
  ['Putero', 'Cliente', 'Local'],
  ['Chulo', 'Proxeneta', 'Calle'],
  ['Folladero', 'Garito', 'Local'],
  ['Ligue de una noche', 'Una noche', 'Fiesta'],
  ['Polvo', 'Follada', 'Sexo'],
  ['Echar un polvo', 'Follar', 'Sexo'],
  ['Paja', 'Masturbación', 'Solo'],
  ['Masturbarse', 'Tocarse', 'Solo'],
  ['Sueño húmedo', 'Ensueño', 'Noche'],
  ['Calentura', 'Lujuria', 'Deseo'],
  ['Morbo', 'Excitación', 'Deseo'],
  ['Guarrada', 'Guarrada', 'Sexo'],
  ['Guarro', 'Cerdo', 'Insulto'],
  ['Cerda', 'Zorra', 'Insulto'],
  ['Bisexual', 'Bisexual', 'Orientación'],
  ['Pansexual', 'Sin etiqueta', 'Orientación'],
  ['Poliamor', 'Varias parejas', 'Relación'],
  ['Pareja abierta', 'Pareja abierta', 'Relación'],
  ['Cornuda consentida', 'Cornuda', 'Fetiche'],
  ['Humillación', 'Degradación', 'Sadomaso'],
  ['Nalgadas', 'Azotes', 'Sadomaso'],
  ['Juego con cera', 'Cera', 'Sadomaso'],
  ['Juego con hielo', 'Hielo', 'Sadomaso'],
  ['Juego de rol', 'Disfraz', 'Fantasía'],
  ['Juego de enfermera', 'Enfermera', 'Fantasía'],
  ['Fantasía del jefe', 'Jefe', 'Fantasía'],
  ['Fantasía del profe', 'Profe', 'Fantasía'],
  ['Uniforme sexy', 'Disfraz', 'Ropa'],
  ['Medias de red', 'Lencería', 'Ropa'],
  ['Portaligas', 'Lencería', 'Ropa'],
  ['Body abierto', 'Picardías', 'Ropa'],
  ['Camisón corto', 'Camisón', 'Ropa'],
  ['Anillo para el pene', 'Anillo', 'Juguete'],
  ['Tapón anal', 'Tapón', 'Juguete'],
  ['Bolas anales', 'Bolas anales', 'Juguete'],
  ['Masturbador', 'Masturbador', 'Juguete'],
  ['Máquina sexual', 'Máquina', 'Juguete'],
  ['Vapores', 'Amilo', 'Fiesta'],
  ['Éxtasis', 'Pastilla', 'Fiesta'],
  ['Porro', 'Canuto', 'Fiesta'],
  ['Pipa de agua', 'Pipa', 'Fiesta'],
  ['Chupito', 'Trago', 'Bar'],
  ['Cubata', 'Combinado', 'Bar'],
  ['Combinado hasta morir', 'Borrachera', 'Bar'],
  ['Despedida de soltero', 'Despedida', 'Fiesta'],
  ['Bailarina erótica', 'Baile erótico', 'Fiesta'],
  ['Baile privado', 'Baile privado', 'Local'],
  ['Baile de barra', 'Barra', 'Baile'],
  ['Perreo', 'Perreo', 'Baile'],
  ['Perreo intenso', 'Reggaetón', 'Baile'],
  ['Beso con lengua', 'Beso con lengua', 'Beso'],
  ['Morreo', 'Frenazo', 'Beso'],
  ['Peto', 'Manoseo', 'Manos'],
  ['Mano inocente', 'Debajo de la ropa', 'Manos'],
  ['Dedos', 'Penetración digital', 'Manos'],
  ['Sesenta y nueve', '69', 'Sexo oral'],
  ['Garganta profunda', 'Garganta profunda', 'Sexo oral'],
  ['Acabada en la cara', 'Acabada en cara', 'Sexo'],
  ['Acabada dentro', 'Dentro', 'Sexo'],
  ['Sacar fuera', 'Fuera', 'Sexo'],
  ['Sin condón', 'Sin condón', 'Riesgo'],
  ['Prueba de embarazo', 'Prueba', 'Farmacia'],
  ['Pastilla del día después', 'Emergencia', 'Farmacia'],
  ['Infección sexual', 'Enfermedad', 'Salud'],
  ['Herpes', 'Llaga', 'Salud'],
  ['Candidiasis', 'Hongos', 'Salud'],
  ['Hemorroides', 'Almorranas', 'Salud'],
  ['Estreñimiento', 'Tapón', 'Baño'],
  ['Diarrea', 'Cagalera', 'Baño'],
  ['Estreñido', 'Aprieto', 'Baño'],
  ['Lavativa', 'Enema', 'Baño'],
  ['Bidé', 'Lavado', 'Baño'],
  ['Orinal', 'Orinal', 'Baño'],
  ['Cagada monumental', 'Lío', 'Error'],
  ['La cagaste', 'La liastes', 'Error'],
  ['Me la suda', 'Me importa un pepino', 'Desprecio'],
  ['Me importa una mierda', 'Pasotismo', 'Desprecio'],
  ['Que te jodan', 'Que te den', 'Insulto'],
  ['Vete a la mierda', 'Lárgate', 'Insulto'],
  ['Que te den por culo', 'Que te den', 'Insulto'],
  ['Tocapelotas', 'Pesado', 'Insulto'],
  ['Rompepelotas', 'Pesado', 'Insulto'],
  ['Huevón', 'Perezoso', 'Insulto'],
  ['Huevos revueltos', 'Desayuno', 'Doble sentido'],
  ['Chupar rueda', 'Ciclismo', 'Doble sentido'],
  ['Meter un gol', 'Fútbol', 'Doble sentido'],
  ['Entrar por detrás', 'Fútbol', 'Doble sentido'],
  ['Paliza', 'Golpiza', 'Bronca'],
  ['Hostia limpia', 'Puñetazo', 'Bronca'],
  ['Galleta', 'Bofetada', 'Bronca'],
  ['Leñazo', 'Golpe', 'Bronca'],
  ['Coñazo', 'Pesadez', 'Insulto'],
  ['Jodón', 'Pesado', 'Insulto'],
  ['Mierdoso', 'Asqueroso', 'Insulto'],
  ['Cabronada', 'Faena', 'Insulto'],
  ['Putada', 'Faena', 'Insulto'],
  ['Gilipollez', 'Tontería', 'Insulto'],
  ['Hostión', 'Golpe', 'Insulto'],
  ['Pollazo', 'Golpe', 'Insulto'],
  ['Cojonudo', 'Genial', 'Taco positivo'],
  ['De puta madre', 'Genial', 'Taco positivo'],
  ['La hostia', 'Brutal', 'Taco positivo'],
  ['Flipante', 'Alucinante', 'Taco positivo'],
  ['Me cago en todo', 'Cabreo', 'Taco'],
  ['Me cago en la leche', 'Cabreo', 'Taco'],
  ['Me cago en Dios', 'Cabreo', 'Taco'],
  ['Leche', 'Semen', 'Doble sentido'],
  ['Crema', 'Semen', 'Doble sentido'],
  ['Nata', 'Semen', 'Doble sentido'],
  ['Chorro', 'Eyaculación', 'Sexo'],
  ['Chorrito', 'Eyaculación', 'Sexo'],
  ['Acabar dentro', 'Acabada dentro', 'Sexo'],
  ['Acabar fuera', 'Sacar fuera', 'Sexo'],
  ['Sin condón', 'Sin condón', 'Riesgo'],
  ['Con condón', 'Condón', 'Protección'],
  ['Forro', 'Preservativo', 'Protección'],
  ['Goma', 'Condón', 'Protección'],
  ['Diafragma', 'Método', 'Protección'],
  ['Píldora', 'Anticonceptivo', 'Farmacia'],
  ['Marcha atrás', 'Marcha atrás', 'Riesgo'],
  ['Calcular días', 'Ritmo', 'Riesgo'],
  ['Pastilla abortiva', 'Farmacia', 'Salud'],
  ['Ecografía', 'Embarazo', 'Salud'],
  ['Triple prueba', 'Infección sexual', 'Salud'],
  ['Serología', 'Análisis', 'Salud'],
  ['Vacuna del papiloma', 'Prevención', 'Salud'],
  ['Prevención del VIH', 'Prevención', 'Salud'],
  ['Urgencia del VIH', 'Emergencia', 'Salud'],
  ['Candidiasis', 'Hongos', 'Salud'],
  ['Cistitis', 'Infección', 'Salud'],
  ['Prostatitis', 'Infección', 'Salud'],
  ['Fimosis', 'Prepucio', 'Salud'],
  ['Frenillo', 'Genital', 'Salud'],
  ['Circuncisión', 'Cirugía', 'Salud'],
  ['Vasectomía', 'Cirugía', 'Salud'],
  ['Ligadura', 'Cirugía', 'Salud'],
  ['Implante anticonceptivo', 'Brazo', 'Farmacia'],
  ['Anticonceptivo interno', 'Anticonceptivo', 'Farmacia'],
  ['Anillo vaginal', 'Anticonceptivo', 'Farmacia'],
  ['Parche anticonceptivo', 'Hormonas', 'Farmacia'],
  ['Gel estimulante', 'Lubricante', 'Juguete'],
  ['Aceite de masaje', 'Masaje', 'Sexo'],
  ['Pluma de cosquillas', 'Juego', 'Sexo'],
  ['Venda', 'Antifaz', 'Sadomaso'],
  ['Mordaza', 'Bola', 'Sadomaso'],
  ['Collar de sumisión', 'Collar', 'Sadomaso'],
  ['Correa', 'Paseo', 'Sadomaso'],
  ['Paleta', 'Paleta', 'Sadomaso'],
  ['Fusta', 'Látigo corto', 'Sadomaso'],
  ['Fusta corta', 'Látigo', 'Sadomaso'],
  ['Nalgada seca', 'Azote', 'Sadomaso'],
  ['Marcas', 'Moretones', 'Sadomaso'],
  ['Cuidados posteriores', 'Cuidados', 'Sadomaso'],
  ['Negociación', 'Límites', 'Sadomaso'],
  ['Semáforo', 'Límites', 'Sadomaso'],
  ['Rojo', 'Parar', 'Sadomaso'],
  ['Ámbar', 'Despacio', 'Sadomaso'],
  ['Verde', 'Seguir', 'Sadomaso'],
  ['Juego de golpes', 'Golpes', 'Sadomaso'],
  ['Ataduras', 'Ataduras', 'Sadomaso'],
  ['Atadura japonesa', 'Cuerda', 'Sadomaso'],
  ['Cuerda japonesa', 'Cuerda', 'Sadomaso'],
  ['Suspensión', 'Colgado', 'Sadomaso'],
  ['Privación sensorial', 'Privación', 'Sadomaso'],
  ['Juego de temperatura', 'Temperatura', 'Sadomaso'],
  ['Juego eléctrico', 'Descargas', 'Sadomaso'],
  ['Juego de mascota', 'Animalito', 'Sadomaso'],
  ['Fetiche de papi', 'Rol', 'Sadomaso'],
  ['Juego de edad', 'Rol', 'Sadomaso'],
  ['Juego médico', 'Clínica', 'Sadomaso'],
  ['No consentimiento pactado', 'Consentimiento', 'Sadomaso'],
  ['Fetiche de elogios', 'Elogios', 'Sadomaso'],
  ['Degradación', 'Insultos eróticos', 'Sadomaso'],
  ['Disponible siempre', 'Disponible', 'Fetiche'],
  ['Juego en público', 'En público', 'Fetiche'],
  ['Sexo en el coche', 'Coche', 'Fetiche'],
  ['Balcón', 'Exterior', 'Fetiche'],
  ['Ascensor', 'Riesgo', 'Fetiche'],
  ['Probador', 'Tienda', 'Fetiche'],
  ['Cine vacío', 'Sala', 'Fetiche'],
  ['Playa nudista', 'Playa', 'Exterior'],
  ['Camping salvaje', 'Tienda', 'Exterior'],
  ['Jacuzzi privado', 'Agua', 'Exterior'],
  ['Ducha juntos', 'Baño', 'Sexo'],
  ['Baño del bar', 'Rapidito', 'Fiesta'],
  ['Terraza de fiesta', 'Exterior', 'Fiesta'],
  ['Trastero', 'Rincón', 'Fiesta'],
  ['Aparcamiento', 'Coche', 'Fiesta'],
  ['VTC caliente', 'Vuelta', 'Fiesta'],
  ['Taxi de madrugada', 'Vuelta', 'Fiesta'],
  ['Resacón histórico', 'Resaca', 'Fiesta'],
  ['Mareo de alcohol', 'Resaca', 'Fiesta'],
  ['Boca de algodón', 'Resaca', 'Fiesta'],
  ['Dolor de cabeza', 'Resaca', 'Fiesta'],
  ['Agua con gas y paracetamol', 'Resaca', 'Fiesta'],
  ['Kebab de madrugada', 'Resaca', 'Fiesta'],
  ['Pizza a las 4', 'Resaca', 'Fiesta'],
  ['Tabaco de mentira', 'Porro', 'Fiesta'],
  ['Porro mal liado', 'Canuto', 'Fiesta'],
  ['Humazo', 'Humo', 'Fiesta'],
  ['Colocón', 'Colgado', 'Fiesta'],
  ['Bajón', 'Caída', 'Fiesta'],
  ['Subidón', 'Éxtasis', 'Fiesta'],
  ['Pastilleo', 'Pastillas', 'Fiesta'],
  ['Raya', 'Coca', 'Fiesta'],
  ['Farlopa', 'Coca', 'Fiesta'],
  ['Chute', 'Inyección', 'Fiesta'],
  ['Ketamina', 'Keta', 'Fiesta'],
  ['Éxtasis', 'Pastilla', 'Fiesta'],
  ['Setas', 'Alucinógenos', 'Fiesta'],
  ['Ácido', 'Viaje alucinógeno', 'Fiesta'],
  ['G de fiesta', 'Droga líquida', 'Fiesta'],
  ['Popper en la disco', 'Vapores', 'Fiesta'],
  ['Esnifar', 'Esnifar', 'Fiesta'],
  ['Camello', 'Camello', 'Fiesta'],
  ['Camello del barrio', 'Camello', 'Fiesta'],
  ['Trapicheo', 'Venta', 'Fiesta'],
  ['Colocarse', 'Drogarse', 'Fiesta'],
  ['Ir puesto', 'Colocado', 'Fiesta'],
  ['Ir ciego', 'Borracho', 'Fiesta'],
  ['Ir petao', 'Borracho', 'Fiesta'],
  ['Ir hasta el culo', 'Borracho', 'Fiesta'],
  ['Blanco total', 'Borracho', 'Fiesta'],
  ['Apagón etílico', 'Apagón etílico', 'Fiesta'],
  ['No me acuerdo de nada', 'Apagón etílico', 'Fiesta'],
  ['Historias vergonzosas', 'Resaca social', 'Fiesta'],
  ['Beso a desconocido', 'Ligue', 'Fiesta'],
  ['Ligue de baño', 'Rapidito', 'Fiesta'],
  ['Número falso', 'Dejar en visto', 'Ligue'],
  ['Dejar en visto', 'Dejar en visto', 'Ligue'],
  ['Dar migajas', 'Migajas', 'Ligue'],
  ['Orbitar', 'Orbitar', 'Ligue'],
  ['Casi pareja', 'Casi pareja', 'Ligue'],
  ['Pareja a medias en redes', 'Pareja en redes', 'Ligue'],
  ['Pareja pública en redes', 'Pareja pública', 'Ligue'],
  ['Tener de reserva', 'Banquillo', 'Ligue'],
  ['Vuelve el ex', 'Vuelve el ex', 'Ligue'],
  ['Colchón afectivo', 'Colchón', 'Ligue'],
  ['Otras apps a la vez', 'Otras apps', 'Ligue'],
  ['Perfil falso', 'Perfil falso', 'Ligue'],
  ['Bombardeo afectivo', 'Bombardeo', 'Ligue'],
  ['Manipulación afectiva', 'Manipulación', 'Ligue'],
  ['Halago hiriente', 'Pique', 'Ligue'],
  ['Ligón de manual', 'Ligón de manual', 'Ligue'],
  ['Primer mensaje', 'Primer mensaje', 'App'],
  ['Deslizar a la derecha', 'Me gusta', 'App'],
  ['Deslizar a la izquierda', 'Paso', 'App'],
  ['Súper me gusta', 'Destacado', 'App'],
  ['Coincidencia', 'Coincidencia', 'App'],
  ['Quitar coincidencia', 'Borrar', 'App'],
  ['Biografía falsa', 'Perfil', 'App'],
  ['Foto de hace 10 años', 'Perfil', 'App'],
  ['Foto con filtro', 'Perfil', 'App'],
  ['Foto en la playa', 'Perfil', 'App'],
  ['Foto del gimnasio', 'Perfil', 'App'],
  ['Foto con el ex recortado', 'Perfil', 'App'],
  ['Quedada para un café', 'Primera cita', 'Ligue'],
  ['Quedada para un vermú', 'Primera cita', 'Ligue'],
  ['Quedada en casa', 'Ver una serie y follar', 'Ligue'],
  ['Ver una serie y follar', 'Follar', 'Ligue'],
  ['Ver una serie', 'Excusa', 'Ligue'],
  ['Masaje con final feliz', 'Masaje', 'Sexo'],
  ['Final feliz', 'Acabar', 'Sexo'],
  ['Masaje prostático', 'Punto P', 'Sexo'],
  ['Estimulación anal', 'Tapón anal', 'Sexo'],
  ['Beso negro', 'Beso negro', 'Sexo oral'],
  ['Sentarse en la cara', 'Sentarse en la cara', 'Sexo oral'],
  ['Sentarse en la cara', 'Sentarse en la cara', 'Sexo oral'],
  ['Paja con la mano', 'Paja con mano', 'Sexo'],
  ['Paja con los pies', 'Paja con pies', 'Fetiche'],
  ['Paja con tetas', 'Paja con tetas', 'Sexo'],
  ['Paja con tetas', 'Paja con tetas', 'Sexo'],
  ['Entre muslos', 'Entre muslos', 'Sexo'],
  ['Frotarse vestidos', 'Frotarse', 'Sexo'],
  ['Frotamiento', 'Frotarse', 'Sexo'],
  ['Llevar al límite', 'Al límite', 'Sexo'],
  ['Orgasmo a medias', 'Orgasmo a medias', 'Sexo'],
  ['Varios orgasmos', 'Varios', 'Sexo'],
  ['Chorrito', 'Chorrito', 'Sexo'],
  ['Eyaculación femenina', 'Chorrito', 'Sexo'],
  ['Orgasmo prostático', 'Punto P', 'Sexo'],
  ['Juego con pezones', 'Pezones', 'Sexo'],
  ['Juego con tetas', 'Tetas', 'Sexo'],
  ['Hablar guarro', 'Hablar guarro', 'Sexo'],
  ['Sexo telefónico', 'Sexo telefónico', 'Sexo'],
  ['Videollamada caliente', 'Videollamada', 'Sexo'],
  ['Cámara a cámara', 'Cámara', 'Internet'],
  ['Menú de propinas', 'Propina', 'Internet'],
  ['Espectáculo privado', 'Espectáculo privado', 'Internet'],
  ['Foto de polla', 'Foto de polla', 'Móvil'],
  ['Foto íntima', 'Foto íntima', 'Móvil'],
  ['Filtración de desnudos', 'Filtración', 'Internet'],
  ['Porno de venganza', 'Venganza', 'Internet'],
  ['Consentimiento explícito', 'Sí claro', 'Ética'],
  ['Retirar el consentimiento', 'Parar', 'Ética'],
  ['Preguntar si todo va bien', '¿Todo bien?', 'Ética'],
  ['Sobriedad y consentimiento', 'Límites', 'Ética'],
  ['No es no', 'Límite', 'Ética'],
  ['Solo sí es sí', 'Consentimiento', 'Ética'],
  ['Acoso callejero', 'Piropo basura', 'Calle'],
  ['Mano en el culo', 'Agarrón', 'Calle'],
  ['Mirada lasciva', 'Mirón', 'Calle'],
  ['Frotarse en el metro', 'Metro', 'Calle'],
  ['Debajo de la falda', 'Debajo de la falda', 'Calle'],
  ['Voyeurismo no consentido', 'Mirón', 'Calle'],
  ['Exhibición', 'Mostrar genitales', 'Calle'],
  ['Enseñar el culo', 'Mostrar culo', 'Calle'],
  ['Correr desnudo', 'Correr desnudo', 'Calle'],
  ['Topless playa', 'Pechos al aire', 'Playa'],
  ['Desnudo integral', 'Nudismo', 'Playa'],
  ['Bronceado de culo', 'Marcas', 'Playa'],
  ['Crema solar en zonas íntimas', 'Playa', 'Playa'],
  ['Pelo púbico', 'Vello', 'Cuerpo'],
  ['Depilación brasileña', 'Cera', 'Cuerpo'],
  ['Depilación total', 'Cera total', 'Cuerpo'],
  ['Franja de vello', 'Franja', 'Cuerpo'],
  ['Monte de Venus', 'Monte', 'Cuerpo'],
  ['Afeitado íntimo', 'Cuchilla', 'Cuerpo'],
  ['Irritación de cera', 'Rojo', 'Cuerpo'],
  ['Foliculitis', 'Granos', 'Cuerpo'],
  ['Estrías', 'Marcas', 'Cuerpo'],
  ['Celulitis', 'Piel de naranja', 'Cuerpo'],
  ['Barriga cervecera', 'Curro', 'Cuerpo'],
  ['Camino de vello', 'Camino de vello', 'Cuerpo'],
  ['Vello del pecho', 'Pecho', 'Cuerpo'],
  ['Sisas', 'Axilas', 'Cuerpo'],
  ['Hedor a sexo', 'Olor', 'Cuerpo'],
  ['Aliento a alcohol y sexo', 'Mañana', 'Resaca'],
  ['Sábana manchada', 'Lavadora', 'Sexo'],
  ['Toalla de emergencia', 'Baño', 'Sexo'],
  ['Papel higiénico impropio', 'Baño', 'Sexo'],
  ['Ducha fría después', 'Bajón', 'Sexo'],
  ['Cigarro postcoital', 'Cliché', 'Sexo'],
  ['La pequeña muerte', 'Orgasmo', 'Sexo'],
  ['Mirarse a los ojos', 'Intimidad', 'Sexo'],
  ['Risa nerviosa en la cama', 'Torpeza', 'Sexo'],
  ['Diente contra diente', 'Beso torpe', 'Beso'],
  ['Ortodoncia al besar', 'Beso', 'Beso'],
  ['Babeo excesivo', 'Beso', 'Beso'],
  ['Chupar el cuello', 'Chupetón', 'Beso'],
  ['Chupetón visible', 'Moratón', 'Beso'],
  ['Arañazos en la espalda', 'Marcas', 'Sexo'],
  ['Mordisco en el hombro', 'Marcas', 'Sexo'],
  ['Pelo agarrado', 'Jalón', 'Sexo'],
  ['Cachete en el culo', 'Nalgada', 'Sexo'],
  ['Empujón rítmico', 'Follar', 'Sexo'],
  ['Cama que cruje', 'Ruido', 'Sexo'],
  ['Vecinos escuchando', 'Ruido', 'Sexo'],
  ['Paredes de papel', 'Ruido', 'Sexo'],
  ['Gritos ahogados', 'Almohada', 'Sexo'],
  ['Morder la almohada', 'Silencio', 'Sexo'],
  ['Lista de canciones sexy', 'Música', 'Sexo'],
  ['Luz baja', 'Ambiente', 'Sexo'],
  ['Velas que huelen a vainilla', 'Ambiente', 'Sexo'],
  ['Sábana de satén', 'Cama', 'Sexo'],
  ['Lencería nueva', 'Ropa', 'Sexo'],
  ['Ropa interior del día a día', 'Ropa', 'Sexo'],
  ['Calzoncillos del abuelo', 'Ropa', 'Sexo'],
  ['Calcetines puestos', 'Torpeza', 'Sexo'],
  ['Sujetador imposible', 'Broche', 'Ropa'],
  ['Cremallera atascada', 'Ropa', 'Ropa'],
  ['Tirante que se rompe', 'Picardías', 'Ropa'],
  ['Tacones en la cama', 'Ropa', 'Sexo'],
  ['Camisa a medio abrir', 'Ropa', 'Sexo'],
  ['Vaqueros difíciles', 'Ropa', 'Sexo'],
  ['Cinturón a contrarreloj', 'Ropa', 'Sexo'],
  ['Condón al revés', 'Torpeza', 'Sexo'],
  ['Condón caducado', 'Riesgo', 'Sexo'],
  ['Condón que se rompe', 'Susto', 'Sexo'],
  ['Buscar el condón a oscuras', 'Torpeza', 'Sexo'],
  ['Cartera sin condón', 'Faena', 'Sexo'],
  ['Farmacia de guardia', 'Emergencia', 'Sexo'],
  ['Máquina expendedor de condones', 'Baño', 'Sexo'],
  ['Lubricante frío', 'Susto', 'Sexo'],
  ['Lubricante con sabor', 'Gel', 'Sexo'],
  ['Lubricante que pica', 'Gel', 'Sexo'],
  ['Aceite que rompe el látex', 'Error', 'Sexo'],
  ['Posición imposible', 'Kama sutra', 'Sexo'],
  ['Calambre en la pierna', 'Torpeza', 'Sexo'],
  ['Pierna dormida', 'Torpeza', 'Sexo'],
  ['Se sale', 'Torpeza', 'Sexo'],
  ['No entra', 'Torpeza', 'Sexo'],
  ['Demasiado seco', 'Lubricante', 'Sexo'],
  ['Demasiado rápido', 'Llevar al límite', 'Sexo'],
  ['Se te baja', 'Vergüenza', 'Sexo'],
  ['Ansiedad de rendimiento', 'Nervios', 'Sexo'],
  ['Fingir el orgasmo', 'Teatro', 'Sexo'],
  ['Preguntar ¿ya?', 'Torpeza', 'Sexo'],
  ['Mirar el móvil en la cama', 'Faena', 'Sexo'],
  ['Dormirse después de acabar', 'Clásico', 'Sexo'],
  ['Cucharita', 'Abrazo', 'Sexo'],
  ['Cucharota', 'Cucharita', 'Sexo'],
  ['Cucharita pequeña', 'Cucharita', 'Sexo'],
  ['Hablar del ex en la cama', 'Error', 'Sexo'],
  ['Decir el nombre equivocado', 'Horror', 'Sexo'],
  ['Reírse de un pedo', 'Torpeza', 'Sexo'],
  ['Pedo en pleno acto', 'Vergüenza', 'Sexo'],
  ['Ruidos intestinales', 'Vergüenza', 'Sexo'],
  ['Estómago vacío ruge', 'Vergüenza', 'Sexo'],
  ['Ir al baño a escondidas', 'Pausa', 'Sexo'],
  ['Lavarse los dientes antes', 'Higiene', 'Sexo'],
  ['Ducha previa', 'Higiene', 'Sexo'],
  ['Aliento a ajo', 'Faena', 'Beso'],
  ['Sudor de gimnasio', 'Olor', 'Cuerpo'],
  ['Colonia excesiva', 'Olor', 'Cuerpo'],
  ['Feromonas de bote', 'Colonia', 'Cuerpo'],
  ['Ropa interior limpia por si acaso', 'Previsión', 'Sexo'],
  ['Afeitarse por si acaso', 'Previsión', 'Sexo'],
  ['Sábanas limpias por si acaso', 'Previsión', 'Sexo'],
  ['Copas de más', 'Alcohol', 'Fiesta'],
  ['Valor de alcohol', 'Coraje', 'Fiesta'],
  ['Confesiones borrachas', 'Fiesta', 'Fiesta'],
  ['Bailar pegado', 'Perreo', 'Baile'],
  ['Manos en la cintura', 'Baile', 'Baile'],
  ['Frotar en la pista', 'Perreo', 'Baile'],
  ['Beso en la pista', 'Ligue', 'Fiesta'],
  ['Sacar a bailar', 'Ligue', 'Fiesta'],
  ['Invitar a chupitos', 'Ligue', 'Bar'],
  ['Pagar la ronda', 'Ligue', 'Bar'],
  ['Pedir el número', 'Ligue', 'Bar'],
  ['Red social en vez de número', 'Ligue', 'Bar'],
  ['Seguir en todas las redes', 'Acecho ligero', 'Ligue'],
  ['Espiar historias', 'Espiar', 'Ligue'],
  ['Ver la ubicación', 'Espiar', 'Ligue'],
  ['Preguntar a amigos comunes', 'Cotilleo', 'Ligue'],
  ['Cotillear el ex', 'Cotilleo', 'Ligue'],
  ['Comparar con el ex', 'Error', 'Relación'],
  ['Revisar el móvil', 'Celos', 'Relación'],
  ['Contraseña compartida', 'Confianza', 'Relación'],
  ['Celos en la discoteca', 'Bronca', 'Relación'],
  ['Bronca de madrugada', 'Pareja', 'Relación'],
  ['Sexo de reconciliación', 'Reconciliación', 'Sexo'],
  ['Sexo de despedida', 'Adiós', 'Sexo'],
  ['Sexo aburrido de sofá', 'Rutina', 'Sexo'],
  ['Rutina de siempre los viernes', 'Rutina', 'Sexo'],
  ['Calendario de ovulación', 'Apps', 'Relación'],
  ['App de ciclos', 'Regla', 'Salud'],
  ['Dolor menstrual', 'Regla', 'Salud'],
  ['Cólico bestial', 'Regla', 'Salud'],
  ['Tampones', 'Regla', 'Salud'],
  ['Compresa', 'Regla', 'Salud'],
  ['Copa menstrual', 'Regla', 'Salud'],
  ['Mancha en la sábana', 'Regla', 'Salud'],
  ['Sexo con la regla', 'Periodo', 'Sexo'],
  ['Toalla roja', 'Regla', 'Sexo'],
  ['Antojo absurdo', 'Embarazo', 'Relación'],
  ['Test de farmacia positivo', 'Susto', 'Salud'],
  ['Test de farmacia negativo', 'Alivio', 'Salud'],
  ['Retraso', 'Susto', 'Salud'],
  ['Síntomas raros', 'Susto', 'Salud'],
  ['Visita al ginecólogo', 'Consulta', 'Salud'],
  ['Visita al urólogo', 'Consulta', 'Salud'],
  ['Exploración íntima', 'Consulta', 'Salud'],
  ['Espéculo', 'Consulta', 'Salud'],
  ['Tacto rectal', 'Consulta', 'Salud'],
  ['Eco transvaginal', 'Consulta', 'Salud'],
  ['Citología', 'Frotis', 'Salud'],
  ['Cultivo de orina', 'Análisis', 'Salud'],
  ['Espermiograma', 'Análisis', 'Salud'],
  ['Banco de semen', 'Fertilidad', 'Salud'],
  ['Donante anónimo', 'Fertilidad', 'Salud'],
  ['Fertilización in vitro', 'Fertilidad', 'Salud'],
  ['Inseminación', 'Fertilidad', 'Salud'],
  ['Heteronorma', 'Norma', 'Orientación'],
  ['Salir del armario', 'Salir del armario', 'Orientación'],
  ['Orgullo', 'Orgullo', 'Orientación'],
  ['Transformista', 'Actuación', 'Cultura'],
  ['Baile de bola', 'Baile', 'Cultura'],
  ['Comunidad fetiche', 'Comunidad', 'Cultura'],
  ['Quedada fetiche', 'Quedada sadomaso', 'Cultura'],
  ['Fiesta en mazmorra', 'Fiesta sadomaso', 'Cultura'],
  ['Fiesta sexual', 'Fiesta sexual', 'Cultura'],
  ['Taller de consentimiento', 'Taller', 'Cultura'],
  ['Sexualidad positiva', 'Cultura', 'Cultura'],
  ['Aceptar el cuerpo en la cama', 'Aceptación', 'Cultura'],
  ['Inseguridad con el cuerpo', 'Nervios', 'Cuerpo'],
  ['Luz apagada por vergüenza', 'Nervios', 'Sexo'],
  ['Camiseta puesta en la cama', 'Nervios', 'Sexo'],
  ['Compararse con el porno', 'Trampa', 'Sexo'],
  ['Expectativas de porno', 'Irreal', 'Sexo'],
  ['Duración de película porno', 'Ficción', 'Sexo'],
  ['Actores que no paran', 'Ficción', 'Sexo'],
  ['Guion ridículo de porno', 'Repartidor de pizza', 'Medios'],
  ['Fontanero porno', 'Cliché', 'Medios'],
  ['Hermanastra porno', 'Cliché', 'Medios'],
  ['Profe particular porno', 'Cliché', 'Medios'],
  ['Masajista porno', 'Cliché', 'Medios'],
  ['Vecina que pide sal', 'Cliché', 'Medios'],
  ['Repartidor de pizza', 'Cliché', 'Medios'],
  ['Sofá de prueba', 'Cliché', 'Medios'],
  ['Cámara subjetiva', 'Cámara', 'Medios'],
  ['Casero', 'Casero', 'Medios'],
  ['Casero', 'Casero', 'Medios'],
  ['Compilatorio de acabadas dentro', 'Compilatorio', 'Medios'],
  ['Anime erótico', 'Anime', 'Medios'],
  ['Regla treinta y cuatro', 'Internet', 'Medios'],
  ['Contenido adulto', 'Etiqueta', 'Internet'],
  ['Anticipo de desnudos', 'Meme', 'Internet'],
  ['Foto provocadora', 'Foto provocadora', 'Redes'],
  ['Foto en lencería', 'Redes', 'Redes'],
  ['Historia destacada caliente', 'Redes', 'Redes'],
  ['Círculo cercano +18', 'Red social', 'Redes'],
  ['Canal de mensajería caliente', 'Mensajería', 'Internet'],
  ['Pack filtrado', 'Filtración', 'Internet'],
  ['Suscripción mensual', 'Plataforma de fans', 'Internet'],
  ['Pagar propinas', 'Propina', 'Internet'],
  ['Vídeo por encargo', 'Encargo', 'Internet'],
  ['Valorar la polla', 'Valoración', 'Internet'],
  ['Instrucciones para pajearse', 'Instrucciones', 'Internet'],
  ['Fetiche de tragar', 'Fetiche', 'Internet'],
  ['Humillación del tamaño', 'Humillación', 'Internet'],
  ['Dominación financiera', 'Dinero', 'Fetiche'],
  ['Dominadora financiera', 'Dominatrix económica', 'Fetiche'],
  ['Tributo', 'Pago', 'Fetiche'],
  ['Vaciar la cartera', 'Dinero', 'Fetiche'],
  ['Custodia de la llave', 'Castidad', 'Sadomaso'],
  ['Jaula de castidad', 'Jaula', 'Sadomaso'],
  ['Control del orgasmo', 'Control', 'Sadomaso'],
  ['Negación del orgasmo', 'Negación', 'Sadomaso'],
  ['Provocación y negación', 'Negación', 'Sadomaso'],
  ['Calentar por dentro', 'Calentar', 'Sexo'],
  ['Fetiche de fecundación', 'Fantasía de embarazo', 'Fetiche'],
  ['Fetiche de embarazo', 'Fantasía de embarazo', 'Fetiche'],
  ['Fetiche de lactancia', 'Leche', 'Fetiche'],
  ['Agonizar con ganas de mear', 'Ganas de mear', 'Fetiche'],
  ['Lluvia dorada', 'Orina', 'Fetiche'],
  ['Coprofilia', 'Heces', 'Fetiche'],
  ['Juego con sangre', 'Sangre', 'Sadomaso'],
  ['Juego con cuchillo', 'Cuchillo', 'Sadomaso'],
  ['Juego con fuego', 'Fuego', 'Sadomaso'],
  ['Juego con agujas', 'Agujas', 'Sadomaso'],
  ['Juego de asfixxia', 'Asfixxia', 'Sadomaso'],
  ['Agarre del cuello', 'Cuello', 'Sadomaso'],
  ['Tirones de pelo', 'Pelo', 'Sexo'],
  ['Escupir', 'Escupir', 'Fetiche'],
  ['Cachetear', 'Cachete', 'Sadomaso'],
  ['Cachete en la cara', 'Cachete', 'Sadomaso'],
  ['Arcadas', 'Náuseas', 'Sexo oral'],
  ['Babeo', 'Babeo', 'Sexo oral'],
  ['Mamada babosa', 'Babeo', 'Sexo oral'],
  ['Hasta el fondo', 'Hasta el fondo', 'Sexo'],
  ['Golpes en los huevos', 'Patada', 'Fetiche'],
  ['Tortura genital', 'Tortura genital', 'Sadomaso'],
  ['Banco de fantasías', 'Recuerdos', 'Solo'],
  ['Fantasía recurrente', 'Mente', 'Solo'],
  ['Historial de incógnito', 'Navegador', 'Internet'],
  ['Borrar historial', 'Navegador', 'Internet'],
  ['Navegación privada por vergüenza', 'Internet', 'Internet'],
  ['Cuenta alternativa', 'Secundaria', 'Internet'],
  ['Cuenta anónima', 'Anónimo', 'Internet'],
  ['Foro adulto', 'Foro', 'Internet'],
  ['Servidor adulto', 'Servidor', 'Internet'],
  ['Chat de voz caliente', 'Audio', 'Internet'],
  ['Susurros eróticos', 'Audio', 'Internet'],
  ['Audio caliente', 'Nota de voz', 'Móvil'],
  ['Nota de voz jadeando', 'Audio', 'Móvil'],
  ['Buenos días con foto', 'Desnudo matutino', 'Móvil'],
  ['Buenas noches con audio', 'Sexteo', 'Móvil'],
  ['Emoji de berenjena', 'Símbolo', 'Móvil'],
  ['Emoji de melocotón', 'Símbolo', 'Móvil'],
  ['Emoji de gotas', 'Símbolo', 'Móvil'],
  ['Emoji de chile', 'Símbolo', 'Móvil'],
  ['Texto sugerente', 'Indirecta', 'Móvil'],
  ['Indirectas en historias', 'Celos', 'Redes'],
  ['Canción dedicada en historias', 'Ligue', 'Redes'],
  ['Publicar y borrar', 'Inseguridad', 'Redes'],
  ['Bloqueo suave', 'Bloqueo suave', 'Redes'],
  ['Bloqueo total', 'Bloqueo', 'Redes'],
  ['Silenciar historias', 'Silenciar', 'Redes'],
  ['Círculo cercano sin ti', 'Excluido', 'Redes'],
];

export const ADULT_WORDS: readonly string[] = ADULT_WORD_PAIRS.map(([w]) => w);
