/**
 * Parejas de palabras para Mr White.
 * - Normales: primera palabra (también usan otros juegos la columna 1).
 * - Farsantes: segunda — misma categoría, claramente distinta (no sinónimo ni subespecie).
 * - Mr White (pista): tercera — ambiente/contexto relacionado de lejos; nada de sonidos ni rasgos delatores.
 */

export type WordPair = readonly [normal: string, farsante: string, hint: string];

export const WORD_PAIRS: readonly WordPair[] = [
  ['Perro', 'Lobo', 'Parque al atardecer'],
  ['Gato', 'Tigre', 'Sofá junto a la ventana'],
  ['León', 'Tigre', 'Sabana al amanecer'],
  ['Caballo', 'Cebra', 'Campo abierto'],
  ['Vaca', 'Búfalo', 'Pradera verde'],
  ['Oveja', 'Cabra', 'Colina con niebla'],
  ['Cerdo', 'Jabalí', 'Barro tras la lluvia'],
  ['Conejo', 'Liebre', 'Huerto de madrugada'],
  ['Ratón', 'Ardilla', 'Rincón del trastero'],
  ['Oso', 'Panda', 'Bosque denso'],
  ['Águila', 'Halcón', 'Cielo despejado'],
  ['Búho', 'Murciélago', 'Noche en el bosque'],
  ['Pato', 'Ganso', 'Estanque del parque'],
  ['Gallina', 'Pavo', 'Corral de pueblo'],
  ['Paloma', 'Cuervo', 'Plaza con bancos'],
  ['Loro', 'Tucán', 'Jaula junto a la ventana'],
  ['Pingüino', 'Foca', 'Hielo y viento'],
  ['Delfín', 'Ballena', 'Espuma en alta mar'],
  ['Tiburón', 'Orca', 'Profundidades'],
  ['Pulpo', 'Medusa', 'Acuario oscuro'],
  ['Araña', 'Escorpión', 'Rincón polvoriento'],
  ['Hormiga', 'Abeja', 'Picnic en el césped'],
  ['Abeja', 'Avispa', 'Jardín en flor'],
  ['Mariposa', 'Libélula', 'Prado de primavera'],
  ['Mosca', 'Mosquito', 'Tarde de verano'],
  ['Serpiente', 'Lagarto', 'Roca al sol'],
  ['Tortuga', 'Caracol', 'Orilla tranquila'],
  ['Rana', 'Tritón', 'Charca de noche'],
  ['Cocodrilo', 'Caimán', 'Río turbio'],
  ['Camello', 'Llama', 'Desierto lejano'],
  ['Elefante', 'Rinoceronte', 'Sabana seca'],
  ['Jirafa', 'Cebra', 'Árboles altos'],
  ['Mono', 'Perezoso', 'Copa de los árboles'],
  ['Gorila', 'Chimpancé', 'Selva húmeda'],
  ['Canguro', 'Koala', 'Llanura austral'],
  ['Koala', 'Wombat', 'Árbol de eucalipto'],
  ['Zorro', 'Coyote', 'Claro del bosque'],
  ['Lince', 'Puma', 'Montaña nevada'],
  ['Jaguar', 'Leopardo', 'Selva tropical'],
  ['Hiena', 'Chacal', 'Noche en la sabana'],
  ['Flamenco', 'Pelícano', 'Laguna rosa'],
  ['Cisne', 'Pato', 'Lago en calma'],
  ['Cuervo', 'Urraca', 'Tejado viejo'],
  ['Canario', 'Jilguero', 'Jaula en el balcón'],
  ['Hamster', 'Cobaya', 'Rueda en la jaula'],
  ['Hurón', 'Comadreja', 'Madriguera estrecha'],
  ['Nutria', 'Castor', 'Río con piedras'],
  ['Morsa', 'Foca', 'Banquisa'],
  ['Estrella de mar', 'Erizo de mar', 'Marea baja'],
  ['Cangrejo', 'Langosta', 'Rocas con algas'],
  ['Pizza', 'Lasaña', 'Viernes en casa'],
  ['Café', 'Té', 'Terraza de mañana'],
  ['Pan', 'Biscote', 'Horno del barrio'],
  ['Queso', 'Mantequilla', 'Tabla de picoteo'],
  ['Leche', 'Batido', 'Desayuno temprano'],
  ['Huevo', 'Tortilla', 'Sartén caliente'],
  ['Arroz', 'Pasta', 'Olla humeante'],
  ['Sopa', 'Cuscus', 'Invierno en casa'],
  ['Ensalada', 'Gazpacho', 'Comida ligera'],
  ['Hamburguesa', 'Perrito caliente', 'Local de comida rápida'],
  ['Patatas fritas', 'Nachos', 'Ración para compartir'],
  ['Chocolate', 'Caramelo', 'Merienda dulce'],
  ['Helado', 'Granizado', 'Paseo de verano'],
  ['Pastel', 'Magdalena', 'Cumpleaños'],
  ['Donut', 'Cruasán', 'Cafetería de paso'],
  ['Manzana', 'Pera', 'Frutero de cocina'],
  ['Naranja', 'Limón', 'Zumo recién hecho'],
  ['Plátano', 'Kiwi', 'Bowl de fruta'],
  ['Fresa', 'Frambuesa', 'Tarta del domingo'],
  ['Uva', 'Cereza', 'Racimo en la mesa'],
  ['Sandía', 'Melón', 'Toalla en la playa'],
  ['Piña', 'Mango', 'Cóctel tropical'],
  ['Aguacate', 'Oliva', 'Tostada de brunch'],
  ['Tomate', 'Pimiento', 'Sofrito casero'],
  ['Zanahoria', 'Apio', 'Estofado lento'],
  ['Cebolla', 'Puerro', 'Olla de guiso'],
  ['Lechuga', 'Espinaca', 'Hojas verdes'],
  ['Brócoli', 'Coliflor', 'Verde ramoso'],
  ['Maíz', 'Trigo', 'Mazorca'],
  ['Avena', 'Cebada', 'Gachas'],
  ['Azúcar', 'Miel', 'Sobrecito'],
  ['Sal', 'Pimienta', 'Salero'],
  ['Aceite', 'Vinagre', 'Oliva'],
  ['Mostaza', 'Ketchup', 'Amarilla'],
  ['Mayonesa', 'Alioli', 'Huevo aceite'],
  ['Sushi', 'Sashimi', 'Wasabi'],
  ['Taco', 'Burrito', 'Tortilla mexicana'],
  ['Paella', 'Risotto', 'Azafrán'],
  ['Empanada', 'Croqueta', 'Relleno'],
  ['Tortilla española', 'Croqueta', 'Bar de raciones'],
  ['Chorizo', 'Salchichón', 'Picante'],
  ['Jamón', 'Bacon', 'Serrano'],
  ['Pollo', 'Pavo', 'Ala asada'],
  ['Carne', 'Pescado', 'Parrilla'],
  ['Salmón', 'Atún', 'Rosa ahumado'],
  ['Gambas', 'Langostinos', 'Pelar'],
  ['Mejillones', 'Almejas', 'Concha azul'],
  ['Calamares', 'Sepia', 'Anillas fritas'],
  ['Bocadillo', 'Sándwich', 'Barra pan'],
  ['Tostada', 'Biscote', 'Desayuno'],
  ['Zumos', 'Batidos', 'Exprimido'],
  ['Refresco', 'Agua con gas', 'Burbujas'],
  ['Cerveza', 'Sidra', 'Caña'],
  ['Vino', 'Cava', 'Uva fermentada'],
  ['Whisky', 'Ron', 'Hielo'],
  ['Vodka', 'Ginebra', 'Transparente'],
  ['Cóctel', 'Chupito', 'Mezcla'],
  ['Smoothie', 'Batido', 'Licuadora'],
  ['Granizado', 'Helado de agua', 'Hielo limón'],
  ['Chicle', 'Caramelo', 'Masticar'],
  ['Avión', 'Helicóptero', 'Cielo'],
  ['Coche', 'Moto', 'Carretera'],
  ['Autobús', 'Tranvía', 'Parada'],
  ['Tren', 'Metro', 'Vías y andenes'],
  ['Barco', 'Yate', 'Puerto y mar abierto'],
  ['Bicicleta', 'Patinete', 'Pedales y casco'],
  ['Camión', 'Furgoneta', 'Mercancías'],
  ['Taxi', 'Uber', 'Taxímetro'],
  ['Submarino', 'Barco', 'Periscopio'],
  ['Cohete', 'Satélite', 'Despegue'],
  ['Globo aerostático', 'Dirigible', 'Aire caliente'],
  ['Ferry', 'Catamarán', 'Travesía'],
  ['Canoa', 'Kayak', 'Remo'],
  ['Tabla de surf', 'Bodyboard', 'Ola'],
  ['Patinaje', 'Monopatín', 'Ruedas'],
  ['Trineo', 'Moto de nieve', 'Nieve'],
  ['Tractor', 'Excavadora', 'Arar'],
  ['Grúa', 'Montacargas', 'Obra'],
  ['Ambulancia', 'Bomberos', 'Sirena'],
  ['Policía', 'Detective', 'Patrulla'],
  ['Hospital', 'Clínica', 'Médico'],
  ['Montaña', 'Colina', 'Cumbre'],
  ['Playa', 'Costa', 'Arena'],
  ['Bosque', 'Selva', 'Árboles'],
  ['Desierto', 'Dunas', 'Sed'],
  ['Río', 'Arroyo', 'Corriente'],
  ['Lago', 'Laguna', 'Orilla'],
  ['Mar', 'Océano', 'Salada'],
  ['Isla', 'Península', 'Mar alrededor'],
  ['Volcán', 'Cráter', 'Lava'],
  ['Ciudad', 'Pueblo', 'Edificios'],
  ['Calle', 'Avenida', 'Semáforo'],
  ['Plaza', 'Parque', 'Fuente'],
  ['Puente', 'Túnel', 'Cruzar río'],
  ['Castillo', 'Palacio', 'Torre'],
  ['Iglesia', 'Catedral', 'Campana'],
  ['Museo', 'Galería', 'Cuadros'],
  ['Biblioteca', 'Archivo', 'Libros'],
  ['Escuela', 'Universidad', 'Pupitre'],
  ['Oficina', 'Despacho', 'Escritorio'],
  ['Tienda', 'Supermercado', 'Caja'],
  ['Mercado', 'Feria', 'Puestos'],
  ['Restaurante', 'Cafetería', 'Menú'],
  ['Bar', 'Pub', 'Tapas'],
  ['Hotel', 'Apartamento', 'Recepción'],
  ['Aeropuerto', 'Estación', 'Vuelo'],
  ['Puerto', 'Muelle', 'Contenedores'],
  ['Fábrica', 'Almacén', 'Producción'],
  ['Granja', 'Huerto', 'Animales'],
  ['Jardín', 'Huerto', 'Regar'],
  ['Cine', 'Teatro', 'Película'],
  ['Estadio', 'Arena', 'Grada'],
  ['Gimnasio', 'Piscina', 'Pesas'],
  ['Spa', 'Sauna', 'Masaje'],
  ['Zoo', 'Acuario', 'Jaulas'],
  ['Parque de atracciones', 'Feria', 'Montaña rusa'],
  ['Camping', 'Glamping', 'Tienda campaña'],
  ['Cueva', 'Gruta', 'Estalactitas'],
  ['Cascada', 'Catarata', 'Agua cayendo'],
  ['Glaciar', 'Iceberg', 'Hielo milenario'],
  ['Ordenador', 'Tablet', 'Teclado'],
  ['Móvil', 'Smartwatch', 'Llamar'],
  ['Teclado', 'Ratón', 'Teclas'],
  ['Pantalla', 'Monitor', 'Píxeles'],
  ['Impresora', 'Escáner', 'Tinta'],
  ['Auriculares', 'Altavoz', 'Escuchar'],
  ['Cámara', 'Webcam', 'Objetivo'],
  ['Router', 'Módem', 'Internet'],
  ['USB', 'Disco duro', 'Puerto'],
  ['Nube', 'Niebla', 'Almacenamiento online'],
  ['Wifi', 'Bluetooth', 'Inalámbrico'],
  ['App', 'Programa', 'Instalar'],
  ['Web', 'Blog', 'Navegador'],
  ['Email', 'Mensaje', 'Arroba'],
  ['Videojuego', 'Consola', 'Mando'],
  ['Joystick', 'Mando', 'Botones'],
  ['Drone', 'Robot', 'Hélices'],
  ['Inteligencia artificial', 'Algoritmo', 'Aprende sola'],
  ['Código', 'Script', 'Programar'],
  ['Base de datos', 'Archivo', 'Tablas'],
  ['Contraseña', 'PIN', 'Oculta'],
  ['Emoji', 'Sticker', 'Carita'],
  ['Selfie', 'Foto', 'Cámara frontal'],
  ['Podcast', 'Audiolibro', 'Episodio'],
  ['Streaming', 'Descarga', 'En directo'],
  ['Pixel', 'Resolución', 'Cuadrado pequeño'],
  ['Batería', 'Pila', 'Autonomía'],
  ['Cable', 'Adaptador', 'Enchufar'],
  ['Microchip', 'Procesador', 'Silicio'],
  ['Antena', 'Señal', 'Captar ondas'],
  ['Película', 'Serie', 'Palomitas'],
  ['Libro', 'Novela', 'Biblioteca'],
  ['Cómico', 'Humorista', 'Risas'],
  ['Actor', 'Actriz', 'Escenario'],
  ['Cantante', 'Músico', 'Voz'],
  ['Banda', 'Orquesta', 'Guitarra'],
  ['Canción', 'Melodía', 'Estribillo'],
  ['Concierto', 'Festival', 'Entradas'],
  ['Danza', 'Ballet', 'Coreografía'],
  ['Pintura', 'Dibujo', 'Lienzo'],
  ['Escultura', 'Estatua', 'Mármol'],
  ['Fotografía', 'Ilustración', 'Cámara'],
  ['Noticia', 'Reportaje', 'Titular'],
  ['Periódico', 'Revista', 'Portada'],
  ['Podcast de entrevistas', 'Audiolibro', 'Auriculares'],
  ['Documental', 'Reportaje', 'Televisión informativa'],
  ['Thriller', 'Suspense', 'Tensión'],
  ['Comedia', 'Drama', 'Humor'],
  ['Terror', 'Misterio', 'Susto'],
  ['Romance', 'Drama', 'Amor'],
  ['Anime', 'Manga', 'Japón'],
  ['Cómic', 'Novela gráfica', 'Viñetas'],
  ['Puzzle', 'Rompecabezas', 'Encajar'],
  ['Ajedrez', 'Damas', 'Jaque mate'],
  ['Cartas', 'Dominó', 'Baraja'],
  ['Dados', 'Ruleta', 'Suerte'],
  ['Bingo', 'Lotería', 'Números'],
  ['Karaoke', 'Micrófono', 'Jugar'],
  ['Magia', 'Ilusionismo', 'Truco'],
  ['Circo', 'Feria', 'Trapecio'],
  ['Fútbol', 'Baloncesto', 'Gol'],
  ['Tenis', 'Pádel', 'Raqueta'],
  ['Golf', 'Bolos', 'Césped cuidado'],
  ['Natación', 'Waterpolo', 'Piscina'],
  ['Atletismo', 'Maratón', 'Pista'],
  ['Ciclismo', 'Triatlón', 'Escena cotidiana'],
  ['Boxeo', 'Kickboxing', 'Ring'],
  ['Judo', 'Karate', 'Tatami'],
  ['Yoga', 'Pilates', 'Estera'],
  ['Esquí', 'Snowboard', 'Nieve'],
  ['Surf', 'Skate', 'Espuma en la orilla'],
  ['Escalada', 'Rappel', 'Cuerda'],
  ['Remo', 'Piragüismo', 'Brazada'],
  ['Vela', 'Regata', 'Ambiente cercano'],
  ['Hockey', 'Lacrosse', 'Stick'],
  ['Rugby', 'Fútbol americano', 'Placaje'],
  ['Voleibol', 'Balonmano', 'Red'],
  ['Béisbol', 'Softbol', 'Bate'],
  ['Críquet', 'Croquet', 'Bate largo'],
  ['Ping-pong', 'Bádminton', 'Mesa'],
  ['Dardos', 'Bolos', 'Triple veinte'],
  ['Billar', 'Snooker', 'Taco'],
  ['Esgrima', 'Arquería', 'Asalto'],
  ['Halterofilia', 'Crossfit', 'Barra'],
  ['Parkour', 'Gimnasia', 'Saltos'],
  ['Patinaje artístico', 'Hockey sobre hielo', 'Pirueta'],
  ['Motocross', 'Rally', 'Barro'],
  ['Fórmula 1', 'MotoGP', 'Circuito'],
  ['Equitación', 'Polo', 'Silla'],
  ['Pesca', 'Caza', 'Anzuelo'],
  ['Camiseta', 'Polo', 'Manga corta'],
  ['Pantalón', 'Vaqueros', 'Perneras'],
  ['Falda', 'Vestido', 'Pliegues'],
  ['Chaqueta', 'Abrigo', 'Cremallera'],
  ['Sudadera', 'Jersey', 'Capucha'],
  ['Zapatos', 'Otro del mismo tipo', 'Cordones'],
  ['Botas', 'Sandalias', 'Caña alta'],
  ['Sombrero', 'Gorra', 'Ala'],
  ['Bufanda', 'Guantes', 'Cuello'],
  ['Cinturón', 'Tirantes', 'Hebilla'],
  ['Gafas', 'Lentes de contacto', 'Graduación'],
  ['Reloj', 'Pulsera', 'Manecillas'],
  ['Collar', 'Pendientes', 'Cadena'],
  ['Anillo', 'Pendiente', 'Dedo'],
  ['Mochila', 'Bolso', 'Espalda'],
  ['Maleta', 'Mochila', 'Viaje'],
  ['Paraguas', 'Chubasquero', 'Lluvia'],
  ['Bañador', 'Bikini', 'Verano'],
  ['Pijama', 'Bata', 'Noche'],
  ['Corbata', 'Pajarita', 'Nudo'],
  ['Calcetines', 'Medias', 'Tobillo'],
  ['Ropa interior', 'Camiseta interior', 'Íntimo'],
  ['Traje', 'Esmóquin', 'Formal'],
  ['Uniforme', 'Bata de trabajo', 'Colegio'],
  ['Delantal', 'Mandil', 'Protege al cocinar'],
  ['Casco', 'Gorra de seguridad', 'Protección'],
  ['Chaleco', 'Abrigo', 'Pasillo del armario'],
  ['Guantes de cocina', 'Manopla', 'Horno'],
  ['Zuecos', 'Chanclas', 'Madera en el pie'],
  ['Tacones', 'Plataformas', 'Altos'],
  ['Silla', 'Sofá', 'Sentarse'],
  ['Mesa', 'Escritorio', 'Comer'],
  ['Cama', 'Colchón', 'Dormir'],
  ['Almohada', 'Cojín', 'Cabeza'],
  ['Manta', 'Edredón', 'Abrigarse'],
  ['Lámpara', 'Bombilla', 'Luz'],
  ['Ventana', 'Persiana', 'Cristal'],
  ['Puerta', 'Portón', 'Llave'],
  ['Escalera', 'Ascensor', 'Peldaños'],
  ['Cocina', 'Horno', 'Recetas'],
  ['Nevera', 'Congelador', 'Frío'],
  ['Microondas', 'Tostadora', 'Calentar'],
  ['Lavadora', 'Secadora', 'Detergente'],
  ['Aspiradora', 'Escoba', 'Polvo'],
  ['Plancha', 'Secador', 'Arrugas'],
  ['Espejo', 'Cuadro', 'Reflejo'],
  ['Estantería', 'Armario', 'Libros'],
  ['Cajón', 'Estante', 'Guardar'],
  ['Alfombra', 'Moqueta', 'Suelo'],
  ['Cortina', 'Estor', 'Oscurecer'],
  ['Vaso', 'Taza', 'Beber'],
  ['Plato', 'Fuente', 'Mesa servida'],
  ['Cubiertos', 'Cuchillo', 'Tenedor'],
  ['Olla', 'Sartén', 'Guiso'],
  ['Tetera', 'Cafetera', 'Té'],
  ['Botella', 'Jarra', 'Tapón'],
  ['Servilleta', 'Mantel', 'Boca'],
  ['Cubo', 'Fregona', 'Fregar'],
  ['Estantería de cocina', 'Despensa', 'Tarros'],
  ['Basura', 'Reciclaje', 'Contenedor'],
  ['Sol', 'Estrella', 'Calor'],
  ['Estrella', 'Planeta', 'Brillar'],
  ['Nubarrón', 'Niebla', 'Lluvia'],
  ['Lluvia', 'Tormenta', 'Gotas'],
  ['Nieve', 'Granizo', 'Copos'],
  ['Viento', 'Brisa', 'Soplar'],
  ['Rayo', 'Trueno', 'Destello'],
  ['Arcoíris', 'Aurora', 'Colores'],
  ['Primavera', 'Otoño', 'Marzo'],
  ['Otoño', 'Invierno', 'Octubre'],
  ['Árbol', 'Arbusto', 'Ramas y raíces'],
  ['Flor', 'Pétalo', 'Olor'],
  ['Hoja', 'Rama', 'Verde'],
  ['Hierba', 'Césped', 'Cortar'],
  ['Semilla', 'Brote', 'Germinar'],
  ['Raíz', 'Tallo', 'Bajo tierra'],
  ['Fruto', 'Baya', 'Maduro'],
  ['Seta', 'Hongo', 'Bosque'],
  ['Musgo', 'Liquen', 'Húmedo'],
  ['Coral', 'Arrecife', 'Mar'],
  ['Piedra', 'Roca', 'Dura'],
  ['Arena', 'Grava', 'Playa'],
  ['Arcilla', 'Barro', 'Modelar'],
  ['Oro', 'Plata', 'Brillo'],
  ['Hierro', 'Acero', 'Oxidarse'],
  ['Cobre', 'Bronce', 'Cable'],
  ['Diamante', 'Rubí', 'Brillante'],
  ['Cristal', 'Vidrio', 'Transparente'],
  ['Papel', 'Cartón', 'Escribir'],
  ['Plástico', 'Caucho', 'Moldeable'],
  ['Médico', 'Enfermero', 'Estetoscopio'],
  ['Profesor', 'Maestro', 'Pizarra'],
  ['Ingeniero', 'Arquitecto', 'Planos'],
  ['Abogado', 'Juez', 'Juicio'],
  ['Bombero', 'Socorrista', 'Incendio'],
  ['Cocinero', 'Chef', 'Receta'],
  ['Camarero', 'Barman', 'Bandeja'],
  ['Piloto', 'Azafata', 'Cabina'],
  ['Mecánico', 'Electricista', 'Motor'],
  ['Fontanero', 'Albañil', 'Grifo'],
  ['Carpintero', 'Ebanista', 'Madera'],
  ['Pintor', 'Escultor', 'Brocha'],
  ['Periodista', 'Editor', 'Titular'],
  ['Fotógrafo', 'Camarógrafo', 'Enfoque'],
  ['Diseñador', 'Ilustrador', 'Logo'],
  ['Programador', 'Analista', 'Código'],
  ['Contable', 'Economista', 'Impuestos'],
  ['Veterinario', 'Zoólogo', 'Mascota'],
  ['Farmacéutico', 'Químico', 'Receta'],
  ['Dentista', 'Ortodoncista', 'Taladro'],
  ['Psicólogo', 'Psiquiatra', 'Sesión'],
  ['Fisioterapeuta', 'Masajista', 'Lesión'],
  ['Peluquero', 'Barbero', 'Tijeras'],
  ['Estilista', 'Maquillador', 'Pasarela'],
  ['Modelo', 'Actor', 'Pasarela'],
  ['Deportista', 'Entrenador', 'Medalla'],
  ['Árbitro', 'Entrenador', 'Silbato'],
  ['Agricultor', 'Ganadero', 'Cosecha'],
  ['Pescador', 'Marinero', 'Anzuelo'],
  ['Cabeza', 'Cara', 'Piensa'],
  ['Ojo', 'Oreja', 'Mirar'],
  ['Nariz', 'Boca', 'Oler'],
  ['Mano', 'Brazo', 'Agarrar'],
  ['Pie', 'Empeine', 'Caminar'],
  ['Dedo', 'Uña', 'Pulgar'],
  ['Pelo', 'Barba', 'Peine'],
  ['Diente', 'Muela', 'Morder'],
  ['Corazón', 'Pulmón', 'Latir'],
  ['Estómago', 'Hígado', 'Hambre'],
  ['Hueso', 'Músculo', 'Fractura'],
  ['Sangre', 'Plasma', 'Roja'],
  ['Piel', 'Epidermis', 'Tacto'],
  ['Espalda', 'Hombro', 'Postura'],
  ['Cuello', 'Garganta', 'Bufanda'],
  ['Rodilla', 'Codo', 'Flexionar'],
  ['Tobillo', 'Muñeca', 'Torcedura'],
  ['Cadera', 'Cintura', 'Bailar'],
  ['Pecho', 'Abdomen', 'Respirar'],
  ['Cerebro', 'Nervio', 'Pensar'],
  ['Fiebre', 'Resfriado', 'Sube la temperatura'],
  ['Tos', 'Estornudo', 'Irrita la garganta'],
  ['Vendaje', 'Escayola', 'Herida cubierta'],
  ['Pastilla', 'Jarabe', 'Farmacia y dosis'],
  ['Vacuna', 'Anticuerpo', 'Laboratorio'],
  ['Análisis', 'Radiografía', 'Laboratorio clínico'],
  ['Cirugía', 'Operación', 'Quirófano y bisturí'],
  ['Dieta', 'Ejercicio', 'Menú saludable'],
  ['Sueño', 'Ilusión', 'Cama y descanso'],
  ['Estrés', 'Ansiedad', 'Nervios y presión'],
  ['Día', 'Noche', 'Escena familiar'],
  ['Mañana', 'Tarde', 'Antes del mediodía'],
  ['Ayer', 'Hoy', 'Día ya pasado'],
  ['Semana', 'Mes', 'Siete días seguidos'],
  ['Año', 'Década', 'Doce meses juntos'],
  ['Segundo', 'Minuto', 'Reloj en marcha'],
  ['Hora', 'Reloj', 'Escena familiar'],
  ['Calendario', 'Agenda', 'Cuenta los días'],
  ['Cumpleaños', 'Aniversario', 'Velas en tarta'],
  ['Fiesta', 'Celebración', 'Música y baile'],
  ['Navidad', 'Año Nuevo', 'Árbol y regalos'],
  ['Halloween', 'Carnaval', 'Calabaza tallada'],
  ['Semana Santa', 'Pascua', 'Procesiones en calle'],
  ['Verano', 'Vacaciones', 'Mucho calor'],
  ['Lunes', 'Martes', 'Tras el domingo'],
  ['Sábado', 'Domingo', 'Fin de semana'],
  ['Enero', 'Febrero', 'Primer mes año'],
  ['Estación florida', 'Otoño', 'Flores y alergia'],
  ['Amanecer', 'Atardecer', 'Sale el sol'],
  ['Mediodía', 'Anochecer', 'Doce del día'],
  ['Lápiz', 'Bolígrafo', 'Grafito y madera'],
  ['Cuaderno', 'Libreta', 'Hojas cosidas'],
  ['Pizarra', 'Pantalla', 'Cole'],
  ['Examen', 'Deberes', 'Nota al final'],
  ['Clase', 'Curso', 'Explica el profesor'],
  ['Asignatura', 'Materia', 'En el horario'],
  ['Historia', 'Publicación', 'Pasado y fechas'],
  ['Matemáticas', 'Física', 'Números y ecuaciones'],
  ['Química', 'Biología', 'Reacciones y átomos'],
  ['Lengua', 'Literatura', 'Ortografía y sintaxis'],
  ['Inglés', 'Francés', 'Idioma extranjero'],
  ['Arte', 'Música', 'Pintura y escultura'],
  ['Educación física', 'Recreo', 'Pista del cole'],
  ['Biblioteca escolar', 'Sala de estudio', 'Libros prestados'],
  ['Mochila escolar', 'Estuche', 'Llevar los libros'],
  ['Goma de borrar', 'Sacapuntas', 'Borra el lápiz'],
  ['Regla', 'Compás', 'Medir centímetros'],
  ['Calculadora', 'Ábaco', 'Botones numéricos'],
  ['Diccionario', 'Enciclopedia', 'Definiciones de palabras'],
  ['Mapa', 'Brújula', 'Coordenadas geográficas'],
  ['Alegría', 'Felicidad', 'Ganas de sonreír'],
  ['Tristeza', 'Melancolía', 'Ganas de llorar'],
  ['Miedo', 'Terror', 'Querer escapar'],
  ['Enojo', 'Ira', 'Cara de enfado'],
  ['Amor', 'Cariño', 'Corazón acelerado'],
  ['Amistad', 'Compañerismo', 'Mejor amigo'],
  ['Esperanza', 'Ilusión', 'Futuro mejor'],
  ['Sorpresa', 'Asombro', 'Boca abierta'],
  ['Orgullo', 'Vanidad', 'Sentirse superior'],
  ['Vergüenza', 'Timidez', 'Cara colorada'],
  ['Paz', 'Tranquilidad', 'Sin conflictos'],
  ['Caos', 'Desorden', 'Todo revuelto'],
  ['Éxito', 'Logro', 'Meta cumplida'],
  ['Fracaso', 'Error', 'Plan que salió mal'],
  ['Suerte', 'Casualidad', 'Azar favorable'],
  ['Destino', 'Futuro', 'Camino marcado'],
  ['Recuerdo', 'Memoria', 'Foto en la mente'],
  ['Ensueño', 'Ilusión', 'Soñar despierto'],
  ['Idea', 'Pensamiento', 'Bombilla encendida'],
  ['Secreto', 'Misterio', 'Susurro entre dos'],
  ['Martillo', 'Destornillador', 'Clava clavos'],
  ['Sierra', 'Cutter', 'Corta madera'],
  ['Clavo', 'Tornillo', 'Lo clava martillo'],
  ['Llave', 'Candado', 'Abre la puerta'],
  ['Cuerda', 'Cadena', 'Atar fuerte'],
  ['Cinta', 'Pegamento', 'Pegar papeles'],
  ['Tijeras', 'Cutter', 'Cortar papel'],
  ['Pinza', 'Alicates', 'Sujetar metal'],
  ['Brocha', 'Pincel', 'Pintar pared'],
  ['Rodillo', 'Espátula', 'Pintar la pared'],
  ['Linterna', 'Vela', 'Luz portátil'],
  ['Fósforo', 'Mechero', 'Encender fuego'],
  ['Pila recargable', 'Otro del mismo tipo', 'Da energía'],
  ['Enchufe', 'Alargador', 'Conectar corriente'],
  ['Termómetro', 'Barómetro', 'Mide los grados'],
  ['Brújula', 'GPS', 'Apunta al norte'],
  ['Mapa turístico', 'Brújula', 'Rutas y caminos'],
  ['Binoculares', 'Telescopio', 'Ver muy lejos'],
  ['Microscopio', 'Lupa', 'Ver lo pequeño'],
  ['Balanza', 'Báscula', 'Pesa objetos'],
  ['Dinero', 'Moneda', 'Billetera'],
  ['Billete', 'Tarjeta', 'En el bolsillo'],
  ['Banco', 'Cajero', 'Guardar ahorros'],
  ['Precio', 'Coste', 'Etiqueta tienda'],
  ['Compra', 'Venta', 'En el super'],
  ['Oferta', 'Descuento', 'Precio rebajado'],
  ['Factura', 'Recibo', 'IVA incluido'],
  ['Impuesto', 'Tasa', 'Cobra Hacienda'],
  ['Ahorro', 'Inversión', 'Hucha llena'],
  ['Deuda', 'Préstamo', 'Deber dinero'],
  ['Sueldo', 'Salario', 'Fin de mes'],
  ['Propina', 'Comisión', 'Tras la comida'],
  ['Presupuesto', 'Gasto', 'Excel mensual'],
  ['Beneficio', 'Pérdida', 'Más ingresos'],
  ['Acciones', 'Bonos', 'Bolsa de valores'],
  ['Criptomoneda', 'Bitcoin', 'Blockchain virtual'],
  ['Cheque', 'Transferencia', 'Firmar y cobrar'],
  ['Efectivo', 'Tarjeta de crédito', 'Billetes y monedas'],
  ['Cartera', 'Tarjetero', 'Guardar tarjetas'],
  ['Caja fuerte', 'Candado', 'Oficina discreta'],
  ['Viaje', 'Excursión', 'Maleta preparada'],
  ['Maleta con ruedas', 'Mochila', 'Ruedas y asa'],
  ['Pasaporte', 'Visa', 'Control fronterizo'],
  ['Billete de avión', 'Reserva', 'Mostrador aeropuerto'],
  ['Hotel boutique', 'Apartamento', 'Recepción y habitación'],
  ['Turista', 'Viajero', 'Cámara de fotos'],
  ['Guía', 'Mapa', 'Explica monumentos'],
  ['Souvenir', 'Recuerdo', 'De las vacaciones'],
  ['Aduana', 'Control', 'Declarar equipaje'],
  ['Equipaje', 'Bolsa de mano', 'Facturar en mostrador'],
  ['Campamento', 'Glamping', 'Tienda de campaña'],
  ['Crucero', 'Travesía', 'Barco de lujo'],
  ['Safari', 'Expedición', 'Animales salvajes'],
  ['Ruta', 'Itinerario', 'Mapa marcado'],
  ['Escala', 'Conexión', 'Cambiar de avión'],
  ['Embarque', 'Abordaje', 'Mostrar tarjeta'],
  ['Check-in', 'Registro', 'Recoger la llave'],
  ['Asiento', 'Ventanilla', 'Número de fila'],
  ['Pasillo', 'Entrada', 'Entre las filas'],
  ['Sala de espera', 'Terminal', 'Filas y pantallas'],
  ['Guitarra', 'Bajo', 'Seis cuerdas'],
  ['Piano', 'Teclado', 'Teclas blancas negras'],
  ['Violín', 'Flauta', 'Ensayo de tarde'],
  ['Flauta', 'Clarinete', 'Soplar aire'],
  ['Saxofón', 'Trompeta', 'Jazz y blues'],
  ['Tambor', 'Batería', 'Golpear baquetas'],
  ['Arpa', 'Lira', 'Cuerdas verticales'],
  ['Ukelele', 'Mandolina', 'Cuatro cuerdas'],
  ['Acordeón', 'Armónica', 'Fuelle y teclas'],
  ['Xilófono', 'Marimba', 'Laminas de madera'],
  ['Rojo', 'Naranja', 'Color de sangre'],
  ['Azul', 'Turquesa', 'Color del cielo'],
  ['Verde', 'Esmeralda', 'Color de hierba'],
  ['Amarillo', 'Dorado', 'Color del sol'],
  ['Morado', 'Violeta', 'Mezcla rojo azul'],
  ['Rosa', 'Tulipán', 'Color chicle'],
  ['Negro', 'Gris', 'Color de noche'],
  ['Blanco', 'Beige', 'Color de nieve'],
  ['Círculo', 'Esfera', 'Sin esquinas'],
  ['Cuadrado', 'Cubo', 'Cuatro lados iguales'],
  ['Triángulo', 'Pirámide', 'Tres lados'],
  ['Rectángulo', 'Óvalo', 'Lados opuestos iguales'],
  ['Línea', 'Curva', 'De punto a punto'],
  ['Punto', 'Coma', 'Fin de frase'],
  ['Símbolo', 'Icono', 'Representa algo'],
  ['Número', 'Cifra', 'Dos más dos'],
  ['Letra', 'Palabra', 'Del abecedario'],
  ['Frase', 'Párrafo', 'Varias palabras'],
  ['Título', 'Encabezado', 'Portada del libro'],
  ['Lista', 'Tabla', 'Viñetas ordenadas'],
  ['Desayuno', 'Brunch', 'Primera comida día'],
  ['Comida', 'Cena', 'Mediodía en mesa'],
  ['Merienda', 'Tentempié', 'Entre comidas'],
  ['Ducha', 'Baño', 'Agua caliente'],
  ['Jabón', 'Champú', 'Hace espuma'],
  ['Toalla', 'Albornoz', 'Secarse el cuerpo'],
  ['Cepillo', 'Peine', 'Despeina el pelo'],
  ['Pasta de dientes', 'Enjuague', 'Tubo en baño'],
  ['Desodorante', 'Perfume', 'Axilas frescas'],
  ['Crema', 'Loción', 'Hidrata la piel'],
  ['Afeitado', 'Depilación', 'Quitar la barba'],
  ['Maquillaje', 'Base', 'Pintar la cara'],
  ['Colonia', 'Perfume', 'Oler bien'],
  ['Lavado', 'Planchado', 'Ropa limpia'],
  ['Limpieza', 'Orden', 'Fregar el suelo'],
  ['Compra semanal', 'Lista de la compra', 'Carro del super'],
  ['Recado', 'Encargo', 'Ir a por pan'],
  ['Cita', 'Reunión', 'Hora acordada'],
  ['Llamada', 'Telefonata', 'Suena el móvil'],
  ['Mensaje de texto', 'WhatsApp', 'Escribir al móvil'],
  ['Dragón', 'Unicornio', 'Escupe fuego'],
  ['Mago', 'Hechicero', 'Varita mágica'],
  ['Caballero', 'Guerrero', 'Armadura brillante'],
  ['Princesa', 'Reina', 'Castillo real'],
  ['Castillo encantado', 'Torre', 'Murallas y princesas'],
  ['Espada', 'Escudo', 'Filo afilado'],
  ['Poción', 'Veneno', 'Beber en frasco'],
  ['Fantasma', 'Espectro', 'Atraviesa paredes'],
  ['Vampiro', 'Hombre lobo', 'Colmillos afilados'],
  ['Zombie', 'Esqueleto', 'Camina muy lento'],
  ['Hada', 'Elfo', 'Alas pequeñas'],
  ['Gnomo', 'Duende', 'Barba y jardín'],
  ['Sirena', 'Tritón', 'Cola de pez'],
  ['Fénix', 'Grifo', 'Renace de cenizas'],
  ['Gigante', 'Enano', 'Muy alto'],
  ['Laberinto', 'Mazmorra', 'Caminos confusos'],
  ['Tesoro', 'Cofre', 'Oro escondido'],
  ['Mapa del tesoro', 'Brújula mágica', 'Marca con equis'],
  ['Varita', 'Cetro', 'Hechizo mágico'],
  ['Corona', 'Tiara', 'La lleva el rey'],
  ['Rueda', 'Neumático', 'Gira al rodar'],
  ['Volante', 'Manillar', 'Girar al conducir'],
  ['Freno', 'Acelerador', 'Detiene el coche'],
  ['Faros', 'Intermitentes', 'Iluminan de noche'],
  ['Motor', 'Batería del coche', 'Bajo el capó'],
  ['Gasolina', 'Diésel', 'En gasolinera'],
  ['Parking', 'Garaje', 'Plaza para aparcar'],
  ['Semáforo', 'Stop', 'Luz roja y verde'],
  ['Paso de peatones', 'Rotonda', 'Cruzar la calzada'],
  ['Autopista', 'Carretera', 'Velocidad alta legal'],
  ['Rosa roja', 'Tulipán', 'San Valentín clásica'],
  ['Girasol', 'Margarita', 'Sigue al sol'],
  ['Orquídea', 'Lirio', 'Flor tropical delicada'],
  ['Cactus', 'Suculenta', 'Espinas y poca agua'],
  ['Bonsái', 'Planta de interior', 'Miniatura en maceta'],
  ['Hierbabuena', 'Menta', 'Hoja para mojito'],
  ['Albahaca', 'Perejil', 'Base del pesto'],
  ['Romero', 'Tomillo', 'Rama para asado'],
  ['Lavanda', 'Jazmín', 'Morado y olor'],
  ['Pino', 'Abeto', 'Cono y agujas'],
  ['Roble', 'Haya', 'Bellota ibérica'],
  ['Olivo', 'Almendro', 'Aceite virgen extra'],
  ['Naranjo', 'Limonero', 'Frutos cítricos colgando'],
  ['Manzano', 'Peral', 'Flores blancas primavera'],
  ['Vid', 'Parra', 'Uvas para vendimia'],
  ['Bambú', 'Caña', 'Tallo hueco flexible'],
  ['Palmera', 'Coco', 'Tronco alto playa'],
  ['Helecho', 'Musgo', 'Hojas rizadas húmedas'],
  ['Trébol', 'Diente de león', 'Cuatro hojas suerte'],
  ['Amapola', 'Clavel', 'Rojo en el cereal'],
  ['Espaguetis', 'Macarrones', 'Pasta larga hervida'],
  ['Ravioles', 'Ñoquis', 'Pasta rellena italiana'],
  ['Fideos', 'Tallarines', 'Sopa con caldo'],
  ['Pan integral', 'Baguette', 'Salvado y fibra'],
  ['Baguette', 'Chapata', 'Crujiente y alargado'],
  ['Mermelada', 'Compota', 'Untar en tostada'],
  ['Crema de cacao', 'Mantequilla de cacahuete', 'Untar dulce mañana'],
  ['Cereal', 'Muesli', 'Cuenca con leche'],
  ['Tostada francesa', 'Pancake', 'Huevo y canela'],
  ['Waffle', 'Crepe', 'Rejilla crujiente dulce'],
  ['Sándwich club', 'Bocadillo mixto', 'Tres panes relleno'],
  ['Ensalada César', 'Gazpacho', 'Menú del mediodía'],
  ['Sopa de tomate', 'Crema de verduras', 'Rojo y caliente'],
  ['Puré', 'Guiso', 'Patata triturada'],
  ['Estofado', 'Asado', 'Olla fuego lento'],
  ['Barbacoa', 'Plancha', 'Carne con brasa'],
  ['Horneado', 'Frito', 'Calor del horno'],
  ['Crudo', 'Cocido', 'Sin pasar fuego'],
  ['Picante', 'Dulce', 'Pica la lengua'],
  ['Ácido', 'Amargo', 'Sabor a vinagre'],
  ['Capital', 'Ciudad', 'Sede del gobierno'],
  ['País', 'Nación', 'Bandera y fronteras'],
  ['Continente', 'Región', 'Europa o África'],
  ['Frontera', 'Límite', 'Pasaporte en aduana'],
  ['Bandera', 'Escudo', 'Tela ondeando asta'],
  ['Idioma', 'Dialecto', 'Palabras que hablamos'],
  ['Cultura', 'Tradición', 'Fiestas y costumbres'],
  ['Costumbre', 'Rito', 'Lo de siempre'],
  ['Fiesta popular', 'Carnaval', 'Verbena local'],
  ['Monumento', 'Estatua', 'Visitar en turismo'],
  ['Reunión', 'Videollamada', 'Sala de juntas'],
  ['Presentación', 'Informe', 'Diapositivas al equipo'],
  ['Correo', 'Buzón', 'Bandeja de entrada'],
  ['Sello', 'Sobre', 'Carta ya franqueada'],
  ['Carpeta', 'Archivador', 'Dossier de papeles'],
  ['Grapadora', 'Clip', 'Une hojas metálicas'],
  ['Post-it', 'Nota', 'Amarillo en monitor'],
  ['Pizarra blanca', 'Rotulador', 'Aula y marcadores'],
  ['Proyector', 'Pantalla', 'Sala oscura'],
  ['Oficina abierta', 'Despacho privado', 'Sin despachos cerrados'],
  ['Nadar', 'Broncearse', 'Brasada en piscina'],
  ['Esquiar', 'Patinar', 'Nieve y pendiente'],
  ['Senderismo', 'Camping', 'Botas por monte'],
  ['Picnic', 'Barbacoa', 'Manta en césped'],
  ['Mercadillo', 'Rastro', 'Puestos segunda mano'],
  ['Concierto al aire libre', 'Festival', 'Escenario sin techo'],
  ['Fogata', 'Chimenea', 'Leña chispas noche'],
  ['Hamaca', 'Tumbona', 'Siesta colgada'],
  ['Sombrilla', 'Toldos', 'Sombra en playa'],
  ['Nevera portátil', 'Termo', 'Bebidas bien frías'],
  ['Tierra', 'Marte', 'Azul desde espacio'],
  ['Sol de verano', 'Estrella', 'Centro del sistema'],
  ['Luna', 'Satélite', 'Mareas y fases'],
  ['Cometa', 'Asteroide', 'Cola en cielo'],
  ['Galaxia', 'Universo', 'Millones de estrellas'],
  ['Astronauta', 'Cosmonauta', 'Traje gravedad cero'],
  ['Nave espacial', 'Estación espacial', 'Despega al espacio'],
  ['Telescopio espacial', 'Observatorio', 'Observa galaxias lejanas'],
  ['Eclipse', 'Tránsito', 'Luna tapa sol'],
  ['Órbita', 'Gravedad', 'Da vueltas alrededor'],
  ['Medusa', 'Anémona', 'Tentáculos en mar'],
  ['Caballito de mar', 'Pez payaso', 'Mini cabeza equina'],
  ['Tiburón martillo', 'Mantarraya', 'Profundidad azul'],
  ['Mantarraya', 'Pez espada', 'Ala ancha nadando'],
  ['Tortuga marina', 'Delfín', 'Costa protegida'],
  ['Arrecife de coral', 'Otro del mismo tipo', 'Roca submarina viva'],
  ['Plancton', 'Algas', 'Base cadena marina'],
  ['Ballena azul', 'Cachalote', 'Mamífero marino gigante'],
  ['Narval', 'Beluga', 'Cuerno espiral ártico'],
  ['Pez globo', 'Manta raya', 'Se hincha al peligro'],
  ['Mariquita', 'Escarabajo', 'Puntos rojos espalda'],
  ['Libélula', 'Caballito del diablo', 'Cuatro alas iguales'],
  ['Grillo', 'Saltamontes', 'Chirrido verano noche'],
  ['Cigarra', 'Grillo', 'Canta en verano'],
  ['Luciérnaga', 'Mariposa nocturna', 'Brilla en oscuridad'],
  ['Oruga', 'Crisálida', 'Antes de mariposa'],
  ['Gusano', 'Lombriz', 'Anélido en tierra'],
  ['Caracol', 'Babosa', 'Con concha lenta'],
  ['Ciempiés', 'Milpiés', 'Muchas patas pequeñas'],
  ['Garrapata', 'Piojo', 'Parásito chupa sangre'],
  ['Gorrión', 'Pinzón', 'Migas en plaza'],
  ['Golondrina', 'Vencejo', 'Migración en primavera'],
  ['Ruiseñor', 'Canario', 'Canto melodioso bosque'],
  ['Ánade', 'Cerceta', 'Nada en estanque'],
  ['Garza', 'Cigüeña', 'Patas largas río'],
  ['Buitre', 'Águila real', 'Carroñero en montaña'],
  ['Cóndor', 'Albatros', 'Plano montañoso grande'],
  ['Pavo real', 'Faisán', 'Cola abanico color'],
  ['Avestruz', 'Emu', 'Corre sin volar'],
  ['Kiwi', 'Casuario', 'Ave neozelandesa'],
  ['Salón', 'Comedor', 'Sofá y televisor'],
  ['Dormitorio', 'Cuarto de invitados', 'Cama y armario'],
  ['Baño', 'Aseo', 'Ducha y lavabo'],
  ['Terraza', 'Balcón', 'Aire libre casa'],
  ['Ático', 'Sótano', 'Última planta edificio'],
  ['Garaje', 'Trastero', 'Coche dentro casa'],
  ['Pasillo central', 'Entrada', 'Une habitaciones'],
  ['Vestíbulo', 'Recibidor', 'Tras abrir puerta'],
  ['Despacho en casa', 'Estudio', 'Teletrabajo en casa'],
  ['Lavadero', 'Tendedero', 'Ropa tendida'],
  ['Peluche', 'Muñeco', 'Juguete blando niño'],
  ['Legos', 'Bloques', 'Encajan por lomo'],
  ['Canicas', 'Peonzas', 'Pequeñas en suelo'],
  ['Comba', 'Elástico', 'Saltar rítmico'],
  ['Balón', 'Pelota', 'Patada o bote'],
  ['Triciclo', 'Bicicleta infantil', 'Tres ruedas niño'],
  ['Columpio', 'Tobogán', 'Sube baja parque'],
  ['Arenero', 'Parque infantil', 'Jugar con pala'],
  ['Cuento', 'Fábula', 'Historia antes dormir'],
  ['Canción infantil', 'Nana', 'Para dormir peque'],
  ['Calor', 'Bochorno', 'Ola verano sofocante'],
  ['Frío', 'Helada', 'Necesitas bufanda'],
  ['Humedad', 'Sequedad', 'Condensación en pared'],
  ['Tormenta eléctrica', 'Vendaval', 'Rayos y truenos'],
  ['Huracán', 'Tifón', 'Vórtice tropical fuerte'],
  ['Tornado', 'Ciclón', 'Embudo de viento'],
  ['Nevada', 'Ventisca', 'Copos tapando calle'],
  ['Lluvia fina', 'Llovizna', 'Gotas casi imperceptibles'],
  ['Chubasco', 'Aguacero', 'Diluvio breve intenso'],
  ['Niebla densa', 'Neblina', 'No ves lejos'],
  ['Espresso', 'Cappuccino', 'Café muy corto'],
  ['Latte', 'Flat white', 'Leche con espuma'],
  ['Té verde', 'Té negro', 'Infusión hoja clara'],
  ['Infusión', 'Tisana', 'Manzanilla en taza'],
  ['Limonada', 'Naranjada', 'Cítrico con azúcar'],
  ['Horchata', 'Granizado de limón', 'Chufa valenciana fría'],
  ['Batido de chocolate', 'Granizado', 'Pajita en el vaso'],
  ['Agua tónica', 'Ginger ale', 'Amarga con gin'],
  ['Sidra natural', 'Cerveza artesanal', 'Manzana fermentada asturiana'],
  ['Sangría', 'Tinto de verano', 'Vino fruta hielo'],
  ['Tiramisú', 'Panna cotta', 'Mascarpone y cacao'],
  ['Flan', 'Natillas', 'Caramelo líquido arriba'],
  ['Arroz con leche', 'Crema catalana', 'Postre canela vainilla'],
  ['Tarta de queso', 'Cheesecake', 'Capa cremosa horneada'],
  ['Brownie', 'Cookie', 'Cuadrado húmedo cacao'],
  ['Magdalena', 'Muffin', 'Horneada en cápsula'],
  ['Churro', 'Porra', 'Con chocolate taza'],
  ['Buñuelo', 'Rosquilla', 'Bola aceite azúcar'],
  ['Helado de vainilla', 'Sorbete', 'Paseo de tarde'],
  ['Sorbete de limón', 'Granizado', 'Helado sin leche'],
  ['Monopoly', 'Risk', 'Calles y bancarrota'],
  ['Pictionary', 'Charadas', 'Dibujar y adivinar'],
  ['Scrabble', 'Boggle', 'Letras en tablero'],
  ['Uno', 'Póker', 'Cartas numeradas colores'],
  ['Mahjong', 'Dominó chino', 'Fichas con símbolos'],
  ['Lego', 'Meccano', 'Piezas encajan manual'],
  ['Puzzle 3D', 'Maqueta', 'Montar volumen piezas'],
  ['Coleccionismo', 'Antigüedades', 'Guardar series valiosas'],
  ['Filatelia', 'Numismática', 'Sellos en álbum'],
  ['Acuarela', 'Óleo', 'Pintura acuosa papel'],
  ['Teléfono', 'Interfono', 'Marcar y escuchar'],
  ['Fax', 'Escáner', 'Copia por línea'],
  ['Carta', 'Postal', 'Escribe y envía'],
  ['Tarjeta de visita', 'Folieto', 'Nombre y cargo empresa'],
  ['Anuncio', 'Publicidad', 'Comercial interrumpe serie'],
  ['Cartel', 'Banner', 'Pegado en calle'],
  ['Folleto', 'Catálogo', 'Pliegos informativos doblados'],
  ['Notificación', 'Alerta', 'Vibra en móvil'],
  ['Chat', 'Foro', 'Conversación instantánea'],
  ['Red social', 'Comunidad', 'Publicar fotos perfil'],
  ['Ladrillo', 'Bloque', 'Pared roja cocido'],
  ['Cemento', 'Hormigón', 'Mezcla que fragua'],
  ['Tejado', 'Cubierta', 'Protege de lluvia'],
  ['Chimenea', 'Conducto', 'Humo por tubo'],
  ['Viga', 'Columna', 'Sostiene techo puerta'],
  ['Pared', 'Muro', 'Divide estancias'],
  ['Suelo', 'Parqué', 'Piso bajo pies'],
  ['Azulejo', 'Mosaico', 'Brillo en baño'],
  ['Yeso', 'Estuco', 'Enlucido blanco pared'],
  ['Andamio', 'Escalera de obra', 'Trabajar en altura'],
  ['Electricidad', 'Corriente', 'Chispa y voltaje'],
  ['Energía solar', 'Molino de viento', 'Tejado moderno'],
  ['Panel solar', 'Molino de viento', 'Convierte rayos solares'],
  ['Central eléctrica', 'Generador', 'Produce megavatios'],
  ['Bombilla LED', 'Fluorescente', 'Luz blanca fría'],
  ['Enchufe USB', 'Cargador inalámbrico', 'Carga el móvil'],
  ['Gas', 'Butano', 'Llama azul cocina'],
  ['Petróleo', 'Gasolina', 'Pozo en el mar'],
  ['Carbón', 'Leña', 'Combustión negra'],
  ['Nuclear', 'Hidroeléctrica', 'Reactor y uranio'],
  ['Moda', 'Estilo', 'Pasarela y ropa'],
  ['Tendencia', 'Clásico', 'Lo de moda ahora'],
  ['Diseño', 'Patronaje', 'Bocetos y formas'],
  ['Pasarela', 'Desfile', 'Modelos caminan'],
  ['Boutique', 'Outlet', 'Ropa de lujo'],
  ['Marca', 'Etiqueta', 'Logo en ropa'],
  ['Talla', 'Medida', 'S, M o L'],
  ['Tejido', 'Tela', 'Material del vestido'],
  ['Algodón', 'Disco desmaquillante', 'Fibra blanda natural'],
  ['Lana', 'Cachemira', 'Viene de oveja'],
  ['Seda', 'Satén', 'Brillo suave lujo'],
  ['Denim', 'Pana', 'Pantalones vaqueros'],
  ['Estampado', 'Liso', 'Flores o rayas'],
  ['Rayas', 'Cuadros', 'Líneas paralelas'],
  ['Lunares', 'Flores', 'Puntos redondos'],
  ['Negro elegante', 'Blanco roto', 'Viste de gala'],
  ['Casual', 'Formal', 'Vaqueros y camiseta'],
  ['Sport', 'Smart casual', 'Ropa de gimnasio'],
  ['Vintage', 'Retro', 'Ropa de otra época'],
  ['Minimalista', 'Maximalista', 'Pocos colores'],
  ['Sonrisa', 'Guiño', 'Foto de grupo'],
  ['Abrazo', 'Beso', 'Brazos alrededor'],
  ['Saludo', 'Despedida', 'Hola con mano'],
  ['Conversación', 'Diálogo', 'Hablar en grupo'],
  ['Debate', 'Discusión', 'Opiniones enfrentadas'],
  ['Acuerdo', 'Pacto', 'Dar la mano'],
  ['Promesa', 'Compromiso', 'Juramento verbal'],
  ['Confianza', 'Lealtad', 'Creer en alguien'],
  ['Respeto', 'Educación', 'Tratar con cortesía'],
  ['Gratitud', 'Agradecimiento', 'Decir gracias'],
  ['Átomo', 'Molécula', 'Laboratorio'],
  ['Célula', 'Tejido', 'Laboratorio'],
  ['Gen', 'ADN', 'Código hereditario'],
  ['Virus', 'Bacteria', 'Infecta sin células'],
  ['Inyección preventiva', 'Anticuerpo', 'Pinchazo preventivo'],
  ['Experimento', 'Hipótesis', 'Tubo de ensayo'],
  ['Teoría', 'Ley', 'Explica fenómenos'],
  ['Laboratorio', 'Investigación', 'Probetas y bata'],
  ['Microscopio electrónico', 'Telescopio', 'Amplía lo diminuto'],
  ['Fórmula', 'Ecuación', 'Símbolos químicos'],
  ['Gravedad', 'Magnetismo', 'Manzana de Newton'],
  ['Electricidad estática', 'Corriente continua', 'Pelos que erizan'],
  ['Óptica', 'Acústica', 'Lentes y prismas'],
  ['Química orgánica', 'Biología', 'Laboratorio escolar'],
  ['Botánica', 'Zoología', 'Estudia las plantas'],
  ['Astronomía', 'Geología', 'Estrellas y planetas'],
  ['Geología', 'Meteorología', 'Rocas y capas'],
  ['Arqueología', 'Paleontología', 'Excava restos humanos'],
  ['Antropología', 'Sociología', 'Estudia culturas humanas'],
  ['Filosofía', 'Ética', 'Preguntas existenciales'],
  ['Batidora', 'Licuadora', 'Bate la masa'],
  ['Robot de cocina', 'Thermomix', 'Picar y mezclar solo'],
  ['Freidora de aire', 'Horno', 'Cocina pequeña'],
  ['Arrocera', 'Vaporera', 'Arroz perfecto solo'],
  ['Yogurtera', 'Heladera', 'Cultiva yogur casero'],
  ['Máquina de pan', 'Panificadora', 'Amasa y hornea'],
  ['Exprimidor', 'Centrifugadora', 'Zumo de naranja'],
  ['Hervidor', 'Calentador', 'Agua hirviendo rápido'],
  ['Campana extractora', 'Ventilador', 'Absorbe humo cocina'],
  ['Lavavajillas', 'Fregadero', 'Lava platos solo'],
  ['Semáforo peatonal', 'Paso de cebra', 'Luz para cruzar'],
  ['Banco de parque', 'Fuente', 'Sentarse al aire libre'],
  ['Farola', 'Poste', 'Ilumina la acera'],
  ['Contenedor', 'Papelera', 'Basura amarilla'],
  ['Grafiti', 'Mural', 'Pintura en muro'],
  ['Escaparate', 'Vitrina', 'Cristal de tienda'],
  ['Quiosco', 'Puesto', 'Vende prensa calle'],
  ['Parada de bus', 'Marquesina', 'Espera del autobús'],
  ['Carril bici', 'Acera', 'Exclusivo ciclistas'],
  ['Rotonda', 'Cruce', 'Circular sin semáforo'],
  ['Gallina ponedora', 'Pato doméstico', 'Huevos cada mañana'],
  ['Burro', 'Mula', 'Orejas largas'],
  ['Pavo real doméstico', 'Faisán', 'Plumas de colores'],
  ['Canario amarillo', 'Periquito', 'Canta en jaula'],
  ['Pez dorado', 'Betta', 'Acuario pequeño'],
  ['Tortuga de agua', 'Pez dorado', 'Pecera en casa'],
  ['Iguana', 'Camaleón', 'Lagarto verde grande'],
  ['Gecko', 'Salamanquesa', 'Trepa por paredes'],
  ['Erizo doméstico', 'Cobaya peruana', 'Púas pero manso'],
  ['Chinchilla', 'Degú', 'Pelaje muy suave'],
  ['Poema', 'Soneto', 'Versos y rima'],
  ['Ensayo', 'Artículo', 'Texto argumentativo'],
  ['Biografía', 'Novela', 'Estantería de no ficción'],
  ['Diario', 'Bitácora', 'Notas personales'],
  ['Guion', 'Teatro', 'Diálogos de película'],
  ['Prólogo', 'Epílogo', 'Antes del capítulo'],
  ['Capítulo', 'Escena', 'Página'],
  ['Personaje', 'Protagonista', 'Figura de ficción'],
  ['Narrador', 'Autor', 'Cuenta la historia'],
  ['Metáfora', 'Símil', 'Comparación poética'],
  ['Cuchara', 'Tenedor', 'Come la sopa'],
  ['Cucharón', 'Espumadera', 'Sirve caldo grande'],
  ['Colador', 'Rallador', 'Escurre la pasta'],
  ['Batidor', 'Varillas', 'Monta claras'],
  ['Tabla de cortar', 'Cuchillo de chef', 'Corta verduras encima'],
  ['Moldes', 'Bandeja', 'Hornea magdalenas'],
  ['Papel de horno', 'Aluminio', 'Forra la bandeja'],
  ['Film transparente', 'Bolsa hermética', 'Envuelve restos'],
  ['Temporizador', 'Termómetro de cocina', 'Cuenta minutos cocción'],
  ['Delantal de cocina', 'Guantes de horno', 'Protege la ropa'],
  ['Guacamole', 'Hummus', 'Aguacate machacado'],
  ['Tzatziki', 'Raita', 'Yogur con pepino'],
  ['Salsa boloñesa', 'Alioli', 'Plato de pasta'],
  ['Salsa carbonara', 'Alfredo', 'Huevo y panceta'],
  ['Gazpacho andaluz', 'Salmorejo', 'Tomate frío verano'],
  ['Tortilla de patatas', 'Empanada', 'Tapeo de bar'],
  ['Croqueta de jamón', 'Pincho', 'Bandeja de calamares'],
  ['Empanada gallega', 'Otro del mismo tipo', 'Masa rellena horno'],
  ['Pincho', 'Tapa', 'Palito en barra'],
  ['Ración', 'Menú', 'Bar de barrio'],
  ['Aceituna', 'Pepinillo', 'Verde en cóctel'],
  ['Anchoa', 'Sardina', 'Filete salado lata'],
  ['Atún en lata', 'Caballa', 'Conserva azul'],
  ['Queso fresco', 'Requesón', 'Sin curar'],
  ['Mozzarella', 'Burrata', 'Bolas para pizza'],
  ['Parmesano', 'Grana Padano', 'Rallado italiano duro'],
  ['Brie', 'Camembert', 'Queso francés cremoso'],
  ['Roquefort', 'Cabrales', 'Vetas azules'],
  ['Gouda', 'Edam', 'Holandés amarillo'],
  ['Cheddar', 'Emmental', 'Naranja británico'],
  ['Valle', 'Cañón', 'Entre dos montañas'],
  ['Meseta', 'Llanura', 'Altiplano extenso'],
  ['Acantilado', 'Faro', 'Caída vertical mar'],
  ['Bahía', 'Golfo', 'Mar entrante tierra'],
  ['Estuario', 'Delta', 'Río encuentra mar'],
  ['Pantano', 'Humedal', 'Agua estancada barro'],
  ['Pradera', 'Estepa', 'Hierba sin árboles'],
  ['Tundra', 'Taiga', 'Frío sin árboles'],
  ['Jungla', 'Bosque tropical', 'Selva densa húmeda'],
  ['Sabana', 'Pradera africana', 'África con hierba'],
  ['Navegador', 'Buscador', 'Abre páginas web'],
  ['Pestaña', 'Ventana', 'Varias webs abiertas'],
  ['Favorito', 'Marcador', 'Guarda un enlace'],
  ['Descarga', 'Subida', 'Guardar desde internet'],
  ['Captura de pantalla', 'Grabación', 'Foto de lo visible'],
  ['Filtro', 'Efecto', 'Cara con gafas'],
  ['Hashtag', 'Mención', 'Almohadilla en red'],
  ['Historia antigua', 'Publicación', 'Desaparece en un día'],
  ['Reels', 'Stories', 'Vídeo corto vertical'],
  ['Directo', 'Stream', 'Emisión en vivo'],
  ['Mascarilla facial', 'Exfoliante', 'Crema en cara'],
  ['Serum', 'Aceite facial', 'Gotas antes crema'],
  ['Protector solar', 'Aftersun', 'Factor cincuenta playa'],
  ['Bálsamo labial', 'Crema de manos', 'Neceser'],
  ['Esmalte', 'Pintauñas', 'Color en uñas'],
  ['Pinza de cejas', 'Rizador', 'Quita pelos ceja'],
  ['Secador de pelo', 'Plancha de pelo', 'Aire caliente cabeza'],
  ['Rizador de pestañas', 'Máscara', 'Curva el contorno ocular'],
  ['Esponja de maquillaje', 'Brocha', 'Aplica base líquida'],
  ['Algodón en bolas', 'Disco desmaquillante', 'Bolita blanca suave'],
  ['Peaje', 'Parking', 'Salida de autopista'],
  ['Gasolinera', 'Estación de servicio', 'Repostar combustible'],
  ['Área de descanso', 'Mirador', 'Parada en autopista'],
  ['Aparcamiento', 'Parking subterráneo', 'Dejar el coche'],
  ['Zona azul', 'Parking', 'Centro de la ciudad'],
  ['Radar', 'Cámara de tráfico', 'Multa por velocidad'],
  ['Carril BUS', 'Rotonda', 'Avenida transitada'],
  ['Rotonda grande', 'Glorieta', 'Círculo de tráfico'],
  ['Puente levadizo', 'Túnel', 'Puerto con barcos'],
  ['Viaducto', 'Pasarela', 'Carretera sobre valle'],
  ['Traductor', 'Intérprete', 'De idioma a idioma'],
  ['Bibliotecario', 'Archivero', 'Presta libros'],
  ['Conservador de museo', 'Guía turístico', 'Cuida obras arte'],
  ['Sommelier', 'Catador', 'Experto en vinos'],
  ['Pastelero', 'Panadero', 'Hace tartas dulces'],
  ['Carnicero', 'Charcutero', 'Corta la carne'],
  ['Pescadero', 'Frutero', 'Vende pescado fresco'],
  ['Florista', 'Jardinero', 'Arregla ramos'],
  ['Joyero', 'Relojero', 'Trabaja el oro'],
  ['Sastre', 'Modista', 'Arregla trajes'],
  ['Zapatero', 'Banco de entrada', 'Repara zapatos'],
  ['Cerrajero', 'Soldador', 'Abre sin llave'],
  ['Cristalero', 'Vidriero', 'Instala ventanas'],
  ['Techador', 'Pintor de brocha gorda', 'Pone tejas arriba'],
  ['Yesero', 'Escayolista', 'Pone tabiques'],
  ['Topógrafo', 'Agrimensor', 'Mide el terreno'],
  ['Geólogo', 'Minero', 'Estudia las rocas'],
  ['Piloto de drones', 'Operador de cámara', 'Vuela aparato remoto'],
  ['Community manager', 'Copywriter', 'Publica en Instagram'],
  ['SEO', 'SEM', 'Posiciona en Google'],
  ['Raqueta', 'Pelota de tenis', 'Golpea la pelota'],
  ['Bate', 'Guante de béisbol', 'Golpea la bola'],
  ['Palo de golf', 'Bola de golf', 'Hace el swing'],
  ['Casco de ciclista', 'Guantes de ciclismo', 'Protege la cabeza'],
  ['Gafas de natación', 'Gorro de baño', 'Ve bajo el agua'],
  ['Aletas', 'Tubo de buceo', 'Patas de rana'],
  ['Tabla de snowboard', 'Botas de esquí', 'Desliza en nieve'],
  ['Cuerda de escalada', 'Mosquetón', 'Asegura al escalador'],
  ['Pesas', 'Mancuernas', 'Levanta hierro gimnasio'],
  ['Banda elástica', 'Esterilla', 'Estira con resistencia'],
  ['Principio', 'Final', 'Donde empieza'],
  ['Inicio', 'Conclusión', 'Primer momento'],
  ['Pregunta', 'Respuesta', 'Signo de interrogación'],
  ['Problema', 'Solución', 'Encrucijada difícil'],
  ['Causa', 'Efecto', 'Lo que provoca'],
  ['Antes', 'Después', 'Momento anterior'],
  ['Arriba', 'Abajo', 'Hacia el cielo'],
  ['Dentro', 'Fuera', 'En el interior'],
  ['Cerca', 'Lejos', 'A pocos pasos'],
  ['Rápido', 'Lento', 'Sin demora'],
  ['Grande', 'Pequeño', 'Mucho tamaño'],
  ['Alto', 'Bajo', 'Mucha altura'],
  ['Ancho', 'Estrecho', 'Gran anchura'],
  ['Largo', 'Corto', 'Mucha distancia'],
  ['Pesado', 'Ligero', 'Cuesta levantarlo'],
  ['Duro', 'Blando', 'No cede al tacto'],
  ['Fuerte', 'Débil', 'Mucha intensidad'],
  ['Claro', 'Oscuro', 'Sin oscuridad'],
  ['Caliente', 'Frío', 'Quema al tacto'],
  ['Nuevo', 'Viejo', 'Sin estrenar'],
  ['Abierto', 'Cerrado', 'Entrada libre'],
  ['Lleno', 'Vacío', 'Sin espacio libre'],
  ['Limpio', 'Sucio', 'Sin manchas'],
  ['Seco', 'Mojado', 'Sin humedad'],
  ['Suave', 'Áspero', 'Agradable al tacto'],
  ['Brillante', 'Mate', 'Refleja la luz'],
  ['Transparente', 'Opaco', 'Se ve a través'],
  ['Recto', 'Tortuoso', 'Sin curvas'],
  ['Simple', 'Complejo', 'Pocos pasos'],
  ['Fácil', 'Difícil', 'Sin complicaciones'],
  ['Ramen', 'Udon', 'Caldo japonés'],
  ['Pho', 'Sopa miso', 'Caldo vietnamita'],
  ['Curry', 'Tikka masala', 'Especias indias'],
  ['Falafel', 'Kebab', 'Garbanzo frito'],
  ['Shawarma', 'Döner', 'Carne en vertical'],
  ['Gyozas', 'Dumplings', 'Empanadillas japonesas'],
  ['Spring rolls', 'Rollitos de primavera', 'Rollito crudo'],
  ['Tempura', 'Fritura', 'Rebozado japonés'],
  ['Teriyaki', 'Yakitori', 'Salsa dulce japonesa'],
  ['Onigiri', 'Maki', 'Triángulo de arroz'],
  ['Pad thai', 'Noodles', 'Wok tailandés'],
  ['Kimchi', 'Chucrut', 'Repollo picante coreano'],
  ['Guiso irlandés', 'Estofado francés', 'Con cerveza negra'],
  ['Fondue', 'Raclette', 'Queso derretido'],
  ['Crepe salado', 'Galette', 'Harina de trigo sarraceno'],
  ['Bagel', 'Pretzel', 'Pan con agujero'],
  ['Strudel', 'Croissant relleno', 'Postre austriaco'],
  ['Baklava', 'Kataifi', 'Miel y nueces'],
  ['Halva', 'Turrón', 'Dulce de sésamo'],
  ['Mochi', 'Dango', 'Arroz glutinoso'],
  ['Llaves de casa', 'Mando del garaje', 'Bolsillo del abrigo'],
  ['Cartera de cuero', 'Tarjetero', 'Guarda billetes'],
  ['Gafas de sol', 'Gorra', 'Terraza en agosto'],
  ['Paraguas plegable', 'Chubasquero fino', 'Para la lluvia'],
  ['Botella de agua', 'Termo de café', 'Hidratación diaria'],
  ['Cargador portátil', 'Power bank', 'Recarga el móvil'],
  ['Auriculares inalámbricos', 'Altavoz', 'Viaje en metro'],
  ['Funda del móvil', 'Protector de pantalla', 'Protege el teléfono'],
  ['Agenda física', 'Calendario digital', 'Apuntas citas'],
  ['Nota adhesiva', 'Recordatorio', 'Se pega al monitor'],
  ['Alce', 'Ciervo', 'Astas enormes'],
  ['Reno', 'Caribú', 'Tira del trineo'],
  ['Bisonte', 'Búfalo', 'Praderas americanas'],
  ['Antílope', 'Gacela', 'Salta en la sabana'],
  ['Ñu', 'Impala', 'Migración masiva'],
  ['Okapi', 'Jirafa', 'Rayas en las patas'],
  ['Tapir', 'Pecari', 'Hocico flexible'],
  ['Armadillo', 'Pangolín', 'Caparazón de placas'],
  ['Oso polar', 'Otro del mismo tipo', 'Hielo ártico'],
  ['Panda rojo', 'Koala', 'Zoo sombreado'],
  ['Lobo ártico', 'Oso polar', 'Tundra blanca'],
  ['Zorro ártico', 'Foca', 'Nieve intacta'],
  ['Lince ibérico', 'Águila', 'Parque natural'],
  ['Guepardo', 'Leopardo de las nieves', 'El más veloz'],
  ['Pantera negra', 'Jaguar negro', 'Felino oscuro'],
  ['Mandril', 'Babuino', 'Hocico colorido'],
  ['Lémur', 'Tarsier', 'Isla de Madagascar'],
  ['Perezoso', 'Oso hormiguero', 'Se mueve despacio'],
  ['Capibara', 'Nutria gigante', 'Roedor acuático'],
  ['Quokka', 'Wallaby', 'Sonrisa australiana'],
  ['Ciprés', 'Cedro', 'Árbol funerario'],
  ['Sauce', 'Álamo', 'Llorón junto al río'],
  ['Abedul', 'Fresno', 'Corteza blanca'],
  ['Castaño', 'Nogal', 'Fruto con cáscara'],
  ['Higuera', 'Morera', 'Fruta con semillas'],
  ['Granado', 'Membrillero', 'Grano rojo interior'],
  ['Cerezo', 'Ciruelo', 'Flores rosas primaverales'],
  ['Melocotonero', 'Albaricoquero', 'Fruta aterciopelada'],
  ['Plátano de sombra', 'Castaño de Indias', 'Hojas en abanico'],
  ['Eucalipto', 'Acacia', 'Aroma medicinal'],
  ['Rascacielos', 'Torre', 'Toca las nubes'],
  ['Edificio', 'Bloque de pisos', 'Donde vives'],
  ['Chalet', 'Adosado', 'Casa independiente'],
  ['Piso', 'Ático dúplex', 'Planta intermedia'],
  ['Loft', 'Estudio', 'Espacio diáfano'],
  ['Casa rural', 'Cortijo', 'Vacaciones en el campo'],
  ['Masía', 'Caserío', 'Construcción catalana'],
  ['Iglesia románica', 'Castillo', 'Pueblo antiguo'],
  ['Mezquita', 'Sinagoga', 'Cúpula y minarete'],
  ['Templo', 'Santuario', 'Lugar de culto'],
  ['Puente romano', 'Acueducto', 'Arcos de piedra'],
  ['Anfiteatro', 'Coliseo', 'Gradas ovaladas'],
  ['Muralla', 'Fortaleza', 'Protege la ciudad'],
  ['Torre del homenaje', 'Muralla', 'Ruinas visitables'],
  ['Claustro', 'Patio', 'Corredor con arcos'],
  ['Cúpula', 'Cimborrio', 'Techo redondeado'],
  ['Arco', 'Bóveda', 'Curva que sostiene'],
  ['Columnata', 'Pórtico', 'Filas de columnas'],
  ['Fachada', 'Portal', 'Cara del edificio'],
  ['Balaustrada', 'Barandilla', 'Protege un balcón'],
  ['Café con leche', 'Infusión', 'Desayuno de terraza'],
  ['Té con limón', 'Infusión de hierbas', 'Cítrico en la taza'],
  ['Agua mineral', 'Zumo', 'Nevera del picnic'],
  ['Hielo', 'Cubitos', 'Enfría la bebida'],
  ['Espuma de leche', 'Crema batida', 'Para el cappuccino'],
  ['Canela', 'Vainilla', 'Rama marrón aromática'],
  ['Nuez moscada', 'Clavo de olor', 'Especia de Navidad'],
  ['Jengibre', 'Cúrcuma', 'Raíz picante'],
  ['Curry en polvo', 'Pimentón', 'Mezcla especiada'],
  ['Orégano', 'Albahaca seca', 'Hierba mediterránea'],
  ['Salsa de soja', 'Wasabi', 'Pedido de sushi'],
  ['Wasabi', 'Rábano picante', 'Verde y picante'],
  ['Mostaza Dijon', 'Ketchup', 'Perrito en la feria'],
  ['Ketchup casero', 'Salsa BBQ', 'Tomate y azúcar'],
  ['Mayonesa light', 'Yogur griego', 'Para untar'],
  ['Aceite de oliva', 'Mantequilla', 'Ensalada de verano'],
  ['Vinagre balsámico', 'Limón', 'Ensalada Caprese'],
  ['Limón', 'Lima', 'Amarillo ácido'],
  ['Hierbas provenzales', 'Bouquet garni', 'Mezcla francesa'],
  ['Caldo de pollo', 'Sopa miso', 'Olla de domingo'],
  ['Harina', 'Maicena', 'Para amasar pan'],
  ['Levadura', 'Polvo de hornear', 'Hace crecer la masa'],
  ['Huevo batido', 'Clara a punto de nieve', 'Para rebozar'],
  ['Nata', 'Crema líquida', 'De vaca'],
  ['Mantequilla clarificada', 'Ghee', 'Sin lactosa'],
  ['Azúcar glas', 'Miel', 'Horneado casero'],
  ['Melaza', 'Sirope de arce', 'Subproducto de caña'],
  ['Chocolate negro', 'Regaliz', 'Caja de bombones'],
  ['Cacao puro', 'Cobertura de chocolate', 'Polvo amargo'],
  ['Almendras', 'Avellanas', 'Fruto seco alargado'],
  ['Nueces', 'Pistachos', 'Cáscara dura'],
  ['Anacardos', 'Cacahuetes', 'Forma de riñón'],
  ['Pasas de Corinto', 'Dátiles', 'Uva seca pequeña'],
  ['Higos secos', 'Orejones', 'Fruta del verano'],
  ['Coco rallado', 'Almendra', 'Bizcocho tropical'],
  ['Semillas de chía', 'Avena', 'Bol de desayuno'],
  ['Avena en copos', 'Salvado de avena', 'Cereal de desayuno'],
  ['Quinoa', 'Cuscús', 'Grano andino'],
  ['Bulgur', 'Trigo sarraceno', 'Trigo partido'],
  ['Lentejas', 'Garbanzos', 'Legumbre pequeña'],
  ['Alubias', 'Judías verdes', 'Legumbre en conserva'],
  ['Guisantes', 'Habas', 'Verde en vaina'],
  ['Soja', 'Edamame', 'Legumbre asiática'],
  ['Tofu', 'Tempeh', 'Cuajada de soja'],
  ['Seitán', 'Proteína vegetal', 'Gluten de trigo'],
  ['Hamburguesa vegetal', 'Falafel', 'Local vegetariano'],
  ['Leche de almendras', 'Zumo de avena', 'Café de especialidad'],
  ['Yogur vegetal', 'Kéfir', 'Nevera del súper'],
  ['Queso vegano', 'Hummus', 'Tabla de picoteo'],
  ['Mantequilla vegetal', 'Margarina', 'Para untar pan'],
  ['Cama individual', 'Sofá cama', 'Habitación de invitados'],
  ['Litera', 'Sofá cama', 'Dos niveles'],
  ['Hamaca de jardín', 'Columpio de terraza', 'Balanceo al aire libre'],
  ['Mesa de centro', 'Mesita auxiliar', 'Delante del sofá'],
  ['Estantería modular', 'Librería', 'Guarda libros'],
  ['Aparador', 'Vitrina', 'Mueble del comedor'],
  ['Cómoda', 'Cajonera', 'Cajones en dormitorio'],
  ['Perchero', 'Colgador', 'Para abrigos'],
  ['Mueble zapatero', 'Banco de entrada', 'Para calzado'],
  ['Espejo de cuerpo entero', 'Perchero', 'Recibidor'],
  ['Alfombra redonda', 'Cortina', 'Salón acogedor'],
  ['Cojín decorativo', 'Manta', 'Sofá del salón'],
  ['Manta de sofá', 'Plaid', 'Calor en el salón'],
  ['Lámpara de pie', 'Velas', 'Rincón de lectura'],
  ['Aplique', 'Plafón', 'Luz en la pared'],
  ['Tira LED', 'Guirnalda', 'Luces decorativas'],
  ['Velas aromáticas', 'Difusor', 'Aroma en casa'],
  ['Incienso', 'Sahumerio', 'Humo aromático'],
  ['Planta artificial', 'Cuadro', 'Estantería'],
  ['Florero', 'Jarrón', 'Para flores cortadas'],
  ['Reloj de pared', 'Calendario', 'Cocina familiar'],
  ['Calendario de pared', 'Planner', 'Marca los días'],
  ['Pizarra magnética', 'Corcho', 'Imanes y notas'],
  ['Marco de fotos', 'Portarretratos', 'Enmarca recuerdos'],
  ['Álbum de fotos', 'Galería digital', 'Páginas con recuerdos'],
  ['Caja de recuerdos', 'Baúl', 'Guarda tesoros'],
  ['Cesta de mimbre', 'Caja de madera', 'Fibra trenzada'],
  ['Organizadores', 'Separadores', 'Orden en cajones'],
  ['Perchas', 'Ganchos', 'Cuelgan la ropa'],
  ['Cajas bajo cama', 'Organizadores de armario', 'Espacio oculto'],
  ['Pelador', 'Rallador', 'Verdura preparada'],
];
